### ISSUE TITLE
C++ code generated by quicktype does not compile in Visual Studio 2017 when "conformance mode" is off

### ISSUE THREAD

**Issue by tjerzyko** [quicktype/quicktype#1024]
I have generated C++ code from JSON Schema "Coordinate" and tried compiling it with VS 15.7.6. It turned out that if you set "Conformance mode" to "No", it doesn't compile. I have attached the sample project and a screenshot of the said option.
The error is as follows:

```
1>------ Build started: Project: quicktype_compilation, Configuration: Debug Win32 ------
1>stdafx.cpp
1>quicktype_compilation.cpp
1>s:\quicktype_compilation\quicktype_compilation\vd_json_serializer.h(18): error C2679: binary '=': no operator found which takes a right-hand operand of type 'double' (or there is no acceptable conversion)
...
```
You can see it yourself when compiling my project.

[quicktype_compilation.zip](https://github.com/quicktype/quicktype/files/2273880/quicktype_compilation.zip)
![image](https://user-images.githubusercontent.com/42238889/43894814-907b129c-9bd3-11e8-9748-aefa8c930413.png)

**Comment by schani** [comment]
Why do you need to use "Conformance mode" = No?

Do you know how to change the generated code to make it work with Conformance turned off?

**Comment by tjerzyko** [comment]
I'm working on a rather large codebase which does not compile otherwise. Majority of the code was written long time ago, we are targeting Win XP and therefore we are using old Microsoft SDK, which is incompatible (confirmed by MS itself).

I have no idea how to fix generated code, and even if I had, it would be impractical, because I want to generate it on the fly, during build process.

**Comment by tjerzyko** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance
"The /permissive- option is compatible with almost all of the header files from the latest Windows Kits, such as the Software Development Kit (SDK) or Windows Driver Kit (WDK), starting in the Windows Fall Creators SDK (10.0.16299.0). Older versions of the SDK may fail to compile under /permissive- for various source code conformance reasons."

**Comment by schani** [comment]
Could you try changing the offending line to

```
            if (!opt) j = nullptr; else j = (json)*opt;
```

and tell me whether that works for you?

**Comment by tjerzyko** [comment]
Yes, it fixes this particular problem in both conformance modes, however another error appears - a few lines later:
```
1>------ Build started: Project: quicktype_compilation, Configuration: Debug Win32 ------
1>quicktype_compilation.cpp
1>s:\quicktype_compilation\quicktype_compilation\vd_json_serializer.h(22): error C2672: 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::get': no matching overloaded function found
```

**Comment by schani** [comment]
Sorry, that's beyond my C++ skills.  If you can figure out how to fix it then I can make quicktype generate that code.

**Comment by tjerzyko** [comment]
Thanks, I will try and let you know.

**Comment by tjerzyko** [comment]
We have found a way to make generated code compile, even without your previous fix (added cast). However, we don't know why it helped. Maybe you will have better idea what's going on here. We moved `from_json` and `to_json` functions from `nlohmann` namespace  to the end of `quicktype` namespace.

This is what is moved:
```
namespace nlohmann {
    inline void from_json(const json& _j, quicktype::VdJsonSerializer& _x) {
        _x.latitude = quicktype::get_optional<double>(_j, "latitude");
        _x.longitude = quicktype::get_optional<double>(_j, "longitude");
    }

    inline void to_json(json& _j, const quicktype::VdJsonSerializer& _x) {
        _j = json::object();
        _j["latitude"] = _x.latitude;
        _j["longitude"] = _x.longitude;
    }
}
```

**Comment by schani** [comment]
Could you check whether those two changes will make a more complex schema work, too?  Like the `pokedex.json` sample on `app.quicktype.io`?

**Comment by tjerzyko** [comment]
I will let you know on Monday.

**Comment by schani** [comment]
@tjerzyko Any updates on this?

**Comment by tjerzyko** [comment]
Sorry, I've forgotten about this issue.
Moving these functions from nlohmann namespace to the end of quicktype namespace seems to be working in every case we encountered.

**Comment by schani** [comment]
I can't make this trivially work, and don't want to spend any more on it, to be honest, given my weak C++ skills.  I'm closing this for now.  Feel free to send us a PR if you managed to fix the issue.

**Comment by tjerzyko** [comment]
Thank you for yor great work!

pt., 31 sie 2018, 22:57 użytkownik Mark Probst <notifications@github.com>
napisał:
