### ISSUE TITLE
Fix error message for introspect queries when output arg is missing

### ISSUE THREAD

**Issue by transitive-bullshit** [quicktype/quicktype#1035]
Hey guys, really excited about using `quicktype` 💯 

We're trying to get basic graphql introspection working and have been unable to get anything to work on a variety of public and proprietary GraphQL APIs.

platform: mac os high sierra
node: 10.3.0
npm: 6.2.0

```
npm i -g quicktype

quicktype --http-method POST --graphql-introspect https://graphql.communitygraph.org/graphql/
```

which produces stdout:
```
given headers: []
headers are {"Accept":"application/json","Content-Type":"application/json"}
Error: Please specify at least one GraphQL query as input.
```

We've tried a lot of different variations of this type of execution and have yet to get a single graphql introspection query to succeed. There's a good chance we're doing something obviously wrong here, and we needed to use POST as in #619. Judging by the relevant [code](https://github.com/quicktype/quicktype/blob/master/src/cli/GraphQLIntrospection.ts#L35), the official `introspectionQuery` provided by GraphQL is being used, so I'm not sure why or how we would supply an additional query on top of that.

Any help is greatly appreciated!

cc @chrisvxd

**Comment by transitive-bullshit** [comment]
Awesome, thanks for the quick response!

Would it make sense to add `stdout` as the default output as is the case with most CLIs?

**Comment by schani** [comment]
We wrote [a blog post about GraphQL](https://blog.quicktype.io/graphql-with-quicktype/), btw, in case you didn't know.

**Comment by schani** [comment]
Yes, it should write to `stdout`.  This option was just hacked together quickly, I apologize.

**Comment by transitive-bullshit** [comment]
Thanks for following up on this @schani && no need to apologize.

My colleagues and I are working on a project that is very related to this space, and you'll like see some more feedback + PRs from us in the weeks to come.

In general, it's great to see that your team has already put so much quality, open-source work into building something that we were previously looking to build ourselves! 💯 

Thanks again!
- Travis

**Comment by schani** [comment]
That's great to hear, Travis!  Looking forward to your contributions.
