### ISSUE TITLE
Tagging "good first issues"

### ISSUE THREAD

**Issue by transitive-bullshit** [quicktype/quicktype#1039]
Quick suggestion that it'd be great if the "good first issue" label was added to some of the easiest GH issues. Their current labeling is really solid, just was trying to find a good area to start and noticed this was missing.

Cheers!

**Comment by schani** [comment]
We've been using the [help wanted tag](https://github.com/quicktype/quicktype/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22), but maybe "good first issue" is better?  Also it's out of date - I'll go through them and relabel.  Thanks!

**Comment by schani** [comment]
Ok, it's [good first issue](https://github.com/quicktype/quicktype/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+) now, and I went through and re-tagged.  Note that they are not necessarily easy, but they don't require deep quicktype knowledge.
