### ISSUE TITLE
Infer property as enum if its values are a subset of an inferred enum

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#1040]
In the pokedex sample, each pokemon has `type` and `weaknesses` properties. `weaknesses` is inferred to be an `Array<Weakness>` and `type` is inferred as `Array<String>`. `type` values are always members of the `Weakness` enum so maybe we could infer `type` as `Array<Weakness>` as well?

```json
    {
      "name": "Bulbasaur",
      "type": [
        "Grass",
        "Poison"
      ],
      "weaknesses": [
        "Fire",
        "Ice",
        "Flying",
        "Psychic"
      ]
    }
```

**Comment by schani** [comment]
Good one!
