### ISSUE TITLE
Add wordwrap as direct dependency.

### ISSUE THREAD

**Issue by qm3ster** [quicktype/quicktype#1041]
Module `wordwrap` is used directly in this project, but it is not in package.json https://github.com/quicktype/quicktype/blob/392abdeaef7f7ac556d2d673f6b0a617eb30e9ff/src/cli/index.ts#L49
https://github.com/quicktype/quicktype/blob/57f40208c25c2a552cc3524fcb0c8fba78f574bb/src/quicktype-core/ConvenienceRenderer.ts#L28
This leads to errors when installing with `pnpm`

**Comment by qm3ster** [comment]
@schani Done. What does that one do?

**Comment by schani** [comment]
@qm3ster We build separate packages for parts of quicktype that can be used as a library without having to bring in all dependencies that full quicktype comes with.  Here's a blog post on how to use it: https://blog.quicktype.io/customizing-quicktype/

**Comment by jheaff1** [comment]
This seems to be an issue again as this PR removed wordwrap as a direct dependency of quicktype:

https://github.com/glideapps/quicktype/pull/2108
