### ISSUE TITLE
Specific JSON Fails to Generate TypeScript

### ISSUE THREAD

**Issue by TheNickmaster21** [quicktype/quicktype#1060]
Hello, I have found that this specific JSON causes only the "// Generated by https://quicktype.io" comment to appear and will not generate any TypeScript code. Removing any property from the JSON will resolve the issue and paste the expected TypeScript. 

`{  
  "ins_phone area":"aq",
  "ins_phone":"ar",
  "ins_policy":"as",
  "ins_dob_mm":"at",
  "ins_dob_dd":"au",
  "ins_dob_yy":"av",
  "ins_sex":"M",
  "other_ins_name":"ax",
  "other_ins_policy":"ay"
}`

`// Generated by https://quicktype.io

export interface TopLevel {
    ins_phone:        string;
    ins_policy:       string;
    ins_dob_mm:       string;
    ins_dob_dd:       string;
    ins_dob_yy:       string;
    ins_sex:          string;
    other_ins_name:   string;
    other_ins_policy: string;
}

// Generated by https://quicktype.io

export interface TopLevel {
    "ins_phone area": string;
    ins_policy:       string;
    ins_dob_mm:       string;
    ins_dob_dd:       string;
    ins_dob_yy:       string;
    ins_sex:          string;
    other_ins_name:   string;
    other_ins_policy: string;
}

// Generated by https://quicktype.io

export interface TopLevel {
    "ins_phone area": string;
    ins_phone:        string;
    ins_dob_mm:       string;
    ins_dob_dd:       string;
    ins_dob_yy:       string;
    ins_sex:          string;
    other_ins_name:   string;
    other_ins_policy: string;
}

// Generated by https://quicktype.io

export interface TopLevel {
    "ins_phone area": string;
    ins_phone:        string;
    ins_policy:       string;
    ins_dob_mm:       string;
    ins_dob_yy:       string;
    ins_sex:          string;
    other_ins_name:   string;
    other_ins_policy: string;
}

// Generated by https://quicktype.io

export interface TopLevel {
    "ins_phone area": string;
    ins_phone:        string;
    ins_policy:       string;
    ins_dob_mm:       string;
    ins_dob_dd:       string;
    ins_sex:          string;
    other_ins_name:   string;
    other_ins_policy: string;
}

// Generated by https://quicktype.io

export interface TopLevel {
    "ins_phone area": string;
    ins_phone:        string;
    ins_policy:       string;
    ins_dob_mm:       string;
    ins_dob_dd:       string;
    ins_dob_yy:       string;
    other_ins_name:   string;
    other_ins_policy: string;
}

// Generated by https://quicktype.io

export interface TopLevel {
    "ins_phone area": string;
    ins_phone:        string;
    ins_policy:       string;
    ins_dob_mm:       string;
    ins_dob_dd:       string;
    ins_dob_yy:       string;
    ins_sex:          string;
    other_ins_policy: string;
}

// Generated by https://quicktype.io

export interface TopLevel {
    "ins_phone area": string;
    ins_phone:        string;
    ins_policy:       string;
    ins_dob_mm:       string;
    ins_dob_dd:       string;
    ins_dob_yy:       string;
    ins_sex:          string;
    other_ins_name:   string;
}

// Generated by https://quicktype.io
`

**Comment by schani** [comment]
quicktype is guessing (incorrectly) that your type is map, not a class.  You can turn off map detection in the Options panel:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/61363/45338545-f5950380-b58d-11e8-9823-97fdf311d769.png">
