### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by matejdro** [quicktype/quicktype#1066]
Not sure what exactly is the issue, but page does not seem to load on my PC. It just show blank white page. Chrome's console shows up couple of javascript errors:

[app.quicktype.io-1537088002014.log](https://github.com/quicktype/quicktype/files/2386428/app.quicktype.io-1537088002014.log)

EDIT: Clearing cookies and local storage helped. I assume there is a bug when loading old storage format?

**Comment by dvdsgl** [comment]
Interesting, thanks for the report. Did you by any chance try the Generate App button? Perhaps that experimental feature introduced a bug.

**Comment by matejdro** [comment]
Nope, white screen started even before that button was even available.

**Comment by schani** [comment]
Moved to the UI repo.
