### ISSUE TITLE
Unable to create codable object for the specific json in swift

### ISSUE THREAD

**Issue by souvickcse** [quicktype/quicktype#1069]
For the following json:
`{
"explore_category_collection": [
{
"entity_id": "112",
"attribute_set_id": "3",
"parent_id": "2",
"created_at": "2018-05-01 09:48:07",
"updated_at": "2018-08-30 15:00:25",
"path": "1/2/112",
"position": "4",
"level": "2",
"children_count": "0",
"is_deal": "1",
"name": "Summer Girls",
"image": "Summer_Girls-02_-_Copy.jpg",
"url_key": "summer-girls",
"deal_end": "2018-10-31 00:00:00",
"start_from": "99"
}
]
}`
It is giving me `let exploreCategoryCollection: [[String: String]]?` but it supposed to be give a codable object.
Thank You.

**Comment by schani** [comment]
quicktype is guessing that that's a map, since it has a lot of keys and all the values are strings.  You can turn that off in the UI:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/61363/45818781-945ce680-bc97-11e8-8427-20b1a4814798.png">
