### ISSUE TITLE
Python: Floats (with zeros?) are auto-converted to ints when pasted into the app

### ISSUE THREAD

**Issue by amqdn** [quicktype/quicktype#1087]
For example, this:
```
{
    "tax": 0.0,
    "subtotal": 0.0,
    "total": 0.0,
    "balance": 0.0,
}
```
...in the app becomes this:
```
{
    "tax": 0,
    "subtotal": 0,
    "total": 0,
    "balance": 0,
}
```

The values are then subsequently typed as `int` and call the `from_int` function, but this causes an `AssertionError` for these fields when my data is passed and the parser is called. Unless there's some reason for this that I'm not aware of, they should be typed `float` and should call a `from_float` function. I worked around the current behavior by doing as such. 

Thanks!

**Comment by schani** [comment]
Fixed.
