### ISSUE TITLE
Feature - Using Lombok

### ISSUE THREAD

**Issue by g4rcez** [quicktype/quicktype#1099]
My feature suggestion is using [lombok](https://projectlombok.org) instead getters and setters of tradicional Java Style.

**Comment by schani** [comment]
@vandalvnl Would you consider contributing this?  We'd be happy to help you along.

**Comment by schani** [comment]
That's awesome!

A few pointers:

* [Here's the code](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/Java.ts) that produces the Java output.

* Right now it's just one class, `JavaRenderer`, that produces Java classes with all the Jackson stuff.  [C# is better separated](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/CSharp.ts).  There, we have a `CSharpRenderer` which produces "naked" C# classes, and a subclass `NewtonsoftCSharpRenderer` which also produces the additional stuff for Json.NET.

* The proper way to do it is to first separate `JavaRenderer` like with C# into a `JavaRenderer` and a `JacksonJavaRenderer`.  That would be a great first pull request.

* Then you can subclass `JavaRenderer` with a `LombokJavaRenderer` which generates the Lombok code you need.

Again, if you need any help at all, please don't hesitate to ask!  You might also want to [join us on Slack](http://slack.quicktype.io) where we can discuss more efficiently.

Cheers!
