### ISSUE TITLE
Please add support for Fail-able properties (in Swift Code)

### ISSUE THREAD

**Issue by arindavoodian** [quicktype/quicktype#1105]
Current implementation does not support fail-able properties thus if parameters do not match or do not exist parse process produces nil (at least in Swift code).

It would be great if Fail-able properties was implemented.

Thanks.

**Comment by schani** [comment]
I'm not familiar with failable properties.  Could you give an example of what the generated code would look like?

**Comment by arindavoodian** [comment]
Here is an example from a class I'm working on. This is from an API call generated with Swagger and YAML

open class TnsMSAPIProgramInfoRetail: Codable {

    public var customFee: TnsArrayOfMSAPICustomFeeRetail?
    public var customFeeTax: Double?
    public var isCashDeal: Bool?
    public var rebateTax: Double?
    public var rebateTaxPct: Double?
    public var totalTaxesFees: Double?


    
    public init(customFee: TnsArrayOfMSAPICustomFeeRetail?, customFeeTax: Double?, isCashDeal: Bool?, rebateTax: Double?, rebateTaxPct: Double?, totalTaxesFees: Double?) {
        self.customFee = customFee
        self.customFeeTax = customFeeTax
        self.isCashDeal = isCashDeal
        self.rebateTax = rebateTax
        self.rebateTaxPct = rebateTaxPct
        self.totalTaxesFees = totalTaxesFees
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(customFee, forKey: "CustomFee")
        try container.encodeIfPresent(customFeeTax, forKey: "CustomFeeTax")
        try container.encodeIfPresent(isCashDeal, forKey: "IsCashDeal")
        try container.encodeIfPresent(rebateTax, forKey: "RebateTax")
        try container.encodeIfPresent(rebateTaxPct, forKey: "RebateTaxPct")
        try container.encodeIfPresent(totalTaxesFees, forKey: "TotalTaxesFees")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        customFee = try container.decodeIfPresent(TnsArrayOfMSAPICustomFeeRetail.self, forKey: "CustomFee")
        customFeeTax = try container.decodeIfPresent(Double.self, forKey: "CustomFeeTax")
        isCashDeal = try container.decodeIfPresent(Bool.self, forKey: "IsCashDeal")
        rebateTax = try container.decodeIfPresent(Double.self, forKey: "RebateTax")
        rebateTaxPct = try container.decodeIfPresent(Double.self, forKey: "RebateTaxPct")
        totalTaxesFees = try container.decodeIfPresent(Double.self, forKey: "TotalTaxesFees")
    }
}

**Comment by schani** [comment]
I don't exactly understand what bug this is solving.  Could you please give an example of a case where parsing with quicktype doesn't work as you expect, and what exactly you expect to happen instead?

**Comment by arindavoodian** [comment]
I'm using a Quicktype generated model with a struct which is being populated with a returned network object type from a rest based API. The problem I’m encountering is that for certain network calls the returned object may not contain all of the object parameters in the struct and the object does not initialize. nil is returned instead:

struct Rebate: Codable {
    let categoryID: Int?
    let customerTypes: [RebateCustomerType]?
    let financialInstitution: String
    let financialInstitutionID: Int
    let id: Int
    let identCode: String
    let lenderCode: String
    let maxCreditScore: Int
    let minCreditScore: Int
    let name: String
    let nameDisplay: String
    let number: String
    let receipientType: Int
    let revisionDate: String
    let selected: Bool?
    let startDate: String
    let stopDate: String
    let terms: [Term]?
    let transactionType: Int
    let type: Int
    let updateTS: String
    let value: RebateValue
    let valueType: Int
    let isGeneric: Bool?
    let maxTerm: [MaxTerm]?

I’d like to find out how I can ignore, for example, the maxTerm parameter, or any other parameter, if the network call return data does not have that data in its structure.

The API we are using has changing class structures for a number of parameters. This causes the data to not properly parse into a valid class object since the returned data structure does not contain a particular parameter.

BTW... Thanks for making such a useful tool!

**Comment by schani** [comment]
If you want all properties to be optional, you can use the "Make all properties optional" switch:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/61363/48008528-c0f58200-e0ce-11e8-90bf-52e05123637c.png">

If you want to be more specific about which properties are optional you can either

1. Generate JSON Schema, modify it to make those properties non-required, and generate Swift from the modified schema.
2. Use quicktype's "Multiple JSON" mode to give more than one JSON input: one where all properties are present, and another one where all the optional ones are missing.

Do any of those work for you?

**Comment by arindavoodian** [comment]
I have tried making all properties optional but this still causes a returned nil for the parse as described in my previous comment when a parameter does not exist in the returned data.

How would I make all properties non-required? Do you mean optional or something else?

I was also unable to find quicktype's "Multiple JSON" mode.

Again, having parameters being fail-able or optional, if there is a difference is one of the only things preventing me from going live with our app right now.

I'd love to fix this issue on my side asap. Thanks for your help.

**Comment by arindavoodian** [comment]
I generated a JSON schema then altered all required to non-required, exported to quicktype as JSON schema, and copied the struct into an Xcode playground.

I'm still getting nils on the parse and I'm sure that the network operation was successful.

Strange..

**Comment by schani** [comment]
Could you post a complete reproducible test case?  A simple Xcode project for example?

**Comment by arindavoodian** [comment]
Could I email you a playground since there are api keys which should stay private?

**Comment by schani** [comment]
Sure.  mark@quicktype.io

**Comment by arindavoodian** [comment]
Sent.

**Comment by schani** [comment]
This is the exception that the decoding throws:

```
valueNotFound(Swift.Double, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "LimitedLeaseRetailData", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "Program", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "APRLMF", intValue: nil), _JSONKey(stringValue: "Index 21", intValue: 21)], debugDescription: "Expected Double but found null value instead.", underlyingError: nil))
```

You've only ever shown quicktype `APRLMF` arrays that contain only numbers, but the actual data also contains `null`s.  The "Make all properties optional" only applies to properties, not array items.

**Comment by arindavoodian** [comment]
I see that now.

Thanks!

Any quick fix you would recommend for me to fix that?

**Comment by arindavoodian** [comment]
Thanks!

**Comment by arindavoodian** [comment]
Hi Mark,

A quick update on the failable initializers addition I had asked about.

A quick way to achieve this would be to set nil coalesced values and
variable parameters as such:

init?(snapshot: DataSnapshot) {

        if let dict = snapshot.value as? [String : AnyObject] {

            email = dict["email"] as? String ?? ""

            firstName = dict["firstName"] as? String ?? ""

            lastName = dict["lastName"] as? String ?? ""

            messageToken = dict["messageToken"] as? String ?? ""

            streetAddress = dict["streetAddress"] as? String ?? ""

            cityAddress = dict["cityAddress"] as? String ?? ""

            stateAddress = dict["stateAddress"] as? String ?? ""

            zipAddress = dict["zipAddress"] as? String ?? ""

            phoneNumber = dict["phoneNumber"] as? String ?? ""



            driverLicenseNumber = dict["driverLicenseNumber"] as? String ??
""



            businessName = dict["businessName"] as? String ?? ""

            businessStreetAddress = dict["businessStreetAddress"] as?
String ?? ""

            businessCityAddress = dict["businessCityAddress"] as? String ??
""

            businessStateAddress = dict["businessStateAddress"] as? String
?? ""

            businessZipAddress = dict["businessZipAddress"] as? String ?? ""

            businessPhone = dict["businessPhone"] as? String ?? ""



            userIsAdmin = dict["userIsAdmin"] as? String ?? ""

            userIsDealer = dict["userIsDealer"] as? String ?? ""

        } else {

            return nil

        }




This would work for any type not just [String : AnyObject] and would still
return values even if one or more properties did not exist in a database.


Thanks again.
