### ISSUE TITLE
Too many private APIs

### ISSUE THREAD

**Issue by alan-agius4** [quicktype/quicktype#1118]
Hi,

Firstly I must say that this is a great tool, however I stumbled a bit on a problem. I really don't want that acronyms gets upper cases https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/support/Acronyms.ts#L4, as a matter of fact I want these to be treated the same as any other word.

The 'simplest' approach that I ended up finding was to extend the `TypeScriptRenderer` and `TypeScriptTargetLanguage` which I quickly ended up realising that extending is no so simple as there are a lot of private methods.

Code: 
```js
// todo: open issue with quicktype
const {
  combineWords,
  firstUpperWordStyle,
  allUpperWordStyle,
  utf16LegalizeCharacters,
} = require('quicktype-core/dist/support/Strings');

const {
  isES3IdentifierPart,
  isES3IdentifierStart,
} = require('quicktype-core/dist/language/JavaScriptUnicodeMaps');

const { funPrefixNamer } = require('quicktype-core/dist/Naming');

/**
 * This is a custom TypeScript
 * 
 * By default QuickType a list of acronyms that when matched will be converted to upper case.
 * @see {@link https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/support/Acronyms.ts#L4}
 */
class TypeScriptRendererCustom extends TypeScriptRenderer {

  _nameStyle(original) {
    const words = splitIntoWords(original);
    return combineWords(words,
      utf16LegalizeCharacters(isES3IdentifierPart),
      firstUpperWordStyle,
      firstUpperWordStyle,
      firstUpperWordStyle,
      firstUpperWordStyle,
      '',
      isES3IdentifierStart
    );
  }

  makeNamedTypeNamer() {
    return funPrefixNamer("types", s => this._nameStyle(s));
  }

  makeEnumCaseNamer() {
    return funPrefixNamer("types", s => this._nameStyle(s));
  }

}


class TypeScriptTargetLanguageCustom extends TypeScriptTargetLanguage {
  constructor() {
    super("TypeScript", ["typescript", "ts"], "ts");
  }

  makeRenderer(renderContext, untypedOptionValues) {
    const options = {};
    const kebabToCamel = (input) => input.replace(/-([a-z])/g, g => g[1].toUpperCase());
    super.getOptions().forEach(o => {
      let name = o.definition.name;
      // https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/TypeScriptFlow.ts#L24
      name = name === 'explicit-unions' ? 'declareUnions' : kebabToCamel(name);
      options[name] = o;
    });
    return new TypeScriptRendererCustom(this, renderContext, getOptionValues(options, untypedOptionValues));
  }
}
```

I'd like that things like this are exposed or actually have more control on certain options.

**Comment by alan-agius4** [comment]
@dvdsgl, thanks for your reply? And documentation or example on what I need to do?

Thanks.

**Comment by dvdsgl** [comment]
Here is a PR that added an option to C#: https://github.com/quicktype/quicktype/pull/762/files

You can see options available by typing just `quicktype` on the CLI, or looking at the options pad in the web UI.

**Comment by alan-agius4** [comment]
@dvdsgl, you mean create the option in the actual quicktype API?

**Comment by dvdsgl** [comment]
Yes. Different languages (e.g. TypeScript vs. C++) capitalize acronyms differently, so you should be able to add an option to the TypeScript language that lets the user configure this.
