### ISSUE TITLE
minlength is not considered for JSON schema 

### ISSUE THREAD

**Issue by kiranpradeep** [quicktype/quicktype#1136]
The generated C# or C++ class for below JSON schema has no validation on minlength.
{
  "type": "object",
  "properties": {
    "quality": {
      "type": "string",
      "minlength": 1
    }
  }
}

**Comment by schani** [comment]
The property is called `minLength`, not `minlength`.  It is supported in C++, but not in C#.  It isn't too hard to implement it - are you interested in contributing?

**Comment by kiranpradeep** [comment]
@schani I am new to TypeScript. But, will give a try and let you know if I can't. Can you please give a starting point?

**Comment by ThomasUllrich666** [comment]
@schani Can you do the same thing for Java? I want to use the minLength/maxLength option there too :-)
