### ISSUE TITLE
VSCode DAP

### ISSUE THREAD

**Issue by robbym** [quicktype/quicktype#1137]
When running quicktype on VSCode's debug protocol schema ([DAP](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json)), the code it produces simply returns a raw map/dictionary/hashtable.

Am I doing something wrong?

**Comment by schani** [comment]
The top-level type of that schema is `object`, with no further constraints, so that's what you get.  But you can tell quicktype to make types for all `definitions`, like this:

```
quicktype --src-lang schema "https://raw.githubusercontent.com/Microsoft/vscode-debugadapter-node/master/debugProtocol.json#/definitions/"
```

**Comment by robbym** [comment]
Works. Thanks!

**Comment by mkrawczuk** [comment]
Actually it doesn't.
I've checked out from the most recent master branch revision, ran 
`./script/quicktype -l typescript --src-lang schema "https://raw.githubusercontent.com/Microsoft/vscode-debugadapter-node/master/debugProtocol.json#/definitions/" -o dap.ts`
and got this: https://file.io/O1vzB6
Actual specification in TypeSript for reference: https://microsoft.github.io/debug-adapter-protocol/specification

Notice how inheritance relations are not persisted, and a lot of 'fun-name' types are generated, like `ArakGroundhog1` to `ArakGroundhog36`

@robbym , would you be kind enough to confirm it's actually working and share your solution to this problem?

**Comment by schani** [comment]
I looked at random names (my output is [here](https://gist.github.com/schani/543af8e337fe1283c4c354432d9885b9)), and all of them are enums with one or two values, such `PurpleArakGroundhog`: This is the single-value `enum` `"request"`, which is used by a bunch of different types.  Were it only used by, say, `Request`, quicktype would name it `Type` or `RequestType`, but if there are too many possible names, quicktype gives up and picks a random name.  One solution would be to give a `title` to the type in JSON Schema.  A TypeScript-only solution would be to not even generate an `enum` in the first place.  That's relatively easy to do.  I can give you guidance if you'd like to work on it.

As for inheritance, we have a bunch of issues on this:

https://github.com/quicktype/quicktype/issues/12
https://github.com/quicktype/quicktype/issues/257
https://github.com/quicktype/quicktype/issues/493

Inheritance is not easy to implement, but special cases of it are manageable.  I'd love to help if you're interested.

**Comment by mkrawczuk** [comment]
Yes, please guide me how to resign  from enums. I've tried adding `--no-enums` at the end of the quicktype command, but it seems not to work.
Full command:
`./script/quicktype -l pike -s schema "https://raw.githubusercontent.com/Microsoft/vscode-debugadapter-node/master/debugProtocol.json#/definitions/" -o DAP_no_enums.pike --no-enums`

**Comment by schani** [comment]
`--no-enums` is only for inference from JSON input, not for disabling enums for JSON Schema.

You can opt to not implement enums for Pike, by simply using the Pike string type for enum types.
