### ISSUE TITLE
Paste to python doesn't work ik Visual Studio Code

### ISSUE THREAD

**Issue by kobej1** [quicktype/quicktype#1139]
When I try to paste my json file as python code, the extension just passed "Generated by https://quicktype.io". It works when I'm converting the json code to another language.
![image](https://user-images.githubusercontent.com/42657049/50048327-54a47000-00c9-11e9-97a3-1d4efa26cae5.png)

**Comment by schani** [comment]
Could you share the JSON you're trying to paste?

**Comment by kobej1** [comment]
[meldingen_2016.zip](https://github.com/quicktype/quicktype/files/2683136/meldingen_2016.zip)
I could converted it in the browser but in Visual Studio Code it doesn't work.

**Comment by schani** [comment]
You'll have to turn off "Infer maps" in the settings (see [our blog](https://blog.quicktype.io/markov/) on what that does in detail):

<img width="975" alt="image" src="https://user-images.githubusercontent.com/61363/50048412-2ea6ad80-0080-11e9-8e32-c1e14bfdb80a.png">

**Comment by kobej1** [comment]
Thanks! By the way nice project, it makes my life as a programmer so much easier!

**Comment by schani** [comment]
@kobej1 Thank you, we love to hear that.  Please tell all your friends! :-)
