### ISSUE TITLE
remove banner from bottom left corner

### ISSUE THREAD

**Issue by RishabhTayal** [quicktype/quicktype#1143]
Since the banner is showing on the left corner, it's impossible to view the bottom part of the json text in the editor.

<img width="538" alt="screenshot 2018-12-24 23 26 55" src="https://user-images.githubusercontent.com/2100166/50413254-873e1f00-07d3-11e9-9765-15b7bda2dab6.png">

**Comment by dvdsgl** [comment]
The ad will disappear if you click it, or if you click the close icon (deploying now, will be live in ~10 minutes).
