### ISSUE TITLE
Java: Option to "Use T[] or List<T>" (similar to C#)

### ISSUE THREAD

**Issue by about-code** [quicktype/quicktype#1161]
For C# there's already an option `--array-type array|list` to control how JSON-Schema type `array` should be translated. Having this option also available for Java would be great.

**Comment by schani** [comment]
Please consider contributing this feature.  You'd have to modify quicktype's [Java target language](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/Java.ts).  For reference, [here](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/CSharp.ts#L114)'s how the C# target language declares the option and [here](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/CSharp.ts#L304)'s where it uses the value of the option to generate the corresponding output.

We're happy to help you if you run into any problems or have any questions.

**Comment by about-code** [comment]
Have already begun studying the sources. Seems to be straight forward. I'm contributing this.

**Comment by schani** [comment]
Fantastic! Thank you!

One request: please add the new option to the [quick-test options for Java](https://github.com/quicktype/quicktype/blob/master/test/languages.ts#L99) (see the [analogous line for C#](https://github.com/quicktype/quicktype/blob/master/test/languages.ts#L71)).  That will run a few tests in our CI with the new option, even if it's not on by default.  You can (and should) run the test suite on your machine with

    FIXTURE=java npm test
