### ISSUE TITLE
Java - missing imports when using --just-types

### ISSUE THREAD

**Issue by eqinox76** [quicktype/quicktype#1162]
Hi all,
first thanks for your work and this great tool!

I found a issue when creating code from a json schema to java with the --just-types flag.
When i add some simple rules like a enum to a string there are some imports missing without which the code is unuseable.
In this minimal [example](https://app.quicktype.io?share=WIGJOX7d9f8sSDnt3Pti) it's at least missing imports for IOException, JsonValue and JsonCreator.

Regards,
Carsten

**Comment by schani** [comment]
@eqinox76 Would you consider contributing a fix?  It should be pretty easy and we'll help you along.

**Comment by eqinox76** [comment]
The problem seems to be that
```
    protected emitEnumDefinition(e: EnumType, enumName: Name): void {
        this.emitFileHeader(enumName, this.importsForType(e));
```
is calling 
```
    protected emitPackageAndImports(imports: string[]): void {
        const allImports = ["java.util.Map"].concat(this._options.justTypes ? [] : imports);
```
I would just remove the justTypes check in ```emitPackageAndImports``` but i don't know if that is breaking something.
Alternativly i would have to somehow signal (parameter, flag) the ```emitPackageAndImports``` that it has not to check if ```emitEnumDefiniton``` is making the call. Which sounds ugly.

Any clue under which conditions ```emitPackageAndImports``` has to check the justTypes option?

**Comment by schani** [comment]
I don't think that removing the check would break anything, but it would import too many packages, in particular `jackson`.  I think the right way to fix it is to remove that check, but in `importsForType` only add the needed imports based on whether `justTypes` is set.

You can always run the test suite with

```
FIXTURE=java,schema-java npm test
```

to check whether the generated code works, at least.  (That won't check the `just-types` code, though)

**Comment by eqinox76** [comment]
Hey schani,
i attempted a [fix](https://github.com/quicktype/quicktype/commit/a4572ede54f328a9248f3aa1fadd4c001e7e5547). I'm not sure about the intention of --just-types but i think removing the jackson json annotations when it' used is the way to go.
Also i'm not sure how to integrate this into the unittests. The testing framework is quiet powerful but i saw no point where i can define java tests with --just-types and check that the output compiles. Pointers are welcome.
A manual test looks good:
```
// Latitude.java

package io.quicktype;

import java.util.*;
import java.io.IOException;

public enum Latitude {
    A, B;

    public String toValue() {
        switch (this) {
        case A: return "A";
        case B: return "B";
        }
        return null;
    }

    public static Latitude forValue(String value) throws IOException {
        if (value.equals("A")) return A;
        if (value.equals("B")) return B;
        throw new IOException("Cannot deserialize Latitude");
    }
}
```
And the testing framework for java shows no errors.

Let me know how you would like to progress,
eqinox76

**Comment by schani** [comment]
Could you please submit a PR so I can review it?

There's currently no way in our test suite to check whether `--just-types` compiles.  We'll accept the PR without that, but if you're interested in adding support for that, please let me know - I'm happy to help.

One cosmetic thing about your commit: Please use [prettier](https://prettier.io) for formatting the code.
