### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Nidhishpp** [quicktype/quicktype#1182]
- Issue Type: `Performance`
- Extension Name: `quicktype`
- Extension Version: `12.0.46`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

[quicktype.quicktype-unresponsive.cpuprofile.txt](https://github.com/quicktype/quicktype/files/2901625/quicktype.quicktype-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by dvdsgl** [comment]
The extension only does computation when you generate code, and these calls are quite fast. Can you tell us more about what happens?
