### ISSUE TITLE
D is missing 

### ISSUE THREAD

**Issue by andre2007** [quicktype/quicktype#1188]
Unfortunately D is missing.  Could you add support for the D Programming Language?

**Comment by schani** [comment]
Would you consider contributing D support to quicktype?  We'd love to help.

**Comment by andre2007** [comment]
Except my mobile phone I will have hardly access to a computer in upcoming weeks.

I can point you to the the right resources:
http://ddili.org/ders/d.en/index.html

Also there is a quite good video tutorial 
https://www.youtube.com/watch?v=rwZFTnf9bDU

You could also  announce quicktype 
On forum.dlang.org. maybe someone also already has some experience with TS.

**Comment by schani** [comment]
What about the weeks after the upcoming weeks?

**Comment by andre2007** [comment]
I will re-check this topic when I have time again.

In general I avoid writing code in script languages. My personal experience is, for a quite high time investment, the outcome is very low. And even if the outcome is high, the quality of the outcome is low. The best mix of time investment, outcome and quality I found in the D programming Language  .

**Comment by dvdsgl** [comment]
Closing this per our policy of not leaving language requests open as issues.
