### ISSUE TITLE
Refactor Typescript generation to not use Namespaces

### ISSUE THREAD

**Issue by wgottschalk** [quicktype/quicktype#1189]
Babel 7 parses typescript and can confirm that they refuse to implement namespaces due to the fact that they are legacy. https://github.com/babel/babel/issues/8244

When parsing from JSON schema to typescript the `Convert` function is wrapped in a namespace.

Solution:

Refactor the Convert function to be a const instead of a namespace. Do not export any of the helpers still.

before:
```ts
export namespace Convert {
  export function toThing(data: string): Thing {...}
  export function thingToJSON(data: Thing): string {...}
}
```

after:

```ts
export const Convert = {
  toThing() {...}
  thingToJSON() {...}
}

// rest of the helpers go here and are not exported
```

**Comment by schani** [comment]
Would you consider contributing a PR that does this?  We'd love to help you along.  The code that emits TypeScript is [here](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/JavaScript.ts) and [here](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/TypeScriptFlow.ts).

**Comment by wgottschalk** [comment]
Sounds good to me. I'll talk a look at this
