### ISSUE TITLE
C# serializes enums to integers rather than strings

### ISSUE THREAD

**Issue by cartwrightluke** [quicktype/quicktype#1197]
Generated code in c# serializes enums to numbers rather than strings.
This should be easy to fix, and just needs the data types to be tagged. See: https://stackoverflow.com/questions/2441290/net-json-serialization-of-enum-as-string

**Comment by schani** [comment]
Could you provide a reproducible test case, please?

**Comment by cartwrightluke** [comment]
I misunderstood what was happening. Looks like we were using the built in serializer rather than the generated one.
