### ISSUE TITLE
Adapt Rust output for compatibility with Rust 2018 edition

### ISSUE THREAD

**Issue by yonkeltron** [quicktype/quicktype#1210]
Hello,

Back at the end of last year, [Rust 2018 was announced](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html). It brought several changes which make the current Rust output of the `quicktype` command incompatible with the 2018 edition. Specifically, the new macro and module system changes [described in the edition guide](https://doc.rust-lang.org/edition-guide/rust-2018/index.html) mean that using Serde to implement the compiler-derived traits of `Serialize` and `Deserialize` requires a different `use` directive than was previously required. The change is described in detail [here](https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html).

The old way:

```rust
#[macro_use]
extern crate serde_derive;
```

The new way:

```
use serde::{Serialize, Deserialize};
```

As a result of this improvement, we need to post-process all Rust code generated by the `quicktype` command in order to replace the old line with this new line.

While I advocate fixing this problem and making the new output the default behavior, as the adoption of Rust 2018 is still underway, I suggest adding a CLI flag which can revert to the legacy behavior for use with Rust versions prior to 1.31.

Some information about my environment (where Quicktype was installed via `npm`):

```bash
$ quicktype --version
quicktype version 15.0.182
Visit quicktype.io for more info.

$ uname -a
Darwin <HOSTNAME> 16.7.0 Darwin Kernel Version 16.7.0: Wed Feb 27 00:29:57 PST 2019; root:xnu-3789.73.43~1/RELEASE_X86_64 x86_64

$ node --version
v11.14.0

$ npm --version
6.9.0
```

Please let me know if I can provide any additional information to aid in the resolution of this problem. I love Quicktype and hope to see its wider adoption in the Rust world.

Thanks,
+Jonathan

**Comment by ajventurini** [comment]
Would love to see this updated with the legacy version option.

**Comment by briansmith-agilebits** [comment]
I noticed that the generated code doesn't even depend on `serde_json` as far as I can tell; it only depends on `serde_derive`, at least in my case. I had to add `serde_json` dependencies into my crates' Cargo.toml just to cope with the `extern crate serde_json;`. If I remove `extern crate serde_json;` then my crates compile just fine. (I'm using the 2018 Edition.)
