### ISSUE TITLE
python 3.7: Optional w/o default, description placement

### ISSUE THREAD

**Issue by einsweniger** [quicktype/quicktype#1216]
Hi!

I've got an API that can describe itself with something that looks like JSON Schema. I write "looks like", because I'm not sure if it does conform with everything.
(A quick romp through the schema spec does not state if a non-required field must provide a default.)

In my case, the result is a generated python dataclass with something like this (v15.0.174):

```python
@dataclass
class BackupCollection:
    """Backup Solr indexes and configurations for a specific collection. One copy of the indexes
    will be taken from each shard, and the config set for the collection will also be copied.
    """
    """Defines a request ID that can be used to track this action after it's submitted. The
    action will be processed asynchronously.
    """
    backup_collection_async: Optional[str]
    """The name of the collection to back up."""
    collection: str
    """A location on a shared drive for the backup-collection command to write to. Alternately,
    it can be set as a cluster property with the cluster endpoint, which also supports
    setting a location.
    """
    location: str
    """The name of the backup."""
    name: str
```

I have to gripe about some of that:

1. Note the missing default on `backup_collection_async`. 
The spec did not include a default, so there is none in the dataclass.
In this case, it's fine as it's just one parameter, but I have more complex classes that take 1 required and 15 optional parameters.
w/o a default value, this get's very tedious to use, when you don't want to use the `from_dict`.

Proposed solution: for fields that have no default specified in the schema, we use `[name]: Optional[T] = None`.

2. the docstrings are placed above the fields.
This is quite unusual in python. At least for me, since I'm usually expecting docstrings below the declaration.

Proposed solution: we put field descriptions in the top level docstring, i.e.

```python
@dataclass
class CreateAlias:
    """
    Create an Alias

    :param create_alias_async: Defines a request ID that can be used to track this action after it's submitted. The action will be processed asynchronously.
    :param collections: The list of collections to be known as this alias. Incompatible with any of the routing parameters. Either this parameter or a complete set of routing parameters is required.
    :param create_collection: The settings to use to create a collection for each new time partition. Most options from the collection create command are available, except for 'name', 'async' and 'waitForFinalState'.
    :param name: The alias name to be created.
    :param router: Routing specific properties to define a time routed alias.  Do not specify 'collections' when creating a time routed alias.
    :param tz: Optional timezone for use with any date math that may exist in other parameters. Defaults to UTC.
    """
    create_alias_async: Optional[str]
    collections: Optional[List[str]]
    create_collection: Optional[Dict[str, Any]]
    name: str
    router: Optional[CreateAliasRouter]
    tz: Optional[str]
```

That way, `help(CreateAlias)` can provide more insight when interacting on the REPL.

Comments and other opinions welcome :3

**Comment by remorses** [comment]
To add default values the properties should also be sorted to make the default ones last (a python restriction)
It would also be cool to include the json schema `default` keyword
