### ISSUE TITLE
Support JSDoc

### ISSUE THREAD

**Issue by barakplasma** [quicktype/quicktype#1226]
Would quicktype like to support JSDoc output?

JSDoc is supported in Visual Studio Code on vanilla Javascript to improve the intellisense via TSC. (see https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript for more details)
For details on JSDoc itself, see https://jsdoc.app/

I find myself converting the Typescript interfaces to JSDoc interfaces by hand, and I am interested in contributing a quicktype to JSDoc converter. Would quicktype accept a PR?

**Comment by dvdsgl** [comment]
Yes we would likely accept this if done well and made optional.

**Comment by barakplasma** [comment]
I'll close this as not planned, since there are now alternative tools which convert JSON to JSDoc

1. https://github.com/n3ps/json-schema-to-jsdoc
2. https://transform.tools/json-to-jsdoc / https://transform.tools/json-to-jsdoc
