### ISSUE TITLE
Dart changes

### ISSUE THREAD

**Issue by KlausJokisuo** [quicktype/quicktype#1227]
1. Remove new keyword because its not needed anymore.
2. Use ' instead of "

This tool is great and I use it daily, keep up the good work.

**Comment by nuc134r** [comment]
This issue involves Dart's codestyle so I decided to add to it insted of creating a new one.

The following JSON

```json
{
    "server_time": 1558463454,
    "request_time": 0.236
}
```

is being parsed into following code:
```dart
class UmaResponse {
    int serverTime;
    double requestTime;

    UmaResponse({
        this.serverTime,
        this.requestTime,
    });
}
```

Notice how "_"-delimited properties turn into camelCase ones. It breaks JSON parsing and they are returned as `Null` in runtime. I suggest adding an option to preserve naming in output code.

OPs remarks also make sense as they follow Google's suggested codestyle. But they don't break things.

**Comment by dvdsgl** [comment]
@nuc134r the default behavior of quicktype ensures that those values are translated correctly—only if you output 'types only' do you lose the information needed to parse the JSON. Please don't use that option.

Many other languages have a style option that would change this, so please consider adding one. As far as I know this is the official naming style for Dart.

**Comment by nuc134r** [comment]
Yeah, I was using Dart's suggested code generation (via official package) to parse JSON and ignored the one that quicktype offers by using 'types only' option. My mistake, thanks for figuring that out for me.
