### ISSUE TITLE
With TypeScript >= 3.4.x quicktype generates an empty schema

### ISSUE THREAD

**Issue by michitaro** [quicktype/quicktype#1256]
With TypeScript >= 3.4, quicktype always generates an emtpry schema (whatever the input typescript files are).

The command below
```sh
quicktype --lang schema interface.ts
```
generates an output like this.
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {}
}
```

Here is a repository to reproduce the problem.
https://github.com/michitaro/quicktype-issue

Could you look into it?

**Comment by abraxaslee** [comment]
https://github.com/quicktype/quicktype/issues/1240
I think this is a related issue. because quicktype is using the typescript version in package.json, not it's own one.

**Comment by kristiyanP** [comment]
Temporary solution is to edit the package-lock.json

add typescript 3.3.3 dependecy to quicktype

Example:
```js
"quicktype": {
      "version": "15.0.197",
      \\ ...
      "requires": {
            \\ ...
      },
      "dependencies": {
           "typescript": {
                 "version": "3.3.3"
             }
           \\ ...
      }
}
```

Remove the node modules
```rm -rf ./node_modules```

Re-install all with the new dependency
```npm i```

Double check package-lock.json that now should have some additional keys for the typescript dependecy under quicktype.

And now you should be able to generate the files.
