### ISSUE TITLE
JSON to Dart doesn't pick up Map unless there's over 8 items

### ISSUE THREAD

**Issue by stiggy87** [quicktype/quicktype#1258]
I have elements in JSON that need to be Maps in Dart. One has over 12 elements, another only has 4.  As a test I used the following JSON to confirm my thought that there's a minimum requirement.

When I use the following JSON:
{
   "Map1": {
       "item1": 0,
       "item2": 0,
       "item3": 0,
       "item4": 0,
       "item5": 0,
       "item6": 0,
       "item7": 0,
       "item8": 0,
       "item9": 0,
       "item10": 0,
       "item11": 0,
       "item12": 0,
       "item13": 0
       },
    "map2": {
       "item1": 0,
       "item2": 0,
       "item3": 0,
       "item4": 0,
       "item5": 0,
       "item6": 0,
       "item7": 0,
       "item8": 0
    }
}

If you remove item8 from map2, you'll see it turn into a class and not keep the Map. I can understand if there's only 1 item, but anything after that should be targeting a Map.

**Comment by dvdsgl** [comment]
Try this one:

```json
{
    "small map": {
        "B6D2D2B4-4580-49F2-913A-0EF0C6C43B33": 0,
        "7E7E5C94-9DBB-48D6-AAA7-783D1922FD18": 0
    }
}
```

It's not size-based — it's based on what the keys look like.

**Comment by stiggy87** [comment]
If my keys are all different strings, (as shown in the original post), when one of my maps is only 4 elements in length, it doesn't create a map.

I don't agree with this being closed for a reason of what you gave. It needs to be looked at and a more definitive answer needs to be provided instead of an example that does not fit my use case.

**Comment by dvdsgl** [comment]
You titled your issue “JSON to Dart doesn't pick up Map unless there's over 8 items” and this is false. What, exactly, is the data you want to infer as a map? Can you try replacing one or two of the values in your JSON object with a GUID? Then it should detect as a map. Here is a detailed post about how the inference works: http://blog.quicktype.io/markov/
