### ISSUE TITLE
const not generated as a single-value enum

### ISSUE THREAD

**Issue by rikoe** [quicktype/quicktype#1277]
According to https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values, the `const` type has the same semantics as a single-value enum.

However, quicktype currently generates const values as either a string or an object (I have seen both depending on quicktype version), with no reference at all to the constant value specified in the schema.

I would expect it to exhibit the same behaviour during code-generation as for single-value enums (which is to say a generated enum type with a single value matching the constant string).

Example: https://app.quicktype.io?share=rogbg8vSs4VHh1E9Zuq5

**Comment by magiepooh** [comment]
I want this feature too 👍

**Comment by joelhoisko** [comment]
I tested this one out again, and there still isn't support for the `const` keyword, it doesn't get parsed into an single enum. Would really love to see this feature happen 👍

Also linked to https://github.com/quicktype/quicktype/issues/1225

**Comment by zhenyakovalyov** [comment]
echoing @rikoe's request to introduce correct const value generation

**Comment by kriswest** [comment]
Working on the same project @rikoe was when raising this issue 4 years ago and we still need this (an use cases have multiplied). Very happy to see [the PR](https://github.com/quicktype/quicktype/pull/2314) @DanielBretzigheimer raised 4 days ago to resolve! Will try and find time to test it out soon.

**Comment by DanielBretzigheimer** [comment]
@dvdsgl: I think this ticket may be closed?
