### ISSUE TITLE
The json-schema to ts cannot seperate Enum type

### ISSUE THREAD

**Issue by wenyuyangpku** [quicktype/quicktype#1284]
I tried to generate typescript from json schema. However, all enum attributes are combined. Here is my input: [The link of the example in QuickType](https://app.quicktype.io?share=mSby87Y3k9npwXjcBeZm)

```
{
  "$ref": "#/definitions/AnyMark",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "AnyMark": {
      "anyOf": [
        {
          "$ref": "#/definitions/Mark"
        },
        {
          "$ref": "#/definitions/CompositeMark"
        }
      ]
    },
    "Mark": {
      "enum": ["area", "bar"],
      "type": "string"
    },
    "CompositeMark": {
      "enum": ["boxplot", "errorbar"],
      "type": "string"
    }
  }
}

```

My ideal output is:

```
export type AnyMark = Mark | Boxplot;

export enum Mark {
  Area = 'area',
  Bar = 'bar'
}
export enum Boxplot {
  Boxplot = 'boxplot',
  Errorbar = 'errorbar'
}

```

But the final output is:
```
export enum AnyMark {
    Area = "area",
    Bar = "bar",
    Boxplot = "boxplot",
    Errorbar = "errorbar",
}
```
Is there any way to seperate all enum class?

**Comment by oxc** [comment]
Did you find a solution for this?

**Comment by freemansoft** [comment]
A lot of languages can't create an Enum as a _union_ of Enums.  Enums are a fixed set. They don't have any meaning in a different enum.  QuickType _will_ create separate enum classes if you use the separately.  Using Mark in one place and AnyMark in another would give you two enums.  One for Mark and one with all of the values.  

You can see this using this schema as an example.
```json
```
{
  "$id": "http://foo/root.json",
  "$ref": "#/definitions/foo",
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
       
        "theComposite": {
          "$ref": "#/definitions/CompositeMark"
        },
         "theAny": {
          "$ref": "#/definitions/AnyMark"
        }
      },
      "required": [
      ]
    },
   
    "AnyMark": {
      "anyOf": [
        {
          "$ref": "#/definitions/Mark"
        },
        {
          "$ref": "#/definitions/CompositeMark"
        }
      ]
    },
    "Mark": {
      "enum": [
        "area",
        "bar"
      ],
      "type": "string"
    },
    "CompositeMark": {
      "enum": [
        "boxplot",
        "errorbar"
      ],
      "type": "string"
    }
  }
} 
```

It generates the following _Dart_ code
```dart
```
import 'dart:convert';

class Foo {
    final AnyMark? theAny;
    final CompositeMark? theComposite;

    Foo({
        this.theAny,
        this.theComposite,
    });

    Foo copyWith({
        AnyMark? theAny,
        CompositeMark? theComposite,
    }) => 
        Foo(
            theAny: theAny ?? this.theAny,
            theComposite: theComposite ?? this.theComposite,
        );

    factory Foo.fromRawJson(String str) => Foo.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory Foo.fromJson(Map<String, dynamic> json) => Foo(
        theAny: anyMarkValues.map[json["theAny"]]!,
        theComposite: compositeMarkValues.map[json["theComposite"]]!,
    );

    Map<String, dynamic> toJson() => {
        "theAny": anyMarkValues.reverse[theAny],
        "theComposite": compositeMarkValues.reverse[theComposite],
    };
}

enum AnyMark {
    AREA,
    BAR,
    BOXPLOT,
    ERRORBAR
}

final anyMarkValues = EnumValues({
    "area": AnyMark.AREA,
    "bar": AnyMark.BAR,
    "boxplot": AnyMark.BOXPLOT,
    "errorbar": AnyMark.ERRORBAR
});

enum CompositeMark {
    BOXPLOT,
    ERRORBAR
}

final compositeMarkValues = EnumValues({
    "boxplot": CompositeMark.BOXPLOT,
    "errorbar": CompositeMark.ERRORBAR
});

class EnumValues<T> {
    Map<String, T> map;
    late Map<T, String> reverseMap;

    EnumValues(this.map);

    Map<T, String> get reverse {
        reverseMap = map.map((k, v) => MapEntry(v, k));
        return reverseMap;
    }
} 
```
```
