### ISSUE TITLE
Alamofire Extensions (5, Swift 5)

### ISSUE THREAD

**Issue by n1schal** [quicktype/quicktype#1313]
The generated Alamofire Response Handlers don't seem to work with the new versions of Swift, Alamofire 5.

<img width="1111" alt="Screen Shot 2019-09-22 at 3 43 42 PM" src="https://user-images.githubusercontent.com/15378179/65385571-19b62380-dd50-11e9-9003-bcb994130193.png">

**Comment by infinigent-solutions** [comment]
@dvdsgl Will there be any update on this?

**Comment by n1schal** [comment]
Hey, I have a workaround, will let you know when I'm on my PC, so far it's been working fine for me.

**Comment by infinigent-solutions** [comment]
@n1schal Can you please share it now, as I need to resolve in urgently?

**Comment by n1schal** [comment]
This will work with:

pod 'Alamofire', '~> 5.0.0-rc.3'

Create an extension for Alamofire and add these two methods:

```
func newJSONDecoder() -> JSONDecoder {
    let decoder = JSONDecoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        decoder.dateDecodingStrategy = .iso8601
    }
    return decoder
}

func newJSONEncoder() -> JSONEncoder {
    let encoder = JSONEncoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        encoder.dateEncodingStrategy = .iso8601
    }
    return encoder
}
```
Make API calls as such:

```
func makeNetworkCall(completion: @escaping(SomeData?, SomeError?) -> Void){
        let requestUrl = APIUrl.networkCall
        AF.request(requestUrl,
                   method: .get,
                   encoding: JSONEncoding.default)..responseDecodable(of: SomeData.self){
                    response in
if let someDataResponse = response.value{
                    completion(someDataResponse, nil)
return;
                }else if let someError = error{
completion(nil, someError)
}
                    
        }
    }
```

**Comment by infinigent-solutions** [comment]
@n1schal  **SomeData** is a model object?

**Comment by n1schal** [comment]
@infinigent-solutions Yup. SomeData is the object you expect in response to the network call. HTH!

**Comment by infinigent-solutions** [comment]
@n1schal It worked
