### ISSUE TITLE
Ruby to_dynamic/to_json is not working

### ISSUE THREAD

**Issue by jakejcheng** [quicktype/quicktype#1319]
to_dynamic does not include loaded values from from_json! or from_dynamic!. Using the default "Welcome" script in the Quicktype editor as an example, doing this:
```
welcome = Welcome.from_json! "{…}"
puts welcome.instructions.first 
```
will output "Type or paste JSON here" which is expected.
However, doing this:
`puts welcome.to_json` or `puts welcome.to_dynamic`
will give
`{"greeting"=>nil, "instructions"=>nil}` and `{"greeting":null,"instructions":null}`

Am I using it the right way or is it broken?

**Comment by jakejcheng** [comment]
I figured it out. The original implementation is:
`
    def to_dynamic
        {
            "greeting"     => @greeting,
            "instructions" => @instructions,
        }
    end
` 
and it won't work. 
However, if it's changed to: (by changing from instance variable to implicit self.method)
`
    def to_dynamic
        {
            "greeting"     => greeting,
            "instructions" => instructions,
        }
    end
`
it works!

**Comment by dvdsgl** [comment]
Strange, our test suite would have found this.
