### ISSUE TITLE
Add support for System.Text.Json from dotnetcore 3.0

### ISSUE THREAD

**Issue by latop2604** [quicktype/quicktype#1323]
With dotnet core 3 we now have a new, hight perf, official, .Net Json serializer. It would be great to have it in QuickType

https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/

https://docs.microsoft.com/fr-fr/dotnet/api/system.text.json

**Comment by doggy8088** [comment]
dup https://github.com/quicktype/quicktype/issues/1347

**Comment by dvdsgl** [comment]
Duplicate
