### ISSUE TITLE
Class constructor TargetLanguage cannot be invoked without 'new'

### ISSUE THREAD

**Issue by loganvolkers** [quicktype/quicktype#1326]
I keep running into this problem while trying to use `quicktype-core`.

```js
import {
  quicktype,
  InputData,
  jsonInputForTargetLanguage,
  languageNamed
} from "quicktype-core";

async function parse() {
  const target = "JSON Schema";
  const input = jsonInputForTargetLanguage(languageNamed(target));
  await input.addSource({
    name: "Schema1",
    samples: [`{ foo: "true" }`]
  });
}
```

It produces this error.

```
Class constructor TargetLanguage cannot be invoked without 'new'
new CrystalTargetLanguage
https://x88j6.csb.app/node_modules/quicktype-core/dist/language/Crystal.js:48:118
evaluate
https://x88j6.csb.app/node_modules/quicktype-core/dist/language/All.js:25:5
$n
https://codesandbox.io/static/js/sandbox.6fbf829d.js:1:148704
e.value
https://codesandbox.io/static/js/sandbox.6fbf829d.js:1:163968
```

Here's an example: https://codesandbox.io/s/quicktype-class-error-x88j6

**Comment by JoseHdez2** [comment]
I'm also having the same error (and I'm also using CodeSandbox). 

`Class constructor TargetLanguage cannot be invoked without 'new'`

It points to the line of the import, in my case

`import { quicktype, InputData, JSONSchemaInput, KotlinTargetLanguage } from "quicktype-core";`

Any progress or solution?

**Comment by dvdsgl** [comment]
I've added an example for how to call `quicktype` programmatically: https://runkit.com/dvdsgl/5dffa01dedf1a1001cf899c3

**Comment by dvdsgl** [comment]
I've added a JSON example to the README https://github.com/quicktype/quicktype#calling-quicktype-from-javascript
