### ISSUE TITLE
C++ Compile Time Error with Googletest

### ISSUE THREAD

**Issue by Alph0r** [quicktype/quicktype#1333]
When trying to build a test project with Googletest in VS 2017 I receive several compile time errors:

binary '=': no operator found which takes a right-hand operand of type 'const std::vector<testing::internal::string,std::allocator<_Ty>>' (or there is no acceptable conversion)

nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::get': no matching overloaded function found

This error seems to be related to ADL. Moving the block with the from_json/to_json functions from namespace nlohmann to namespace quicktype fixes the error.

**Comment by zoink47** [comment]
I have the same problem with Microsoft Visual Studio 2019 16.3.7.
