### ISSUE TITLE
"Just Types" for C# omits namespace

### ISSUE THREAD

**Issue by atrauzzi** [quicktype/quicktype#1353]
I'm looking to generate plain C# types from TypeScript with no dependencies on any external libraries. Unfortunately, when I generate using "just types", I end up losing the namespace (as well as the json.net dependencies).

Is there any way I can have namespaces without json.net?

**Comment by thegoldenmule** [comment]
I made a PR here: https://github.com/quicktype/quicktype/pull/1436

**Comment by thegoldenmule** [comment]
@atrauzzi After some discussion, it was deemed that `just-types` serves some specific purposes that we can't break backward compat for. Instead, I started a new PR with a new option for the C# renderer: `just-types-and-namespace`. See https://github.com/quicktype/quicktype/pull/1461.

**Comment by atrauzzi** [comment]
Slick!

**Comment by thegoldenmule** [comment]
@atrauzzi FYI this has been merged into master.

**Comment by thegoldenmule** [comment]
This has been resolved.
