### ISSUE TITLE
Coverts float to int when using JSON to generate Python

### ISSUE THREAD

**Issue by radioflyer28** [quicktype/quicktype#1358]
Instead of using the `float` from the key in the JSON file it generates methods in the Python code that treat it as an `int`. It seems to only do this when numbers end with `.0`. Changing any key's value in the input JSON from `.0` to `.01` will result in it being treated as a `float` in the generated Python functions.

For value ending in `.0`, treats as `int`:
JSON = `"dataSamplingRate": 1250000.0` to Python dict= `"dataSamplingRate": 1250000`

For value ending in `.01`, treats as `float`:
JSON = `"dataSamplingRate": 1250000.01` to Python dict= `"dataSamplingRate": 1250000.01`

**Comment by dvdsgl** [comment]
Same as #1345
