### ISSUE TITLE
Allow int or float in Python dataclasses

### ISSUE THREAD

**Issue by danvk** [quicktype/quicktype#1375]
Use this TypeScript as input and convert to Python 3.7 (with dataclasses):

```ts
export interface Config {
    fooBar: number;
}
```

Result:

```python
# ...

@dataclass
class Config:
    fooBar: float

    # ...

    def to_dict(self) -> dict:
        result: dict = {}
        result["fooBar"] = to_float(self.fooBar)
        return result

# ...
```

When I try to create a `Config` instance in Python and serialize it, however, I get an error:

```
In[2]: Config(fooBar=10).to_dict()
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-a3f5b1bbb6e2> in <module>
----> 1 Config(fooBar=10).to_dict()

<ipython-input-1-2171edd126f5> in to_dict(self)
     41     def to_dict(self) -> dict:
     42         result: dict = {}
---> 43         result["fooBar"] = to_float(self.fooBar)
     44         return result
     45

<ipython-input-1-2171edd126f5> in to_float(x)
     20
     21 def to_float(x: Any) -> float:
---> 22     assert isinstance(x, float)
     23     return x
     24

AssertionError:
```

(full example [here][1])

The issue is that the `Config` dataclass requires that its property be a `float`. But there's no reason an `int` shouldn't be allowed, too. `number` in TypeScript covers both.

[1]: https://app.quicktype.io?share=FM0CsCDEfE240UWcQoGg

**Comment by dvdsgl** [comment]
This is already supported, but requires a special annotation, as TypeScript does not have an integer primitive: https://app.quicktype.io?share=uD3uJjXOJohbkwOLaE4A

**Comment by danvk** [comment]
@dvdsgl the request here isn't to only allow ints. It's to allow either float or int. I can't think of any APIs in Python that accept floats but not ints, so this really breaks expectations about how Python code should operate.

**Comment by alyiwang** [comment]
Hi @dvdsgl The link you shared above: https://app.quicktype.io?share=uD3uJjXOJohbkwOLaE4A doesn't contain much info. Could you share the fix or annotation we should use? Thanks!

**Comment by DOsinga** [comment]
I wonder though in general about these asserts. It goes somewhat against the Python duck typing notion. Something taking a float should in general accept an int, but the same is true for lists and dicts - if I create my own class that behaves like a list, I would expect the generated code to accept it, not to reject it because it doesn't derive from the python list.

**Comment by jkillian** [comment]
I believe this is fixed in https://github.com/glideapps/quicktype/pull/2549
