### ISSUE TITLE
Ruby integration only works with outdated dry-rb gems

### ISSUE THREAD

**Issue by Morozzzko** [quicktype/quicktype#1379]
It's been a while since the integration was introduced, so the gems we use to list types are outdated

We need to update the integration and make sure it produces correct output for the latest gem versions. 

Would be cool if it works with `dry-types >= 1.0` and `dry-struct >= 1.0`

Semi-related issue: #1125
Source code: https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/ruby/index.ts

**Comment by Morozzzko** [comment]
As a side-note, the integration should probably give us a choice. Some people haven't upgraded their gems to 1.x, so they still need support for latest 0.X gems

Would be nice if someone could implement that too

**Comment by dvdsgl** [comment]
Hello! I wrote the Ruby backend but I haven't used Ruby in over eight years. Would you consider contributing?

**Comment by Morozzzko** [comment]
I'm afraid I might not get the chance to do it within the next few month, but I hope someone from Ruby community could pick this up

Seems like a decent task for beginners and enthusiasts, so I hope someone would be interested.

I'm sharing the link to the issue, and I'd be thankful if someone decided to take a shot at it
