### ISSUE TITLE
Issue when quicktyping from TypeScript to JSON Schema

### ISSUE THREAD

**Issue by Roms1383** [quicktype/quicktype#1381]
First and foremost this project looks great ! 👍 
I gave it a try today and ran into some issue, which I describe below.

### context

`package.json`
*  "quicktype": "^15.0.210",
*  "typescript": "^3.7.5"

`yarn`
1.21.1

`host`
macOs Catalina 10.15.2

### description

I already have a bunch of TypeScript interfaces from which I would like to generate JSON Schema definitions.

### how to reproduce

Given a file :

```ts
// located at ./src/definitions/country.ts
export interface Country {
  code : string
  name : string
}
```

Running the command :

```shell
yarn quicktype -s ts src/definitions/country.ts -l schema -o src/contracts/country.json
```
or
```shell
yarn quicktype -s typescript src/definitions/country.ts -l schema -o src/contracts/country.json
```

### output result
```json
// located at ./src/contracts/country.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {}
}
```

### expected result

I would have expected something similar to :
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Country": {
            "title": "Country",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "title": "code"
                },
                "name": {
                    "type": "string",
                    "title": "name"
                }
            },
            "required": [
                "code",
                "name"
            ]
        }
    }
}
```

### notes

I tried multiple different combinations including creating a TS class instead of interface, even both, but I get the same output everytime.

---
Where did I made a mistake ?
Thanks in advance

**Comment by fgarcia** [comment]
I've just been having problems to achieve this. The README is confusing because the section about converting from Typescript to Schema does not really show an example achieving that. 

I only managed to confirm quicktype can convert from Typescript to Schema using online tool, but not the command line. 

Currently I do this task with `typescript-json-schema` but it would be great solving this with quicktype too

**Comment by yuku** [comment]
FYI: It seems that quicktype 13.0.14 + typescript 3.7.4 work as expected.

**Comment by Roms1383** [comment]
thanks for your feedback dudes,
if anybody has a working sample it would be very much appreciated :+1:

**Comment by Roms1383** [comment]
> FYI: It seems that quicktype 13.0.14 (w/ typescript 3.7.4) can generate jsonschema.

Would this be a regression then?

**Comment by aelesia** [comment]
Same problem. I can generate from Typescript using 13.0.14 but not with the latest version 15.0.212

**Comment by ciffelia** [comment]
Quick workaround: `yarn add -D typescript@3.3.4000` or `npm -D typescript@3.3.4000`
