### ISSUE TITLE
UUIDs not detected despite option being turned on.

### ISSUE THREAD

**Issue by haikusw** [quicktype/quicktype#1383]
Input JSON:

[
    { "id":"BF427F49-B0DB-480A-84DA-CF4E18D0CA12",
        "artist": "18AE8F61-E30B-43C6-B8E4-6B148B72C21E",
        "name":"Demons & Wizards",
        "tracks":["27AD570F-4E80-4B60-8B92-D7E89123E940",
        "2B16F5C4-8942-48A4-97C7-D0664B6DE558"]
    },
{ "id":"A68FEC70-6C8F-41FD-B76F-09EC2F2F4630",
    "artist": "FDC5E3DF-A736-4F48-8557-415A9FF82A28",
    "name":"The Cars",
    "tracks":["42417E77-51E2-4DD1-B376-078C9A37A7C2",
    "4507B404-D695-48C5-8548-05AF1DA45653",
    "E95006FF-4E89-4D9D-8170-7F4A75BC03E7"]
}
]

->
Output Swift (5):

import Foundation

// MARK: - Album
struct Album: Codable {
    let id: String      // <---- would ideally be UUID
    let artist: String      // <---- would ideally be UUID
    let name: String
    let tracks: [String]      // <---- would ideally be [UUID]

    enum CodingKeys: String, CodingKey {
        case id = "id"
        case artist = "artist"
        case name = "name"
        case tracks = "tracks"
    }
}

typealias Albums = [Album]

**Comment by haikusw** [comment]
These UUIDs are being generated via 

In Terminal, macOS 10.15.2

joe ~ % swift repl
Welcome to Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).
Type :help for assistance.
  1> import Foundation
  2> print( UUID() )
CA75E77E-9DB9-4A8C-A8EC-70E7CF0B696D
  3>

**Comment by haikusw** [comment]
Looks like it's maybe just missing from https://github.com/quicktype/quicktype/blob/7f6a3d315d368d4e7501fc38ff8a0d730095fa55/src/quicktype-core/language/Swift.ts 

???

(@vibrazy did the detective work to find and suggest this)

**Comment by dvdsgl** [comment]
Swift does not have UUID support yet.

**Comment by haikusw** [comment]
Any reason not to leave this open and change it to a feature request?

**Comment by dvdsgl** [comment]
We accept PRs, but not feature requests.
