### ISSUE TITLE
docker container fails to build on macOS 10.15.2

### ISSUE THREAD

**Issue by haikusw** [quicktype/quicktype#1384]
Thought I'd try looking into the bug I reported with UUIDs and Swift, but the Docker container fails to build.  Failed at step 37:

> Step 37/54 : RUN apt-get -y update
>  ---> Running in f133c0b6fc92
> Hit:1 https://deb.nodesource.com/node_8.x xenial InRelease
> Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
> Hit:3 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease
> Hit:4 http://ppa.launchpad.net/jonathonf/gcc-7.1/ubuntu xenial InRelease
> Hit:5 http://archive.ubuntu.com/ubuntu xenial InRelease
> Hit:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
> Ign:7 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial InRelease
> Hit:8 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
> Ign:9 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release
> Ign:10 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages
> Ign:11 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages
> Ign:11 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages
> Ign:11 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages
> Ign:11 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages
> Ign:11 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main all Packages
**> Err:10 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages
>   403  Forbidden
> Ign:11 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main all Packages
> Reading package lists...
> W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
> E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> The command '/bin/sh -c apt-get -y update' returned a non-zero code: 100**

Thought I'd let y'all know…

**Comment by lnxbil** [comment]
Yes, the author (`jonathonf`) has restricted access to those old `python-3.6` packages in December 2019. More information can be found [here](https://launchpad.net/~jonathonf).

I recommend moving to a newer codebase (e.g. `bionic beaver` instead of `xenial xerus`).

**Comment by haikusw** [comment]
@lnxbil Any interest in putting together a PR to make that improvement to the quicktype docker image? Not something I'm familiar enough with to do.   

I guess we should see if the maintainers of quicktype are open to such a PR first…

**Comment by lnxbil** [comment]
> @lnxbil Any interest in putting together a PR to make that improvement to the quicktype docker image? Not something I'm familiar enough with to do.

No, I'm not a NodeJs or TypeScript developer and I have no idea how to fix problems that could arise there.

The question remains: Why did you want to build the Docker container in the first place? It's for development and CI.

I can however provide you with instructions to run `quicktype` in a Docker container if you want. That I needed yesterday and the official Docker image (the `Dockerfile` and the currently built one) is for development and CI, not for actually running it. Therefore I packaged it with Docker so that you can just run it everywhere. This is often exactly what I want, because it encapsulates everything you need in a nice package that can literally run everywhere (Docker required).

A "running instance" (the program itself to work with) is very straight forward to set up:

```Dockerfile
FROM node:10
RUN npm install -g quicktype
ENTRYPOINT [ "/usr/local/bin/quicktype" ]
```

The resulting image is also only 985 MB in size and not a 5.37 GB monster as the CI build. Running it is also very easy, just create a shell alias like this:

```
alias quicktype='docker run -it --rm --volume $PWD:/workdir --workdir /workdir --user $(id -u) <your-docker-image-name-here>'
```

and enjoy quicktyping :-D

**Comment by haikusw** [comment]
@inxbil I wanted to run their development docker container to see if I could fix a bug/limitation with quicktype that I ran into - Issue #1383.

**Comment by lnxbil** [comment]
> @inxbil I wanted to run their development docker container to see if I could fix a bug/limitation with quicktype that I ran into - Issue #1383.

Okay, the use case the image was meant for. Sorry, I cannot help you there.

**Comment by dvdsgl** [comment]
We switched the python PPA, so all works now.

**Comment by haikusw** [comment]
The container builds now, thanks!  Following the directions at the bottom of https://github.com/quicktype/quicktype the first step succeeds but the second step ( `npm run test` ) fails #1490
