### ISSUE TITLE
I want to load js in browser to convert JSON to RUST without AJAX. Need local browser converter.

### ISSUE THREAD

**Issue by cbmgit** [quicktype/quicktype#1386]
This is an awesome library, and I am using https://app.quicktype.io a lot for JSON to Typescript. but now for my intranet app in an organization, I need to implement JSON to RUST and for deployment, I have an Nginx and it supports only static serving. 

I need help to implement JSON to RUST which does the local processing in the browser? is it possible? if yes how?

**Comment by dvdsgl** [comment]
Yes, app.quicktype.io already does this so it is possible (it does not use AJAX). We describe how to do this in our README.

**Comment by cbmgit** [comment]
is it possible to create a sample index.html which uses quicktype.js or steps to use it without any nodejs or any framework such as react or angular. Readme file doesn't provide accurate answer, how to use a quicktype as js lib, like we use jquery.

**Comment by SaadBazaz** [comment]
@cbmgit Did you figure out how to use this in the browser?
