### ISSUE TITLE
Dart coping with empty lists and null values in general

### ISSUE THREAD

**Issue by wurstnudl** [quicktype/quicktype#1388]
I'm currently generating dart code from json instances.
Basically it works good, however I ran into one annoying issue:

When quicktype generates it's toJson() method, it assumes lists are never null. This leads to nullpointers.

Problematic exemplary line in generated code:
`address: List<Address>.from(json["address"].map((x) => Address.fromJson(x))),`

Solution (with modified generated code):
`address: List<Address>.from(json["address"]?.map((x) => Address.fromJson(x)) ?? List()),`

Error:
`NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map(Closure: (dynamic) => Address)`

Had a very quick glimpse at the typescript code, I think the error could easily be fixed.
I assume it's here, quicktype version is 15.0.209, in Dart.js Line 254:

`protected mapList(itemType: Sourcelike, list: Sourcelike, mapper: Sourcelike): Sourcelike {
        return ["List<", itemType, ">.from(", list, ".map((x) => ", mapper, "))"];
 }`

Any ideas on this?

Disclaimer: Working with the provided (valid) schema doesn't work because of much deeper lying problems I can not tackle mainly because I don't know enough about typescript.

See this issue: https://github.com/quicktype/quicktype/issues/1376
The affected schema: https://www.hl7.org/fhir/STU3/fhir.schema.json.zip

**Comment by wurstnudl** [comment]
Solution:

`return ["List<", itemType, ">.from(", list, "?.map((x) => ", mapper, ") ?? List())"];`

I'd like to contribute, however cloning and trying to build the latest quicktype leads to the following error:

`npm ERR! elm@0.18.0-exp5 install: `npx binwrap-install`
npm ERR! Exit status 1
`, 
the reason probably being a 404 when trying to run npx binwrap-install:
`404 Not Found - GET https://registry.npmjs.org/binwrap-install - Not found`

Could anybode look into that?

**Comment by wurstnudl** [comment]
Quicktype can be build when running --ignore-scripts first (following the build instructions for windows; I'm running linux).

There are a lot more problems with nullchecks. I forked quicktype and added a few fixes to make it usable for us at all, I might create a pull request but I'd like a response to this issue first because I might be missing something.

**Comment by dvdsgl** [comment]
Do you mean, you want quicktype to always assume lists can be null, even if the type is non-optional? It sounds like your JSON samples don't have examples where the lists are missing. Please reopen if my understanding is not correct, but we cannot specialize the Dart language to always assume lists can be null.
