### ISSUE TITLE
is it possible that `paste json as types` command works in remote development？

### ISSUE THREAD

**Issue by nanlei2000** [quicktype/quicktype#1395]
I know the main issue here is we can not get the local clipboard text into remote, so i use `open quick type for json` command as a work round, is it possible that `paste json as types` command works in remote develop？
I use the `Remote Development` extension to work in remote machine.

**Comment by xgdgsc** [comment]
I also fiind it confusing that it shows `Could not get clipboard contents` when in remote.

**Comment by dvdsgl** [comment]
This sounds like a VS Code issue—if you cannot access the clipboard during remote development. Anyway, it should be on the https://github.com/quicktype/quicktype-vscode repo if it's a bug with the quicktype plugin itself.
