### ISSUE TITLE
[Dart] Use Null aware operator instead of Ternary operator.

### ISSUE THREAD

**Issue by vinceramcesoliveros** [quicktype/quicktype#1397]
## Change ternary operator to null aware operator
```dart
factory Customer.fromJson(Map<String, dynamic> json) => Customer(
        id: json["id"] == null ? null : json["id"],
        name: json["name"] == null ? null : json["name"],
        type: json["type"] == null ? null : Type.fromJson(json["type"]),
        defaultBilling: json["default_billing"] == null
            ? null
            : DefaultBilling.fromJson(json["default_billing"]));
```
to
```dart

factory Customer.fromJson(Map<String, dynamic> json) => Customer(
        id: json["id"] ?? null,
        name: json["name"] ?? null,
        type: json["type"] ?? null,
        defaultBilling: DefaultBilling.fromJson(json["default_billing"] ?? null) ?? null);
```

**Comment by ram231** [comment]
@dvdsgl , I can submit a PR for this. are you working on this new feature?

**Comment by dvdsgl** [comment]
@ram231 sounds good! Should be easy enough and not break any existing code.

**Comment by dvdsgl** [comment]
Actually it might be more complex—I believe those expressions are generated based on the types being optional. Also the example you gave is not equivalent—`DefaultBilling.fromJson` can be passed `null`.

**Comment by ram231** [comment]
my example seem to be rushed that I didn't checked if it will work or not. Adding `bool operator==(other)` or [Equatable](https://pub.dev/packages/equatable) package would be able to compare if the nested object is null.
 
Also, I find it hard to use null aware operator on Lists. so it might be a good use to have ternary operator on List.

**Comment by ThinkDigitalSoftware** [comment]
@ram231 and further, 
```dart
factory Customer.fromJson(Map<String, dynamic> json) => Customer(
        id: json["id"] ?? null,
        name: json["name"] ?? null,
        type: json["type"] ?? null,
        defaultBilling: DefaultBilling.fromJson(json["default_billing"] ?? null) ?? null);
```

should be 
```dart
factory Customer.fromJson(Map<String, dynamic> json) => Customer(
        id: json["id"],
        name: json["name"],
        type: json["type"],
        defaultBilling: DefaultBilling.fromJson(json["default_billing"]));
```

since return null if an item is null is redundant

**Comment by ram231** [comment]
Anyways. I found it tedious to workaround with List. That's why I feel like maybe it was hard for me to implement this.

**Comment by ThinkDigitalSoftware** [comment]
What do you mean workaround? I may be able to help

On Apr 8, 2020 2:13 PM, Vince Ramces Oliveros <notifications@github.com> wrote:

Anyways. I found it tedious to workaround with List. That's why I feel like maybe it was hard for me to implement this.
