### ISSUE TITLE
Generate code via cli from a JSON schema file

### ISSUE THREAD

**Issue by melissapalmer** [quicktype/quicktype#1398]
Hi, 

How does one convert from JSON schema file to code? In particular I am looking to generate Java code. There is no json-schema option for the `--src-lang`  flag. And using json does not get me the correct classes. 

Thanks
Melissa

**Comment by WanderHuang** [comment]
`quicktype -o YourJavaFile.java source.json --just-types`

Maybe this can help u. You don't need to set `json-schema` type because it's just a `json`

**Comment by melissapalmer** [comment]
@WanderHuang  unfortunately I always get an error like: 
`Error: Please specify a language (--lang) or an output file extension.`

I have a json file with json schema that will generate a number of different Java classes, not just one.

**Comment by melissapalmer** [comment]
I worked this out I had been using the following type of command line: 
```
quicktype -s schema json_schema_def_file.json -o /Models.java
```
basically the lines in docs at: 
https://github.com/quicktype/quicktype#generating-code-from-json-schema
