### ISSUE TITLE
[json to java]Some fields are not converted correctly

### ISSUE THREAD

**Issue by lli429558167** [quicktype/quicktype#1402]
egg:
  (json)typeId => (java)typeID, 
  (json)codeCd => (java)codeCD
  ...

**Comment by dvdsgl** [comment]
This is correct, this is how Java is setup to treaty acronyms. You can add an option to customize this as C++ does if you desire.

**Comment by dvdsgl** [comment]
This is correct, this is how Java is setup to treaty acronyms. You can add an option to customize this as C++ does if you desire.
