### ISSUE TITLE
Case of member in my JSON got overridden

### ISSUE THREAD

**Issue by rpresser** [quicktype/quicktype#1411]
This JSON:

`{ "CountOfWTFRemarks": 5 }`

Becomes this C# code:

```
public partial class Welcome
{
    public long CountOfWtfRemarks { get; set; }
}
```

Because the case changed in going from a JSON key to a C# class property name, **this will never deserialize correctly.**  

Sure, you can argue that the case is non-optimal and should have been CountOfWtfRemarks when designed. But if I'm writing a client for an API that isn't under my control, quicktype generated code won't work properly without careful correction after generation.

In particular, I hit this wall while working with DigiCert's APIs, in particular https://daas.digicert.com/apicontroller/v1/certificate/list.

**Comment by dvdsgl** [comment]
Here is the default code quicktype emits:

```csharp
namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Welcome
    {
        [JsonProperty("CountOfWTFRemarks")]
        public long CountOfWtfRemarks { get; set; }
    }
}
```

Which works. You're turning off options from default that breaks the parsing.

We would accept a contribution that changes the acronym handling here, as C++ allows, but we implemented the .NET naming standards.

Closing as feature request.
