### ISSUE TITLE
I couldn't get this to work at all, C++ 17 VS 2019

### ISSUE THREAD

**Issue by ScottyMac52** [quicktype/quicktype#1416]
I generated separate classes and tried the documented test method:
```
#pragma once
#include "nlohmann/json.hpp"
#include <optional>
#include <stdexcept>
#include <regex>
#include <codecvt>
#include <iostream>
#include <locale>
#include "Generators.hpp"

using json = nlohmann::json;

int main()
{
    vyper::helper.hpp data = nlohmann::json::parse(jsonString);
    std::wcout << vyper::wdump((nlohmann::json) welcome);
}
```
So as to be fair I decided to try and generate it as a single file and then isolate and remove as many errors as I could and this is where I am at present:

```
    std::string jsonString = R"({ "modules": [{"name": "F-14R"},{"name": "F-15RHV" } ]})";
    vyper::vyper data = nlohmann::json::parse(jsonString);
    std::wcout << vyper::wdump(static_cast<nlohmann::json>(vyper));
```
This is using the single header in vyper.zip.
[vyper.zip](https://github.com/quicktype/quicktype/files/4285000/vyper.zip)

From this I get the following compiler errors:
```
1>C:\Users\Scott\Source\Repos\VDM\testHarness\testHarness.cpp(23,58): error C2440: 'initializing': cannot convert from 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>' to 'vyper::vyper'
1>C:\Users\Scott\Source\Repos\VDM\testHarness\testHarness.cpp(23,23): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>C:\Users\Scott\Source\Repos\VDM\testHarness\testHarness.cpp(24,65): error C2882: 'vyper': illegal use of namespace identifier in expression
1>C:\Users\Scott\Source\Repos\VDM\testHarness\testHarness.cpp(24,26): error C2672: 'vyper::wdump': no matching overloaded function found
```

I get multiple compiler errors and I am using VS 2019 C++ set to C++ 17. Most of the errors seem to be related to missing namespaces. I have attached the generated code and I attached the original JSON file I used.
[Welcome C++ (quicktype).zip](https://github.com/quicktype/quicktype/files/4284922/Welcome.C%2B%2B.quicktype.zip)
[F-14BRIO.zip](https://github.com/quicktype/quicktype/files/4284924/F-14BRIO.zip)

**Comment by loveCatCoder** [comment]
Any progress? I have the same problem.

**Comment by ScottyMac52** [comment]
No, I gave up and found a simpler framework for JSON in C++ for my project.
It's too bad I like the code generation but there needs to be better QA. I
tried c++95, 11, 14 and 17.

**Comment by ScottyMac52** [comment]
Two weeks goes by and no comments from the coders? This thing is DEAD.
