### ISSUE TITLE
json length restriction in dart?

### ISSUE THREAD

**Issue by ejin66** [quicktype/quicktype#1424]
quicktye failed to create model with this json in dart: 
`{
  "aaaaaaaaaa": 1,
  "bbbbbbbbbb": 24,
  "cccccccccc": 4004.1,
  "ddd": 6.1
}`
but, when i decrease a word, it works:
`{
  "aaaaaaaaaa": 1,
  "bbbbbbbbbb": 24,
  "cccccccccc": 4004.1,
  "dd": 6.1
}`
Is there any length restriction?

**Comment by dvdsgl** [comment]
It's being detected as a map, try `--no-maps`.
