### ISSUE TITLE
argument list too long: quicktype

### ISSUE THREAD

**Issue by ManAnRuck** [quicktype/quicktype#1427]
I have ~165000 files, and when I run `quicktype **/*.json -o Procedure.ts` I get this error message
`argument list too long: quicktype`

i want to try to get the types for all json files in one for this repo.
https://github.com/bundestag/dip21-daten

**Comment by dvdsgl** [comment]
Can you try placing all the JSON files in a directory, and quicktyping the directory? I don't think shells support 165k arguments anyway.
