### ISSUE TITLE
Optional Template Configuration

### ISSUE THREAD

**Issue by MarkAlicz** [quicktype/quicktype#1442]
First off you guys have done an amazing job KUDOS!!!

One thing I wind up doing is taking the FromJson and ToJson methods and putting them in the base class.  In addition I make the ToJson method a non static method. 
I was wondering if you would think about allow us to edit the templates and save different variations.

Example
public string ToJson() => JsonConvert.SerializeObject(this, Converter.Settings);

**Comment by dvdsgl** [comment]
This is done to allow extension methods on array types and primitives.

Customizing the strings you mention is an awesome idea but a very large feature. We once had experimental handlebars support to allow something like this.

Closing for now, as this is a huge project. Please reopen if you feel like spec'ing it out and taking the project forward.
