### ISSUE TITLE
Allow multi-file output in the command line for languages like Java

### ISSUE THREAD

**Issue by Fleker** [quicktype/quicktype#1447]
I am trying to convert several JSON schema files into Java as part of a larger build process. I'd like a simple way to call Quicktype with my series of schemas and get a series of Java files out.

When I run:

`./node_modules/.bin/quicktype -s schema ./schemas/*.json -l java --package com.app -o mylib.java`

Nothing happens. Running the tool without any output flag, the output is printed to the console, containing all of my files with comments stating the file name. There doesn't seem to be a way, through the CLI, to specify an output directory.

This is a feature request to allow for an output directory and to get many files generated, one for each input file. Ideally the generated files should be named based on the input file name.

**Comment by Fleker** [comment]
cc @proppy @canain

**Comment by dvdsgl** [comment]
What happens when you put your schemas in a folder, and quicktype that folder, as described in the command line help? Please reopen if that does't work. The Java renderer is multi-file by default already.

**Comment by Fleker** [comment]
That works for me, thanks.

**Comment by kmturley** [comment]
"The Java renderer is multi-file by default already"

Should the `multi-file-output` option be used within the Java file similar to this?
https://github.com/search?q=repo%3Aglideapps%2Fquicktype%20multiFileOutput&type=code

Today you can generate Java single file and multi file programmatically using these two methods:
```
quicktype()
quicktypeMultiFile()
```

See my demo
https://github.com/kmturley/quicktype-typescript-input-demo
