### ISSUE TITLE
Can quicktype keep the origin json name for generate codes

### ISSUE THREAD

**Issue by foobra** [quicktype/quicktype#1448]
`
{
  "m_bTestBLEStatus" : true
}
`

Can I generate c++ codes as 
`
struct Welcome {
  bool m_bTestBLEStatus;
};
`

not, "mBTestBLEStatus", "m_b_test_ble_status", "MBTestBleStatus", "mBTestBleStatus", "M_B_TEST_BLE_STATUS", "MBTestBLEStatus", "mBTestBLEStatus".

**Comment by dvdsgl** [comment]
You could add an option to do this. Closing, as it is a feature request.
