### ISSUE TITLE
Can quicktype generate java codes with @Nullable and @Nonnull annotations?

### ISSUE THREAD

**Issue by foobra** [quicktype/quicktype#1453]
Just like other languages, introduce jsr 305 to make codes more resonable.

**Comment by skornel02** [comment]
One problem that might arise is that JSR 305 was never released officially, and it might lead to issues.
Using Optional<> from Java 8 might be a better idea, as suggested in [this article](https://blog.codefx.org/java/jsr-305-java-9/#Alternatives-To-JSR-305)?

**Comment by dvdsgl** [comment]
Sure, this could be added as an option. Closing as feature request.
