### ISSUE TITLE
The TypeScript testsuite fails when not running with the UTC timezone

### ISSUE THREAD

**Issue by untitaker** [quicktype/quicktype#1459]
This fails under the CEST timezone:

```
npm run build
FIXTURE=typescript npm test
```

Some ambiguous datetimes that either have no time or timezone do not roundtrip correctly.

By setting the environment variable `TZ=UTC`, the tests pass.

**Comment by skornel02** [comment]
Setting that environmental variable in the [test script](https://github.com/quicktype/quicktype/blob/master/script/test) should be a fix for this issue.
As a disclaimer this might prove a hindrance when trying to run tests on Windows systems.
