### ISSUE TITLE
Swift --protocol can't use custom protocol

### ISSUE THREAD

**Issue by miku1958** [quicktype/quicktype#1472]
I try to add WCDBSwift.TableCodable and HandyJSON in converted model, but quicktype give me an Error: Unknown value WCDBSwift.TableCodable,HandyJSON for option protocol.

Is it any possible that I can add custom protocol automatly in the future? If yes, maybe you can consider to add protocol in a extension?

**Comment by dvdsgl** [comment]
Great idea! Please consider contributing this. We do not keep feature requests open as issues, however, so I will close this.
