### ISSUE TITLE
Is it possible to pass configuration options to "TargetLanguage" instances programmatically?

### ISSUE THREAD

**Issue by GavinRay97** [quicktype/quicktype#1478]
I've poured over the source code and docs, and I can't seem to figure out how to pass config options to TargetLanguage instances or when calling `quicktype()`.

I have the following, which works, but I would like to use Python 3.7, and also to have the ability to configure the other options present when using the CLI:

```ts
async function quicktypeTypescript(targetLanguage, typeName, files) {
  const typescriptSchema = schemaForTypeScriptSources(files)
  //@ts-ignore
  const schemaInput = new JSONSchemaInput(new JSONSchemaStore())

  await schemaInput.addSource({
    name: typeName,
    schema: typescriptSchema.schema,
  })

  const inputData = new InputData()
  inputData.addInput(schemaInput)

  return quicktype({
    inputData,
    lang: targetLanguage,
  })
}

async function main() {
  const { lines: pythonResult } = await quicktypeTypescript(
    'python',
    '#/definitions/',
    ['./tsTypeDefs.ts']
  )
  console.log(pythonResult.join('\n'))
}

main()
```

Manually constructing `PythonTargetLanguage` doesn't seem to provide an opportunity for `options` in the construtor, or a builder-pattern `.withOptions()` etc:

```ts
const python = new PythonTargetLanguage('test', ['test'], 'py')
```

Is this possible to do from code, or only when executing from CLI?

**Comment by GavinRay97** [comment]
Update: found answer from @dvdsgl here linked to a Runkit example that happened to use `rendererOptions`, really happy I stumbled on that.

https://github.com/quicktype/quicktype/issues/1326#issuecomment-568306268

```ts
quicktype({
    inputData,
    lang: 'python',
    rendererOptions: {
      'python-version': '3.7',
    }
  })
```

Works perfectly, sorry for opening an issue :+1: 

(Might be useful to make a note of `rendererOptions` in the readme example)

**Comment by Vaibhavsaharan** [comment]
How can I call quicktype with renderer options in my python script. I am using this

`subprocess.check_call("quicktype input/schema.json --lang python --options {'python-version' : '3.7'} --top-level '+ camel_case_template +' --out input/backend/model.py", shell=True)`
