### ISSUE TITLE
Typescript - [key: string] breaks the parser, also for recursive types

### ISSUE THREAD

**Issue by GavinRay97** [quicktype/quicktype#1481]
For some reason, Quicktype doesn't handle `[key: string]` very well in Typescript. Both examples below cause Quicktype to freeze:
```ts
interface Something {
  value: string
  [key: string]: Something
  another: number
}
```
```ts
interface Something {
  val: number
  [key: string]: string
}
```

**Comment by dvdsgl** [comment]
We don't support types, mixing static and dynamic members.

This works just fine:

```ts
class AddressBook {
  /**
   * A dictionary of Contacts, indexed by unique ID
   */
  contacts: { [id: string]: Contact };
}
```

**Comment by GavinRay97** [comment]
Ahh okay, understood. How would you represent a type which has a mix of known and unknown keys @dvdsgl?
