### ISSUE TITLE
Use of serde instead of serde_json

### ISSUE THREAD

**Issue by AntonBlomstrom** [quicktype/quicktype#1493]
https://github.com/quicktype/quicktype/blob/7a6a0fbdaa817ac36d0acf8701fe92e36ae261d6/src/quicktype-core/language/Rust.ts#L378
Think this line might be outdated. I changed it to `use serde::{Deserialize, Serialize};` in my own code.

**Comment by mocsy** [comment]
Duplicate of #1210 

It might as well be optional, as current code compiles with edition  2018 disabled as well.
