### ISSUE TITLE
Placing to_json / from_json methods in nlohmann namespace leads to multiply compile errors

### ISSUE THREAD

**Issue by llilakoblock** [quicktype/quicktype#1494]
Take a look at this issue in nlohmann's repo: https://github.com/nlohmann/json/issues/780

**Comment by Jusonex** [comment]
This is a duplicate of #1185. Unfortunately, this problem makes the codegen unusable with MSVC.

Have you considered integrating the solution suggested in https://github.com/quicktype/quicktype/issues/1185#issuecomment-506614282? It seems to fix the problem for me.
