### ISSUE TITLE
Very slow performance for Kotlin

### ISSUE THREAD

**Issue by abeeriqbal** [quicktype/quicktype#1497]
I am using converting simple json object to data class using quicktype
but it take alot of time. For  3 to 4 objects it takes 2 to 3 seconds and for large objects it takes 20 to 40 seconds, but when i am using Gson, it will parse data in milliseconds. So for Kotlin i will not prefer anyone to use quicktype. 

 data class ChannelProgramsItem (
        val id: Long? = null,

        @Json(name = "view_count")
        val viewCount: Long? = null,

        val title: String? = null,
        val comments: Long? = null,
        val images: String? = null,

        @Json(name = "image_path")
        val imagePath: String? = null
    ) {
        public fun toJson() = klaxon.toJsonString(this)

        companion object {
            public fun fromJson(json: String) = klaxon.parse<ChannelProgramsItem>(json)
        }

        fun imagePath() : String {
            return imagePath + ""
        }
    }

**Comment by dvdsgl** [comment]
Please use `kotlinx` instead of `klaxon`.
