### ISSUE TITLE
swift convert error

### ISSUE THREAD

**Issue by mingkyme** [quicktype/quicktype#1500]
{"result_msg": ""}

to Swift code

expected
struct Welcome {
    let result_msg: String
}

reality    
struct Welcome {
    let resultMsg: String
}

Is it error?

**Comment by dvdsgl** [comment]
The actual code produced by `quicktype` with default settings is correct and adheres to Swift naming conventions by design:

```swift
import Foundation

// MARK: - Welcome
struct Welcome: Codable {
    let resultMsg: String

    enum CodingKeys: String, CodingKey {
        case resultMsg = "result_msg"
    }
}
```
