### ISSUE TITLE
'quicktype-core' has missing dependency 'is-url'

### ISSUE THREAD

**Issue by exKAZUu** [quicktype/quicktype#1502]
`quicktype-core` depends on `is-url`, but there is no reference in its `package.json`.

### Reproducntion steps
1. `mkdir test`
1. `cd test`
1. `npm i quicktype-core`
1. `node -e "require('quicktype-core')"`
1. The following error occurs

```
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'is-url'
```

**Comment by slaivyn** [comment]
Thank for having fixed this issue I am facing right now!
Will it be deployed soon to npm? 😃
