### ISSUE TITLE
How to use multi json on localhost?

### ISSUE THREAD

**Issue by Dexus** [quicktype/quicktype#1508]
Hi, i have a very big JSON collection, that need to generated as a Struct for GO,

There are multiple samples for each model/struct.

How can I do the same as app.quicktype.io?

EDIT1:
If I try that with app.quicktype.io it crash... i have over 55MB minified JSON and localstorage only expect 10MB...

**Comment by skornel02** [comment]
Hi, have you tried pointing it at a folder with jsons in it? 
`quicktype -l <language> -s json ./jsons/`

**Comment by Dexus** [comment]
Ok, I miss that example in the help.
