### ISSUE TITLE
IntelliJ Platform Plugin?

### ISSUE THREAD

**Issue by da3dsoul** [quicktype/quicktype#1510]
Personally, I use Rider, but all of the Jetbrains software use the same plugin engine, and I think QuickType would be so nice in Rider, IDEA, Pycharm, or whatever.
I'm not familiar with the plugin framework, but I could see it being implemented as generators, extraction refactors, or a tool window extension.
Here's a link to their docs if someone familiar with the project wants to take a look: https://www.jetbrains.org/intellij/sdk/docs/intro/welcome.html

In the meantime, I'll just use it online, in VSCode, or something.

**Comment by dvdsgl** [comment]
We would love for someone to build it. Closing as feature request.

**Comment by da3dsoul** [comment]
I didn't see a place for feature requests. Where are they at?
