### ISSUE TITLE
Use num for Dart instead of int or double

### ISSUE THREAD

**Issue by MichaelPriebe** [quicktype/quicktype#1514]
[num](https://api.dart.dev/stable/2.8.4/dart-core/num-class.html) is very good to use when parsing json when its not always obvious that a number will be an integer or a double. Often times when using Quicktype for Dart you will get errors of mismatched ints and doubles when your sample just happened to not have either or. This severely decreases the usefulness of Quicktype if you have to go back and manually adjust your samples.

**Comment by dvdsgl** [comment]
You're welcome to add an option for this if it's important for Dart, but we consider quicktype's ability to distinguish int and double types a feature.

I also think "severely decreases the usefulness of Quicktype" is an exaggeration.
