### ISSUE TITLE
Support YAML JSON Schemas

### ISSUE THREAD

**Issue by duydao** [quicktype/quicktype#1526]
Supporting YAML JSON Schemas seems to be easy enough to add, is there a specific reason that it wasn't included yet?

**Comment by davinchia** [comment]
Is there any reason why this was closed? I was attempting to generate code for yaml based Json Schema and it wasn't working for me, so I'm curious.

**Comment by duydao** [comment]
@davinchia There was no response to this issue (or any others), it seems dead community-wise so I've closed it. Feel free to create another isse, good luck!
