### ISSUE TITLE
Negative integers parse as Double

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#154]
`Data.String.Util.isInt` is too simplistic:

https://github.com/quicktype/quicktype/blob/master/src/Data/String/Util.js#L13

Also needs to be fixed in `quicktype.ts`:

https://github.com/quicktype/quicktype/blob/master/cli/quicktype.ts#L215

**Comment by dvdsgl** [comment]
Now that we ship all modules unbundled, the TypeScript should import the PureScript function.

**Comment by schani** [comment]
Fixed in e3c3c147987b3d6e78b91a024fc9d91aa6888bf0
