### ISSUE TITLE
Update KotlinX target to support Kotlin 1.4.0

### ISSUE THREAD

**Issue by asarazan** [quicktype/quicktype#1558]
Kotlin just had a big new release, and the [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) framework is finally hitting 1.0. There are a couple breaking changes in the serialization boilerplate that need to be updated.

Having contributed the original KotlinX support to quicktype; it's likely that either myself or @vaudevillen will take this on. Just wanted to get an official issue filed so I don't forget :-)

**Comment by mfrtrifork** [comment]
@asarazan what is the status of this ? Did you start development ?

**Comment by asarazan** [comment]
Hey @mfrtrifork I noticed that kotlinx.serialization is still technically at 1.0.0-RC2 according to https://github.com/Kotlin/kotlinx.serialization/releases

I debate whether to get started now, but it does seem like there are still some pretty breaking changes happening, even between RCs. Hopefully it's a matter of days or weeks before it stabilizes at 1.0.0 and I can get started :-)

**Comment by mfrtrifork** [comment]
Thanks for the response @asarazan.
I ended up using klaxon which actually suits my needs very well, but thanks anyways 👍

**Comment by asarazan** [comment]
Makes total sense. I love kotlinx.serialization on all platforms, but its biggest value add is in multiplatform code at the moment. Klaxon is mature and a solid choice :+1:

**Comment by asarazan** [comment]
Hey all, now that the new serialization is stable, I've submitted a PR to bring us up to spec: 
* 1.0.0 Support: https://github.com/quicktype/quicktype/pull/1570
* Additional Bugfix: https://github.com/quicktype/quicktype/pull/1572
