### ISSUE TITLE
Key must be quoted | Wrong

### ISSUE THREAD

**Issue by abelardolg** [quicktype/quicktype#1575]
Hi there,
To my mind I have found a bug, maybe?

![Screenshot from 2020-10-13 23-21-00](https://user-images.githubusercontent.com/22522883/95917621-d5f2e980-0daa-11eb-80bc-ddd52e173892.png)

Best regards,

**Comment by HyperwaveGlitch** [comment]
I'm having the same issue. 
In my case, the json line it finds erroneous is `"unique": true`, so it's a boolean. 
There is one UUID in the json under another object, which is quoted. `   "type": "UUID",`

# I have tried the following:
- Removing the line it reacted too and any other values where the key is "unique"
- Removing the line with the UUID
- Turning off "Detect UUIDs" and turning off "Detects maps", and "Detect booleans in strings", one by one and all together
- I also tried all of the above while using private browsing session to visit the site with fresh cache and no cookies

Nothing has helped. 

# Here's the settings I used:
**Language tab:**
- C#, 6
- Array
- Complete

**Other tab:**
- 6
- Normal
- Double
- Object
- Object
- Everything else **on**, except "Merge similar classes" and the variations I have tried (mentioned above)

Even if there's a few hiccups now and then, I must say that I really like this tool. It has saved me **a lot** of work, and I really appreciate your efforts! Thanks!

**Comment by ghoshabhi** [comment]
My case is very simple.. I had a trailing comma. But the validation regardless says "Key must be quoted"
```json
{
    "foo": {
        "id": 1,
        "name": "baz",  // <<<<
    }
}
```

<img width="715" alt="image" src="https://user-images.githubusercontent.com/19292575/120903026-7a56c400-c5f8-11eb-9a43-273b75a3a4e5.png">
