### ISSUE TITLE
Multiple json schemas cause type re-definition errors for the boilerplate types like 

### ISSUE THREAD

**Issue by jaryder** [quicktype/quicktype#1592]
Hello,

I am trying to use quicktype to auto-generate C++ code for several JSON Schema documents.  I have tried a few different combinations of parameters (e.g. multi-source, output path) but cannot get headers that contain all the to/from_json() definitions (Generators.hpp gets clobbered with whatever the last JSON Schema document is) AND don't have name collisions for redefinitions of helper functions like get_untyped() (helper.hpp gets replicated if separate output directories are used for each JSON schema doc).

Is quicktype designed with the expectation that only a single JSON Schema document would be used for a compilation unit?

If required, I can provide a canonical example to enable a local repro.  But it's a pretty basic setup:
A.schema.json
B.schema.json

quicktype .... A.schema.json
quicktype .... B.schema.json

main.cpp:
#include "A.hpp"
#include "B.hpp"

Thanks!

**Comment by antonklava** [comment]
I think this issue is somewhat related to https://github.com/nlohmann/json/issues/780

A hack in the meantime is to change the namespace of the to_json/from_json functions

```
sed -i -z "s/\n\nnamespace nlohmann/\n\nnamespace MY_NAMESPACE/" A.hpp
sed -i -z "s/\n\nnamespace nlohmann/\n\nnamespace MY_NAMESPACE/" B.hpp
```
