### ISSUE TITLE
Support enums

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#16]
For string properties, can we form a relatively small set of equivalence classes from a large number of samples? We might represent that as an enum (if the target language has enums).

There are two parts to this:

- [x] Supporting enums in our IR, accepting them from JSON Schema, and producing code for them
- [x] Automatically detecting them from given JSON samples

We can and should do the former, whether we ever do the latter or not.

**Comment by schani** [comment]
Implemented in e3c3c147987b3d6e78b91a024fc9d91aa6888bf0
