### ISSUE TITLE
Support Mongo Schema

### ISSUE THREAD

**Issue by ubeytd** [quicktype/quicktype#1621]
It would be nice to have mongo schema generator :)

**Comment by nneuberger1** [comment]
I would like to see this happen. If this were included as a PR on the project, would be included into the release?

I'd consider contributing to the project if that's possible. I'd rather not have a one-off fork for myself to maintain.

Naturally, it would be mongoose based. I'd prefer it to be TypeScript and Mongoose generated outputs. That's what I manually build out now. I generate the TypeScript versions from quicktype and it produces the interfaces. Then I manually build out the mongoose schema classes by hand.

Maybe it could be an option to select as a switch on the Typescript language drop down option.

Or similar to 'TypeScript Zod' or 'TypeScript Effect Schema'.

Thoughts?
