### ISSUE TITLE
Cannot Delete in 'Multiple JSON' Source Type or add Sample

### ISSUE THREAD

**Issue by mikkelharris** [quicktype/quicktype#1665]
When trying to remove a Type or Sample or add a Sample there is an error in the console 'RangeError: Maximum call stack size exceeded.'

**Comment by dvdsgl** [comment]
Yes, I see it.

**Comment by vaaski** [comment]
This issue is over a month old, any updates?

**Comment by vaaski** [comment]
from what i can see the website itself isn't open-source.
however, firefox is able to show some more info about what might be the cause of the issue.

> ![image](https://user-images.githubusercontent.com/17879327/113617678-ef3c6a80-9656-11eb-8ce4-67ca168abda0.png)

it seems like /static/js/components/SourcePad/index.tsx is to blame, specifically the function on line 341.

> ![image](https://user-images.githubusercontent.com/17879327/113617969-50fcd480-9657-11eb-8cb5-1fc7398a08b8.png)
> i suspect the while loop is causing infinite recursion.

<br>

i'd love to help, but it doesn't seem like the website is open to contributions.

**Comment by dvdsgl** [comment]
Very strange — line 342 makes no sense, and seems to have been introduced by a refactor. Removing it and fixing a global var wee on line 347 resolves the issue. I am deploying the fix now.

**Comment by vaaski** [comment]
perfect, thank you!

**Comment by dvdsgl** [comment]
Fixed.

**Comment by vaaski** [comment]
can confirm, you can close #1681 too btw.
