### ISSUE TITLE
your footer covers the bottom size of json editor , i am unable to edit the json from bottom

### ISSUE THREAD

**Issue by habeel96** [quicktype/quicktype#1676]

**Comment by nizwar** [comment]
How can they didn't notice this at the first place,
Even on the announcement site there is a ridiculous unclosable banner covering their cookie agreement and footer

**Comment by habeel96** [comment]
> How can they didn't notice this at the first place,
> Even on the announcement site there is a ridiculous unclosable banner covering their cookie agreement and footer

exactly , 
atleast they could have made those banners dismissable

**Comment by NatoBoram** [comment]
Related to #1143
