### ISSUE TITLE
Why was Typescript removed from the list of available input sources from the app.quicktype.io web app?

### ISSUE THREAD

**Issue by GavinRay97** [quicktype/quicktype#1684]
☹️ Pls put it back, I beg of you

![image](https://user-images.githubusercontent.com/26604994/111817227-23bcd200-88b4-11eb-95f6-214b28ad8a67.png)

**Comment by danvk** [comment]
Just curious if there's an explanation for this. Is using TypeScript as a source language for quicktype discouraged? This change invalidates the links for repros in many quicktype issues, e.g. #1646.

**Comment by dvdsgl** [comment]
It was difficult to make it work in the browser due to dependency issues. We'd like to bring it back.

We are working to open-source the web app and add it to this repo, but we are busy.

**Comment by GavinRay97** [comment]
Congrats on the new business venture by the way, best of luck!
