### ISSUE TITLE
Use fewer private methods for extensibility 

### ISSUE THREAD

**Issue by ylilarry** [quicktype/quicktype#1686]
I need to extend the `SwiftRenderer` class to customize the output, but found it is impossible to do so, because too many methods are private.
For instance, one of the most important method to override:
```
    protected emitSourceStructure(): void {
        if (this._options.multiFileOutput === false) {
            this.renderSingleFileHeaderComments();
        }

        this.forEachNamedType(
            "leading-and-interposing",
            (c: ClassType, className: Name) => this.renderClassDefinition(c, className),
            (e: EnumType, enumName: Name) => this.renderEnumDefinition(e, enumName),
            (u: UnionType, unionName: Name) => this.renderUnionDefinition(u, unionName)
        );

        if (!this._options.justTypes) {
            this.emitSupportFunctions4();
        }
    }
```
contains `._options`, `this.renderClassDefinition`, `this.renderUnionDefinition`, `this.renderUnionDefinition` that are all private property/methods. It is therefore impossible to extend the `SwiftTargetLanguage` class for custom output.

A good design philosophy is to default to `protected`, unless there is a good reason to use `private`.

**Comment by schani** [comment]
@ylilarry Feel free to make a PR that changes those to `protected`.
