### ISSUE TITLE
Memory issue when converting a lot of files

### ISSUE THREAD

**Issue by timcole** [quicktype/quicktype#1710]
The answer this might be to go kick rocks but figured I'd bring it up anyways lol.
I'm trying to generate types based on a directory of examples.. There's one issue with that. There are 53,000 examples...

The server has 90GB of RAM but crashes at 4GB. To my understanding, this is a V8 limitation that can be suppressed with the `max-old-space-size` flag so I tried adding `NODE_OPTIONS=‘--max-old-space-size=32000’` in from of the original ` quicktype . -o ../faa.ts` command but the result was the same. :(

Does anyone have any recommendations even if this isn't an issue with quicktype's would still be really helpful! <3

```
<--- Last few GCs --->

[50:0x5059be0]   213852 ms: Scavenge 4065.1 (4140.9) -> 4063.4 (4140.9) MB, 6.3 / 0.0 ms  (average mu = 0.703, current mu = 0.579) allocation failure 
[50:0x5059be0]   213863 ms: Scavenge 4065.3 (4140.9) -> 4063.7 (4140.9) MB, 6.5 / 0.0 ms  (average mu = 0.703, current mu = 0.579) allocation failure 
[50:0x5059be0]   213874 ms: Scavenge 4065.5 (4140.9) -> 4063.7 (4144.9) MB, 7.4 / 0.0 ms  (average mu = 0.703, current mu = 0.579) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb12b00 node::Abort() [node]
 2: 0xa2fe25 node::FatalError(char const*, char const*) [node]
 3: 0xcf8a9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcf8e17 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xee2d65  [node]
 6: 0xef1ae1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xef4d3c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xec12eb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x122acab v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x160c479  [node]
Aborted (core dumped)
```

**Comment by prateek-somaiya** [comment]
I am in the same boat and it looks like this tool is a joke, clearly not scalable... I don't have the luxury of 90G of memory but this is something the tool should be able to handle or at least provide an option which could potentially take more time but use less memory. It looks like it reads everything in memory and then infer the schema, clearly no thought given to memory management. Disappointed!

**Comment by prateek-somaiya** [comment]
and to answer you question, try setting `--max-old-space-size=32000 globally`. I am using windows so I do it like this:
```set NODE_OPTIONS=--max_old_space_size=8192```

**Comment by bjwktcsnzh** [comment]
I suspect there is a memory leak of global variables, because I also get OOM when I try to use Worker.

**Comment by bjwktcsnzh** [comment]
> I am in the same boat and it looks like this tool is a joke, clearly not scalable... I don't have the luxury of 90G of memory but this is something the tool should be able to handle or at least provide an option which could potentially take more time but use less memory. It looks like it reads everything in memory and then infer the schema, clearly no thought given to memory management. Disappointed!

I tried using indexeddb instead of in-memory storage, but it slowed down badly on large datasets. This seemed hard to optimize.
