### ISSUE TITLE
Dart: Why "data" turns into "datum"?

### ISSUE THREAD

**Issue by hardiklakhalani** [quicktype/quicktype#1712]
JSON to Dart Converter:

For each 'key' containing the characters 'data' turns into "datum"!even "bannerdata" to "bannerdatum".
Why? 🤔

**Comment by NatoBoram** [comment]
Huh. I would understand if it detected `datas` and turned all `data` into `datum` then all `datas` into `data`, but if you don't have `datas` in the first place it's kinda pointless...
