### ISSUE TITLE
Typescript makes properties readOnly

### ISSUE THREAD

**Issue by esfomeado** [quicktype/quicktype#1749]
Hello,

Is there any way to make the properties readOnly when converting to typescript?

Thanks

**Comment by djmisterjon** [comment]
welp `jsonShemas` support flag `read-only`.
But it seem not supported in `quicktype` !
```json
{
  "id": "http://json-schema.org/geo",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "A geographical coordinate",
  "type": "object",
  "properties": {
    "latitude": {
      "type": "number",
      "readOnly": true
    },
    "longitude": {
      "type": "number"
    }
  }
}
``` 
I hope a good guy will can add those feature ! 
https://json-schema.org/draft/2019-09/json-schema-validation.html
Json shemas is the nextgen json for most sofware and game !
