### ISSUE TITLE
`lodash` is still referenced in the compiled output of the `quicktype-core` package

### ISSUE THREAD

**Issue by chaucerbao** [quicktype/quicktype#1750]
It seems like `lodash` is being referenced in the compiled (dist/) output. If you attempt to use the package, it will throw an error.

> Error: Cannot find module 'lodash'
> Require stack:
> - node_modules/quicktype-core/dist/language/Dart.js
> - node_modules/quicktype-core/dist/language/All.js
> - node_modules/quicktype-core/dist/Run.js
> - node_modules/quicktype-core/dist/index.js

To replicate, start a new repo:
1. `npm install quicktype-core`
2. `grep lodash node_modules/quicktype-core/dist/**/*.js`

You'll find the line in **dist/language/Dart.js**

**Comment by talks2much** [comment]
It seems that https://github.com/quicktype/quicktype/commit/679b7bcd9d11fc06b449b16b200ae05a6307767f wasn't published to npm. @dvdsgl I'm sorry for pinging you here, but do you have power of publish new working package?

**Comment by agriffis** [comment]
Is there a workaround for this other than using a fork?

**Comment by NemoStein** [comment]
> Is there a workaround for this other than forking?

Install lodash as a dependency
`npm i -D lodash`

**Comment by dvdsgl** [comment]
#1870
