### ISSUE TITLE
Website app.quicktype.io the bottom banner hides bottom text

### ISSUE THREAD

**Issue by Sun3** [quicktype/quicktype#1752]
The Website app.quicktype.io the bottom banner (The creators of QuickType are hiring...) hides the bottom text and you cannot view or edit the JSON text or view the results view on the right side.

Thanks.

**Comment by NatoBoram** [comment]
Install [uBlock Origin](https://github.com/gorhill/uBlock) and add this filter : 

```abp
app.quicktype.io##[href^="https://www.glideapps.com/jobs"]
```
