### ISSUE TITLE
is it support null safety of Dart Language for flutter?

### ISSUE THREAD

**Issue by bittuRichestsoft** [quicktype/quicktype#1783]
The parameter 'status' can't have a value of 'null' because of its type, but the implicit default value is 'null'. (Documentation)  Try adding either an explicit non-'null' default value or the 'required' modifier.

I don't know why this error happened. But  I have idea of null safety of dart language so please check it is support null safety or not.

**Comment by ltropin** [comment]
Duplicate #1673 ))
