### ISSUE TITLE
Unable to Scroll down on JSON container

### ISSUE THREAD

**Issue by tingaz-2nye** [quicktype/quicktype#1797]
I am unable to scroll down and view the rest of the code because of the banner which is fixed at the bottom of screen plus the json container is not scrollable

**Comment by jeffctown** [comment]
It's also really hard to copy anything at the bottom.  Please make your ad dismissible.

**Comment by grant** [comment]
Yes, this makes app.quicktype.io a lot harder to use. Something changed in the working UI

**Comment by NatoBoram** [comment]
Duplicate of #1657

**Comment by lsh-0** [comment]
Not a duplicate, I can't scroll down on the output json container at https://app.quicktype.io
