### ISSUE TITLE
JSON to Dart @required modifier should be changed to required 

### ISSUE THREAD

**Issue by shortstopyomin** [quicktype/quicktype#1826]
class ProfileRequest {
    ProfileRequest({
        **@required** this.email,
        **@required** this.password,
    });

    final String email;
    final String password;

    }

**Comment by romme86** [comment]
I tried to push a new branch for a pull request and I got permission denied. 
It is an easy fix...

**Comment by NatoBoram** [comment]
@romme86 That's not how GitHub works. You need to click on the **Fork** button at the top of the page.
