### ISSUE TITLE
[Website Issue] Bottom banner is overlapping the content

### ISSUE THREAD

**Issue by esc-0-bar** [quicktype/quicktype#1839]
The bottom banner of app.quicktype.io is overlapping the content.
Even there is no close button. 
Please make a close button or make it appear for 5s or as a pop-up.

### That thing is annoying.

**Comment by NatoBoram** [comment]
Duplicate of #1657

**Comment by esc-0-bar** [comment]
Closing this duplicate issue.

Temporary solution:
https://github.com/quicktype/quicktype/issues/1657#issuecomment-885791211
