### ISSUE TITLE
Converter class can conflict with System.Converter

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#184]
How do we make referencing this class unambiguous? Does it simply need a different name?

**Comment by schani** [comment]
The point of namespaces is that names don't have to be unique.  You can use the namespace to qualify.

Does this make some of our generate code not compile?

**Comment by dvdsgl** [comment]
Yes, in a couple of cases I've seen errors in Visual Studio when `System.Converter` and `QuickType.Converter` were both in scope. I'll post the exact circumstance if I see it again.

**Comment by schani** [comment]
Is this still a thing?

**Comment by dvdsgl** [comment]
I don't believe so, and #276 can be considered a replacement for this issue anyway.
