### ISSUE TITLE
Ads "hiring engineers" hides part of code

### ISSUE THREAD

**Issue by abelardolg** [quicktype/quicktype#1844]
Hi,

Your ads for hiring engineers, located at the bottom of the page, hides part of code.  I can't scroll to  completely see it.

Proposed solution: by adding "X" to manually close it.

Best regards.

![image](https://user-images.githubusercontent.com/22522883/144565313-12c0ce8d-cc11-4d21-9496-e17ed4639841.png)

**Comment by NatoBoram** [comment]
Duplicate of #1657
