### ISSUE TITLE
Consider removing C# 6.0+ requirements

### ISSUE THREAD

**Issue by thegoldenmule** [quicktype/quicktype#185]
The [Unity game engine](https://unity3d.com/) is widely used and uses the Mono compiler to compile C# scripts. However, it cannot compile C# 6.0 features. Unfortunately this means we can't use quicktype "out of the box", as the C# quicktype generates requires these arrow functions:

```
public partial class EmailSignInRequest
    {
        public static EmailSignInRequest FromJson(string json) => JsonConvert.DeserializeObject<EmailSignInRequest>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this EmailSignInRequest self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }
```

There's no benefit to using these language features in generated code. In fact the IL generated by the compiler is almost identical. Please consider falling back to older language features in this case.

**Comment by dvdsgl** [comment]
Consider it considered—we’re happy to remove it.
