### ISSUE TITLE
Please add support for null safety in dart language.

### ISSUE THREAD

**Issue by bittuRichestsoft** [quicktype/quicktype#1855]
Please add support for null safety in dart language.

**Comment by Phuong9Pay** [comment]
Same.

**Comment by vthakkar66** [comment]
Yes, Please add support for null safety :)

**Comment by chunlee-thong** [comment]
https://github.com/chunlee-thong/dart-quicktype
Give this a try if it fits your use case

**Comment by NatoBoram** [comment]
Duplicate of #1673

**Comment by RmondJone** [comment]
可以看看我提交的PR,现在等待官方合并，[#1904](https://github.com/quicktype/quicktype/pull/1904)
You can take a look at the PR I submitted, now waiting for the official merge。[#1904](https://github.com/quicktype/quicktype/pull/1904)
