### ISSUE TITLE
how do i specify --edition2018 flag for rust

### ISSUE THREAD

**Issue by Snazzie** [quicktype/quicktype#1866]
when i specify `--edition2018` in cli command, i get `Error: Option parsing failed: Unknown option: --edition2018.`

How am i suppose to activate this option?

https://github.com/quicktype/quicktype/blob/817c837e0a9df1d796f31f6f85030c85f9fcbec0/src/quicktype-core/language/Rust.ts#L50

**Comment by valkum** [comment]
It is missing here https://github.com/quicktype/quicktype/blob/5dd9b16974a8038d3a2092b1956bead063613808/src/quicktype-core/language/Rust.ts#L64
