### ISSUE TITLE
Flutter 2 with null safity

### ISSUE THREAD

**Issue by MBilalMurtaZa** [quicktype/quicktype#1889]
Hi, Bro I used this for a long time it's very helpful and time-saving. 
but the problem is here dart release null safety and model changed in null safety. 
please upgrade the dart JSON to a model with null safety.
thanks in advance.

**Comment by roiskhoiron** [comment]
i ve same problem with format @required so manualy i fix it to 'required' only

**Comment by dharmikvyas** [comment]
I faced same issue. Please update dart JSON part. Many thanks.

**Comment by RmondJone** [comment]
可以看看我提交的PR，现在等待官方合并。[#1904](https://github.com/quicktype/quicktype/pull/1904)
