### ISSUE TITLE
Cannot see all generated code

### ISSUE THREAD

**Issue by starteNCS** [quicktype/quicktype#1903]
When generating larger files the bottom banner hides the last few lines of generated code.

I would suggest to either add an option to close the banner, or add it below the page, not on top of it.

![image](https://user-images.githubusercontent.com/30404993/157887589-b272f121-8ff5-4ae9-9137-18a6d8201f8d.png)

**Comment by NatoBoram** [comment]
Duplicate of https://github.com/quicktype/quicktype/issues/1657
