### ISSUE TITLE
issue with analysing

### ISSUE THREAD

**Issue by jadhavswapnilgit** [quicktype/quicktype#1907]
hello,
I have used QuickType its very helpful but  from 2 hours the response data can not be converted to model what is issue ,please solve this issue
![Screenshot 2022-03-14 at 4 01 21 PM](https://user-images.githubusercontent.com/65398979/158154776-fee731d5-6603-4c7f-9a4a-91bd1935569c.png)

**Comment by PrabinMaharjan** [comment]
I am  facing same issue
