### ISSUE TITLE
The bottom ad / promo bar needs a close button !

### ISSUE THREAD

**Issue by Montago** [quicktype/quicktype#1914]
I can't see the bottom of the code because you have a top layer Promo bar, advertising something about job openings...

**Comment by vince-rippa** [comment]
Yes, please. It has been like this for months now, it covers the bottom of the text boxes and causes some serious headaches when trying to check the last lines of the pasted JSON or to copy only a parte of the generated code

**Comment by rimedar** [comment]
Yes, a close button, or a a minimize, it's so frustrating.
