### ISSUE TITLE
Question: Typescript -> (kotlin/Swift) with Integer

### ISSUE THREAD

**Issue by john-twigg-ck** [quicktype/quicktype#1918]
How do generate an integer when Typescript is the source, given that it only supports `number` which automatically becomes a `Double` in the target languages?

**Comment by tienne** [comment]
I have a similar problem.
I am converting typescript to swift.

**Comment by tienne** [comment]
i found use jsdoc

```typescript
export interface Menu {
  /**
   * @type integer
   */
  seq?:         number;
  name:         string;
  isFavorite:   boolean;
  
  isAlcohol:    boolean;
  price:        number;
  position?:    MenuPosition;
}
```
