### ISSUE TITLE
Consider leaving Json attributes on poco

### ISSUE THREAD

**Issue by thegoldenmule** [quicktype/quicktype#192]
It would be nice if there were a better middle ground between `--poco no` and `--poco yes` for C# generation. If I use `--poco no`, I get a lot of serialization classes I don't need that have collisions. If I use `--poco yes` I get a poco that does not match the case of the json definition files, and thus cannot be serialized/deserialized correctly.

It would be nice if the Json property tags were left on with `--poco yes`, or controlled via another flag.

**Comment by schani** [comment]
Yes, that makes sense.

**Comment by dvdsgl** [comment]
It sounds like the name conflicts are the real issue here.

**Comment by schani** [comment]
Independent of the main issue, it does make sense to have options to independently disable serializers and deserializers.  Disabling both gives you `--poco yes`, enabling both gives you `--poco no`, with two more choices in between.

**Comment by dvdsgl** [comment]
Well, disregarding the goal of the people who asked for `--poco no`, who wanted to remove references to `Newtonsoft.Json` for some reason.

**Comment by schani** [comment]
I'm not sure what you're saying.  I also think you mean `--poco yes`.  All of these goals are compatible.

**Comment by dvdsgl** [comment]
The people who asked for `--poco yes` wanted to strip all `JsonProperty` attributes *and* conversion helpers to have pure classes with no dependencies, presumably because they are not deserializing JSON or they want to bring their own frameworks.

This issue contradicts that use case (which I'm not sure if we want to facilitate anyway, we are a JSON tool, not a model templating tool, at the end of the day) by changing the meaning of `--poco yes` to re-add the `JsonAttributes`.

I agree that we should have a way to turn off serializers, but I don't think `--no-serializers --no-deserialiers` expresses the same user desire as `--poco yes`.

**Comment by dvdsgl** [comment]
In order of priority, I think we should:

1. Fix the name conflicts, which I think would obviates @thegoldenmule's desire to turn off de/serializers.
1. Add either `--no-helpers` or `--serializers no` `--deserializers no` and support them in all languages.
1. Keep `--poco new` (or possibly a more general option like `--no-dependencies`) an option that produces output without any dependencies.

**Comment by schani** [comment]
Ok, we need to pry things apart.  We have three pieces involved in serialization/deserialization:

1. The `JsonAttributes`.

2. The convenience methods `FromJson`, `ToJson`.

3. Explicit serialization and deserialization code for unions.

Being able to turn the convenience methods on and off makes total sense.  Many people might not use them, for a variety of reason, so why bother with them?

If you want either serialization or deserialization, then you need the `JsonAttributes`.  And if you want serialization you need the union serialization code, and the same goes for deserialization.  If you don't want either serialization or deserialization, you also don't need the `JsonAttributes`.

**Comment by schani** [comment]
What is `--poco new`?

**Comment by dvdsgl** [comment]
I often go back and fix these typos, I'm not sure why you don't see them – perhaps you need to refresh.

**Comment by schani** [comment]
We don't have to support this in all languages all at once to make sense.  We can add it as demand arises.

**Comment by schani** [comment]
I agree about the conflict being highest priority.  How do we fix this?  Just a namespace option?

**Comment by thegoldenmule** [comment]
Adding a namespace option would be grand, but it requires a ton of namespaces just to avoid collisions. In my use case, I have separate request + response json definitions that I'm trying to generate C# types for. Requiring a namespace for each model is _doable_ but tough to use. Consider:

```
var request = new Messages.CreateMyResource.Request.Request();
var response = new Messages.CreateMyResource.Response.Response();
```

It compiles, but it's kinda gross.

**Comment by schani** [comment]
@thegoldenmule So don't your collisions come from the data model, too?  If you have multiple `Request` and `Response` classes I mean?

**Comment by thegoldenmule** [comment]
My example is not great. Here's a better one:

My request:
```
namespace Messages.CreateUser
{
    using System;
    using System.Net;
    using System.Collections.Generic;

    using Newtonsoft.Json;

    public partial class Request
    {
        [JsonProperty("provider")]
        public string Provider { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        [JsonProperty("providerToken")]
        public string ProviderToken { get; set; }
    }
}
```

My response:
```
namespace Messages.CreateUser
{
    using System;
    using System.Net;
    using System.Collections.Generic;

    using Newtonsoft.Json;

    public partial class Response
    {
        [JsonProperty("error")]
        public string Error { get; set; }

        [JsonProperty("success")]
        public bool Success { get; set; }
    }
}
```

Now I can use them like:

```
await _messages.Send<Messages.CreateUser.Response>(new Messages.CreateUser.Request());
```

So I'm using the namespaces to breakout request/response pairs.

**Comment by thegoldenmule** [comment]
BTW-- I'm getting the output from above by having my build process rip generate through quicktype, then replace the namespace + rip off the serializers.

**Comment by schani** [comment]
@thegoldenmule Ok, so for your use case there are two problems:

1. The `Converter` conflict.  You can avoid that by using `--src-urls` to generate both in the same file.  Did that not work?

2. The namespace.  We should support that via an option.

**Comment by thegoldenmule** [comment]
Ah, I didn't realize `--src-urls` would generate them safely in the same file. I thought that was purely an optimization to avoid spinning up node over and over. I will try that.

And yes, namespaces are the bigger issue.

**Comment by schani** [comment]
Ok, so let's make namespaces the priority issue (luckily it should be pretty easy to implement).  And please report back on your success with `--src-urls` - it will generate everything in one file, without name collisions, unless we screwed up, in which case please file a separate bug report ;-)

**Comment by schani** [comment]
We've implemented customizable namespaces, and the rest is in #227
