### ISSUE TITLE
Consider creating build artifacts

### ISSUE THREAD

**Issue by thegoldenmule** [quicktype/quicktype#193]
Via our Slack discussion, it would be nice if we could generate compiled libraries from quicktype directly. This may be beyond the scope of quicktype, or be best as an extension, as plugging into arbitrary build toolchains may be too cumbersome.

However, for my use case (and I imagine, many others), it would be useful to generate a `dll` directly from a set of json definitions:

`quicktype -o Messages.dll --src-urls MyDefinitions.json`

**Comment by schani** [comment]
That's an interesting idea, but currently too far outside our scope, unless you'd be willing to contribute and maintain it.  But note: this is a feature that seems simple, and it's certainly not logically difficult, but it will require handling many combinations of configurations, writing lots of test code, and continuous maintenance to keep up with toolchain updates.
