### ISSUE TITLE
Xcode Extension not available in all regions!

### ISSUE THREAD

**Issue by guardian-ben** [quicktype/quicktype#1946]
<img width="372" alt="Screenshot 2022-05-09 at 15 55 31" src="https://user-images.githubusercontent.com/104841688/167437904-447bbf3f-ceaa-4328-b338-2d1e6815ef0b.png"> 

Could we make the Xcode Extension available in all regions, please?

**Comment by dvdsgl** [comment]
We cannot support the macOS app.
