### ISSUE TITLE
Asking for hiring engineers on the macOS app hide the bottom content

### ISSUE THREAD

**Issue by Sparklydust** [quicktype/quicktype#1960]
macOS Monterey Version 12.4
MacBook Pro (14-inch, 2021) Apple M1 Max 64GB
Quicktype Version Undefined (Could not find it attached to "About quicktype" info on the mac application. 

- Open the quicktype app
- Add a json to parse the data
- Got a result
- Bug: Could not see the last lines are they are hidden by your company looking to hire

![Screenshot 2022-06-15 at 11 08 47](https://user-images.githubusercontent.com/40178207/173789730-308337f0-0639-4267-b978-2259a2f2662e.png)

**Comment by Crayon2000** [comment]
This is a duplicate of issue #1914
