### ISSUE TITLE
Generic properties in C# sample

### ISSUE THREAD

**Issue by marekott** [quicktype/quicktype#1965]
Hello,
is there a way to generate C# sample with generic property which type won't be escaped? Please find below an example:
![image](https://user-images.githubusercontent.com/46067021/175945124-9ab3d476-94bc-4549-b688-3146d132e32c.png)

As you can see `<>` were removed from type definition despite being a valid class name. Similar issue will occur when type is described by full name (with namespace). Valid dots separating words in namespace will be removed. Is there any setting that allows for disabling escaping those characters?

**Comment by dvdsgl** [comment]
We cannot support that generic syntax in JSON Schema
