### ISSUE TITLE
Need to declare arrays typedef/prototypes/functions

### ISSUE THREAD

**Issue by joelguittet** [quicktype/quicktype#1984]
Hello,

I'm currently working on cJSON (https://github.com/DaveGamble/cJSON) generator. For this I need to have the list of arrays to generate typedef/prototypes/functions. I need to have the name of the array and the type of the items.

Today I'm using this code snippet to generate enum or classes, providing the types and names:

```
this.forEachEnum("leading-and-interposing", (enumType: EnumType, enumName: Name) =>
    //CODE
);
```
```
this.forEachObject("leading-and-interposing", (classType: ClassType, className: Name) =>
    //CODE
);
```

This is mainly retrieving code snippets from the C++ language generator.

Question is: is it possible to have similar code snippet to have the list of arrays ? I need to declare them before they are used in parent class. I also need to generate specific functions to manage them.

Thanks,

Joel

**Comment by schani** [comment]
You can use `forEachType` and then use `matchTypeExhaustive` to process the arrays.

**Comment by joelguittet** [comment]
Hello Mark,
Thanks for the advice, I have found a solution.
Joel
