### ISSUE TITLE
Footer bar is breaking usability

### ISSUE THREAD

**Issue by paulocoutinhox** [quicktype/quicktype#2006]
Hi,

The footer bar is breaking usability on website.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/395096/197558683-629b6519-bbbc-4b41-935e-3038c826c805.png">

I can't see all the content.

**Comment by Crayon2000** [comment]
This is a duplicate of issue https://github.com/quicktype/quicktype/issues/1914
