### ISSUE TITLE
How build quicktype on mac?

### ISSUE THREAD

**Issue by jeffasd** [quicktype/quicktype#2042]
I am new in quicktype
I clone code from github

i change package.json "elm": "0.18.0-exp5", to "elm": "0.19.1-5",
then delete script/quicktype 

then bash``` npm install
or bash``` npm run build

but in script folder the quicktype not create

I use ./script/quicktype test_model.json -o test_model.java

but here i delete script/quicktype, when i run npm run build,the new quicktype not create

what happen? 

I can`t create script/quicktype shell

**Comment by dvdsgl** [comment]
Try again. `elm` dependency is removed. Be sure to follow steps in README.
