### ISSUE TITLE
Site suddenly not working

### ISSUE THREAD

**Issue by brockweaver** [quicktype/quicktype#2043]
This tool is amazing! Thank you so much for all your work and time.  I've been using this the past few days and it has saved me a ton of typing.

Unfortunately I started getting this error just today (Dec 24 2022 around 2pm Central) in chrome console.  Looks like there might be a problem on the webserver for mime type mappings.

- Refused to execute script from 'https://app.quicktype.io/worker-json.js' because its MIME type ('text/html') is not executable.

There are errors after that but they appear to be related to this first problem.

**Comment by dvdsgl** [comment]
@brockweaver hello! I cannot repro this. Can you add some screenshots?

**Comment by dvdsgl** [comment]
Please reopen if you can add more info
