### ISSUE TITLE
Python Support

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#205]

**Comment by DAMANgoldberg** [comment]
As per instructions from Twitter. Enclosed is the JSON file I had for other purposes, and a PDF with the Formal JSON Viewer plugin in Notepad ++. I see how it translates to valid TypeScript code that can be plugged in. Wanting something similar for Python as I am a newbie programmer beyond HTML and Basic, and not very fond of the C type of languages. Thanks.

[JSON_python.zip](https://github.com/quicktype/quicktype/files/1326127/JSON_python.zip)

**Comment by dagrooms52** [comment]
I'm also interested in this feature. I haven't done much TypeScript, but this feature would really help me at my day job, so I'm considering contributing in this area. I'm unable to start this until [this issue](https://github.com/quicktype/quicktype/issues/291) is resolved.

**Comment by schani** [comment]
@dagrooms52 Are you still on this?  Is there anything we can do to help?

**Comment by dvdsgl** [comment]
@ianleatherbury is also interested in working on Python support but doesn't think he'll be able to deliver for a couple of months.

**Comment by IanLeatherbury** [comment]
Yup, still nailing down my schedule for the New Year right now. I should have a better idea of a timeline in the next couple of weeks.

**Comment by dagrooms52** [comment]
Last thing I did before the holidays was start testing, it looked like the renderer API breaking changes had broken a few things for my Python renderer layer so I decided to wait for the dust to clear. Is the API feeling more stable now? I don't think I'll be able to hammer through fixing the breaking changes and testing fast enough to not get broken by the next API changes otherwise. I can only give it about an hour every night.

**Comment by schani** [comment]
Sorry about that.  Just keep targeting whichever quicktype commit you're on now, and once you have it somewhat working I'll just adapt it to the latest changes.  I've been doing that a lot - I'm pretty efficient at it ;-)

**Comment by schani** [comment]
@IanLeatherbury How's it going?

**Comment by IanLeatherbury** [comment]
Am hopefully about to finish emitting classes today. I think the implementation is pretty simplistic, and I'm not sure exactly what you guys need in terms of tests, but, I can submit a PR soon and we can find out :-)

**Comment by schani** [comment]
I can help you set up the tests - it's pretty easy.  The main thing you need is a "driver" file, which is basically a simple Python command line program that uses the code you emit to deserialize some input JSON and then to serialize it back to JSON.

This is the driver for C#, for example: https://github.com/quicktype/quicktype/blob/master/test/fixtures/csharp/Program.cs

You can take the filename from the command line arguments, or you can read from stdin - it doesn't matter.

**Comment by IanLeatherbury** [comment]
Ah gotcha, yeah that seems pretty simple. I'm going to finish the FromJson side today, I still need to take a look at the ToJson side though.

**Comment by SamuelMarks** [comment]
Any news? - Really could be a useful language output 👍

**Comment by IanLeatherbury** [comment]
Sady, I'm not going to finish this anytime soon. I've had some work project come up that are taking up my weekend coding time. Anyone else want to give it a shot?

**Comment by IanLeatherbury** [comment]
Yep, you can find the repo [here](https://github.com/IanLeatherbury/quicktype/tree/python) in the Python branch.

The typescript file to do the transformation is [here](https://github.com/IanLeatherbury/quicktype/blob/python/src/Language/Python.ts).

I was working with Mark on this in the Quicktype slack channel and he was very helpful.

Also note, this is from an earlier version of Quicktype, so some things have changed since I began implementing it, so if you pull the latest master from the main repo, I imagine some things will break :-)

**Comment by schani** [comment]
@dagrooms52 had also started a Python effort - his code produces nice type annotations: https://github.com/quicktype/quicktype/compare/master...dagrooms52:python-lang

**Comment by dagrooms52** [comment]
Breaking changes kind of killed my efforts (plus first release at my day job, fun!) so I don't think my branch will be extremely usable, but maybe some of it can be helpful like the type annotation bits.

**Comment by SamuelMarks** [comment]
@schani Haven't had the chance to look at it since I got that Node.js memory solution off your Slack. Been busy with my research.

Should have time this weekend to work on it, would welcome input 🙂

**Comment by schani** [comment]
@SamuelMarks I suggest figuring out exactly what the code is you want quicktype to generate first, and then actually making quicktype produce it isn't all that hard anymore, and we can help you with that on Slack, and you can look at existing target languages that do something similar.
