### ISSUE TITLE
Conversion fails if wrong type

### ISSUE THREAD

**Issue by Json-008a** [quicktype/quicktype#2065]
I have a field in my .json which contains (usually) a string.
  "Location": "28",

If this field contains an Int the conversion fails:
  "Location": 28,

How can I modify the generated swift code to  change the int to string?

Thanks
Rolf

**Comment by dvdsgl** [comment]
Your sample should include a case where this field is an int, and quicktype will prepare for both.

**Comment by Json-008a** [comment]
Thank you for your fast answer. I see your point. 
My issue is, that I need a sting in any case. So my idea was to convert the Int to String, by modifying your code. 

Thanks
Rolf
