### ISSUE TITLE
Please provide settings for unsafe dart models

### ISSUE THREAD

**Issue by fajaregafirmansyah** [quicktype/quicktype#2089]
Because my office project has not migrated to null safety when I use this tool, the error is in my IDE.

**Comment by dvdsgl** [comment]
<img width="649" alt="CleanShot 2023-01-09 at 12 23 04@2x" src="https://user-images.githubusercontent.com/108197/211400961-3aa0dfc2-a57b-4c91-ae03-121bee91fdac.png">
