### ISSUE TITLE
Error: Option parsing failed: Unknown option: --check-required. (Json Schema -> C#)

### ISSUE THREAD

**Issue by ChrisRichner** [quicktype/quicktype#2091]
Hi there

Since Version 16.0.11 and newer we face the following issue 

> Error: Option parsing failed: Unknown option: --check-required.

when generating C# Code with the following arguments

> quicktype -s schema schema.json -l csharp -o c:\temp\ --array-type list --check-required

**Comment by bzuidgeest** [comment]
There are now two rendering frameworks, the old newtonsoft and system.text.json. from .net 6. Does the problem go away if you specify which framework you want to use?

**Comment by ChrisRichner** [comment]
Thank you for this suggestion, 

I've tried both frameworks values with latest version 18.0.1 and the error remains eventough the error message is slightly different.

>  Error: Option parsing failed: UNKNOWN_OPTION: Unknown option: --check-required.

**Comment by dvdsgl** [comment]
I bet this is the same as root cause as #2097

**Comment by bzuidgeest** [comment]
@ChrisRichner I am not really done yet, so if you don't need the system.text.json framework option then I would suggest sticking with an older quicktype version for now. Seems the safe option
However, if you are in dire need I made a PR #2104  that I think mostly fixes the problem, but it's not properly tested. 
The check-required option is back, but it's only used by the old newtonsoft renderer. I did not have time to (re)-enable it for the new systemtextjspon renderer.
So use at your own risk. If you could see if it works that would be usefull to me. I would require you being able to build your own version of quicktype though.

**Comment by ChrisRichner** [comment]
@bzuidgeest  Thank you for your effort 💪 I've already pinned the version so that we're up and running until a mitigation is found.

**Comment by ChrisRichner** [comment]
At least the Web Version now shows the options again 👍

![image](https://user-images.githubusercontent.com/7531283/212361707-9db11619-bcfc-4545-9cd1-04f33d69f000.png)

**Comment by bzuidgeest** [comment]
> At least the Web Version now shows the options again 👍
> 
> ![image](https://user-images.githubusercontent.com/7531283/212361707-9db11619-bcfc-4545-9cd1-04f33d69f000.png)

Yes the options are back I pushed a quick fix. The functionality itself was never gone, it was just that the option was not recognized. But as it is the QuickType framework does not support showing options dependent on framework. Therefore the option Check-required at the moment only has a real effect for newtonsoft serialization, but shows for both. 
After taking a quick look there does not seem to be equivalent functionality for the newtonsoft required attribute in system.text.json. Not even in .net 7. Even if you would add a custom attribute, Microsofts serializer would not check it.

If you happen to use the new system.text.json framework or plan to do so in the future, I would not mind to know if you have a workaround for this. If so, maybe I could add it to the system.text.json generator.
