### ISSUE TITLE
just-type option for csharp

### ISSUE THREAD

**Issue by heavenwing** [quicktype/quicktype#2097]
quicktype version 18.0.0
There is no just-type option for csharp, earlier version have `--features just-types`

**Comment by Xzelsius** [comment]
Related to #2091?
Might be caused by #1997

**Comment by bzuidgeest** [comment]
I have checked and the options are still there. lines 1410 en 665 in the charp.ts  The only thing I can think of for this possible regression is that @dvdsgl  made some small changes to the PR before accepting it. One of them modified some export from the way they seem to have been. In this commit https://github.com/quicktype/quicktype/pull/1997/commits/9e8fd131e71ccdd59f0a4038d10fa3821e5a88f4

Maybe that causes the problem, making the option "undetected". The option that's missing is the same for both frameworks, so maybe it needs to be moved to a more common base option set,.

**Comment by bzuidgeest** [comment]
@heavenwing I am not really done yet, so if you don't need the system.text.json framework option then I would suggest sticking with an older quicktype version for now. Seems the safe option
However, if you are in dire need I made a PR #2104  that I think fixes the problem, but it's not properly tested. So use at your own risk. If you could see if it works that would be usefull to me.

**Comment by heavenwing** [comment]
thanks.
I have already used old version now.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: bzuidgeest ***@***.***>
发送时间: Friday, January 13, 2023 6:02:59 AM
收件人: quicktype/quicktype ***@***.***>
抄送: Yongguang Zhu ***@***.***>; Mention ***@***.***>
主题: Re: [quicktype/quicktype] just-type option for csharp (Issue #2097)


@heavenwing<https://github.com/heavenwing> I am not really done yet, so if you don't need the system.text.json framework option then I would suggest sticking with an older quicktype version for now. Seems the safe option
However, if you are in dire need I made a PR #2104<https://github.com/quicktype/quicktype/pull/2104> that I think fixes the problem, but it's not properly tested. So use at your own risk. If you could see if it works that would be usefull to me.

―
