### ISSUE TITLE
Please add previous version dart converter

### ISSUE THREAD

**Issue by nzee098** [quicktype/quicktype#2102]
![image](https://user-images.githubusercontent.com/56812492/211966647-ce97ddd5-dfec-47d2-b5de-b35b5a5a0aec.png)

**Comment by skillseedslimited** [comment]
I think i am experiencing the same error. did quick type do an update? 

how can i solve this problem.

**Comment by nzee098** [comment]
> I think i am experiencing the same error. did quick type do an update?
> 
> how can i solve this problem.

I have a temporary solution to use
https://ashamp.github.io/jsonToDartModel/

**Comment by dvdsgl** [comment]
@RmondJone any ideas?

**Comment by RmondJone** [comment]
> @RmondJone any ideas?

I've been quite busy at work recently, and I've been busy with some personal matters, and I haven't started to modify it yet. When I'm done with my work for a while, I'll do some support, you see?  I will fix all these issues in the next version, please wait for a while.  All minor issues, will be supported soon.

**Comment by RmondJone** [comment]
> ![image](https://user-images.githubusercontent.com/56812492/211966647-ce97ddd5-dfec-47d2-b5de-b35b5a5a0aec.png)
> 

I'll submit a fix to fix this soon, so please bear with me.

**Comment by RmondJone** [comment]
This problem has been fixed. Pay attention to this PR  [#2135 ](https://github.com/quicktype/quicktype/pull/2135)
