### ISSUE TITLE
Dart parser Datetime error

### ISSUE THREAD

**Issue by byemylove203** [quicktype/quicktype#2106]
When the tool generate json parser with Object have datetime, example :  
`insertedAt: json["inserted_at"], `
there will be error when the inserted_at is null, last version of the tools still correct but recently a new updated version corrupted it. 
correct way:  `editedAt: json["inserted_at"] == null ? null : DateTime.parse(json["inserted_at"]),`

**Comment by RmondJone** [comment]
> When the tool generate json parser with Object have datetime, example :  
> `insertedAt: json["inserted_at"], `
> there will be error when the inserted_at is null, last version of the tools still correct but recently a new updated version corrupted it. 
> correct way:  `editedAt: json["inserted_at"] == null ? null : DateTime.parse(json["inserted_at"]),`

I'll submit a fix to fix this soon, so please bear with me.

**Comment by byemylove203** [comment]
Thanks a lot! I'll keep in touch

**Comment by RmondJone** [comment]
This problem has been fixed. Pay attention to this PR  [#2135 ](https://github.com/quicktype/quicktype/pull/2135)

**Comment by byemylove203** [comment]
Thanks a lot. I appreciate the effort!
