### ISSUE TITLE
nixpkgs quicktype package fails to build

### ISSUE THREAD

**Issue by BeneSim** [quicktype/quicktype#2144]
Hey, I already created an issue at the nixpkgs repository https://github.com/NixOS/nixpkgs/issues/211268. I'm the package maintainer of photoprism and currently blocked by the nixpkgs `generate.sh` node2nix script failing at `quicktype` - in particular the subpackages like `quicktype-graphql-input` etc..

I tracked it down to https://github.com/quicktype/quicktype/compare/f347c71e607451804894fe26e04dcdc152ac47a0..20296629979c6c4d783f1b02075da80eb00ba166 and I guess the issue is related to the usage of 'file:..' dependencies https://github.com/quicktype/quicktype/blob/20296629979c6c4d783f1b02075da80eb00ba166/packages/quicktype-graphql-input/package.json#L15.

According to https://docs.npmjs.com/cli/v9/configuring-npm/package-json#local-paths the usage of `file:` is 
> ... helpful for local offline development and creating tests that require npm installing where you don't want to hit an external server, but should not be used when publishing packages to the public registry.

**Comment by dvdsgl** [comment]
@BeneSim thank you–this is fixed in `20.0.26`

**Comment by BeneSim** [comment]
@dvdsgl Thank you for the quick response. It's working again :+1:
