### ISSUE TITLE
dart null safety is not working anymore

### ISSUE THREAD

**Issue by mhdjazmati** [quicktype/quicktype#2147]
when you switch null safety option it does nothing
it still defines the parameters as regular ones not null safe type.

in previes version it was working.

**Comment by dvdsgl** [comment]
It is working. Fields are only nullable if they are actually sometimes null in the sample.

**Comment by RmondJone** [comment]
@dvdsgl  I am wondering whether to add a new attribute to satisfy that all fields can be empty to adapt to different scenarios.

**Comment by dvdsgl** [comment]
Isn't that this?

![image](https://user-images.githubusercontent.com/108197/215108879-f1d84a53-a425-4b48-ab49-580612412c40.jpeg)

**Comment by RmondJone** [comment]
> Isn't that this?

OK， I thought there was no such attribute
