### ISSUE TITLE
Java - Enums should be nested inside the calling class

### ISSUE THREAD

**Issue by tonyobanon** [quicktype/quicktype#2148]
Enums referenced by a class should be nested as a public static class inside the class itself. Instead of creating a separate file to contain the enum class - which in fact messes up the namespace.

**Comment by dvdsgl** [comment]
What would you expect to happen if many classes use the enum type?

**Comment by tonyobanon** [comment]
If many classes use the same enum type, a new file can would need to be created in that case. But I should also mention - that scenario is the exception not the rule.

**Comment by dvdsgl** [comment]
How does this mess up the namespace? Is this a bug or a style preference?

**Comment by tonyobanon** [comment]
It is a bug, not a style preference

```
{
  "id": "http://json-schema.org/geo",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "A geographical coordinate",
  "type": "object",
  "properties": {
        "o": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "string",
                    "enum": ["a", "b"]
                }
            }
        },
        "p": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "string",
                    "enum": ["a", "b", "c"]
                }
            }
        },
        "p_lat": {
            "type": "object",
            "properties": {
                "b": {
                    "type": "string"
                }
            }
        },
        "plat_enum": {
            "type": "object",
            "properties": {
                "b": {
                    "type": "string"
                }
            }
        }
    }
}
```

In the above schema, we end up with two class files with identical names: "PLatEnum.java" and "PlatEnum.java". Some operating systems (including MacOS ) have case insensitive file names, so in this case writing the second file to disk will fail

**Comment by dvdsgl** [comment]
@tonyobanon this is completed?

**Comment by tonyobanon** [comment]
After some review, I made the determination that the above "supposed" bug will likely never happen in the real world. I say this because I crafted the schema above to counter quicktype heuristics. And for this reason, I will be closing this issue.
