### ISSUE TITLE
Need @jsonKey(name: "") keyword feature in dart for freezed compactability. 

### ISSUE THREAD

**Issue by abinvs-2019** [quicktype/quicktype#2162]
When using a json model which contains spaces or capital letter in json, need this keyword for freezed to generate the class with the correct spelling,

For example:
`   "Semester Details": [
            {
                "Semester Name": "Semester1",
                "Semester Amount": "100000"
            },
            {
                "Semester Name": "Semester2",
                "Semester Amount": "120000"
            },`

This json has capital named variable, which is "Semester Details" which has space also,
so,
`Freezed will generate the class like this:
  const factory SemesterDetail({
        String? semesterName,
        String? semesterAmount,
    }) = _SemesterDetail;`
which will generate class in the name name as the variable name,

so adding @jsonKey(name: "") can override the naming of the variable ,
for eg:
`  const factory SemesterDetail({
    @JsonKey(name: 'Semester Name') String? semesterName,
    @JsonKey(name: 'Semester Amount') String? semesterAmount,
  }) = _SemesterDetail;`

which would generate the json parsing function as the name given in the keyword.

**Comment by armanate** [comment]
I think this feature is very needed, my json does have a long list of properties, and it takes a long time to add these jsonkey annotations myself. please add this feature.

**Comment by linhmanh92** [comment]
I also have a case where my data is underscore and when it comes to dart I want it to be camelCase using JsonKey.

**Comment by rizerzero** [comment]
I also use underscores and this causes each time an issue because it's converted to camelCase.

**Comment by kvnxiao** [comment]
This will be fixed by https://github.com/quicktype/quicktype/pull/2348

**Comment by abinvs-2019** [comment]
Closing this considering the PR! #2348
