### ISSUE TITLE
C++ Codegen - throw std::exception& instead of const char*

### ISSUE THREAD

**Issue by SimonCahill** [quicktype/quicktype#2166]
Reviewing an internal PR, I noticed that Quicktype generates C++ code that throws `const char*` as exception types.
While this is technically allowed by the language, code **shouldn't** throw built-ins, but **should** throw objects derived from `std::exception`!

Some more information can be found here:
[isocpp.org](https://isocpp.org/wiki/faq/exceptions)
[StackOverflow](https://stackoverflow.com/a/6249350/2921426)

The reasoning behind throwing "complex" types are as follows:
 - as code evolves, it may become necessary to expand on the error
 - programmers generally except well-known types to be thrown (`catch (const std::exception& ex)` is not a rare sight!)

The best option would be to implement a custom `quicktype_error` or `parse_error` for the schemas and then have it contain the error information.

An example of generated code would be:

```cpp
#include <exception>
#include <string>

namespace foo {
    class quicktype_error: public std::exception {
        public:
            quicktype_error(const std::string& msg, /*other related info*/): exception(), m_error(msg) {
                // ???
            }

            const char* what() override { return someFuncToGatherAllErrorInfo().c_str(); }

        private:
            std::string m_error;
            /* other related info */
    };
}
```

**Comment by dvdsgl** [comment]
Sounds good! Please consider a PR that changes this.

**Comment by SimonCahill** [comment]
I'll try. I'll admit I'm having a hard time finding my way around the sources and (appropriately) adding things.
So far I've created a branch that'll simply throw `std::runtime_error`, but no custom exceptions. Haven't quite figured that one out yet
