### ISSUE TITLE
Test file 76ae1.json with duplicated item make test failing

### ISSUE THREAD

**Issue by joelguittet** [quicktype/quicktype#2197]
Hello,

The file 76ae1.json has a duplicated entry, which to me should be incorrect json. Can you confirm ?
Duplication is at https://github.com/quicktype/quicktype/blob/master/test/inputs/json/misc/76ae1.json#L1665, "topic" element is provided twice.

I have notice this make my test failing (working on cJSON implementation), and I see several language skip this file, maybe for this reason ?

I can do a PR but first I would like to have a confirmation. Thanks.

Joel

**Comment by joelguittet** [comment]
@dvdsgl maybe you can help here ?

**Comment by dvdsgl** [comment]
Fine to remove! Good catch.

**Comment by joelguittet** [comment]
Thanks for the reply, done at https://github.com/quicktype/quicktype/pull/2203!

**Comment by joelguittet** [comment]
PR merged, closing.
