### ISSUE TITLE
Templating from types

### ISSUE THREAD

**Issue by tonysneed** [quicktype/quicktype#223]
It would be nice to be able to customize generated output, similar to how T4 templates are used to customize code gen in Visual Studio.  For example, if you have a class used in two-way data binding,  you need to implement INotifyPropertyChanged, which you can do in a base class.  The trick, however, is that you need to fire the event in the setter of each property in the class.

```csharp
public class Person : EntityBase
{
    private string _name;
    public string Name
    {
        get { return _name; }
        set
        {
            _name = value;
            NotifyPropertyChanged(nameof(Name));
        }
    }
}
```

This is just one example of how one might like to customize code generation.  T4 templates allow for this, but they are tied to Visual Studio.  Another option could be something like Yeoman.  Or there could be a hook that accepts a callback, allowing for the strategy pattern.

**Comment by dvdsgl** [comment]
Perhaps someday we could allow some optional template-style customization with [handlebars](http://handlebarsjs.com/) or a similar, simple syntax that works for all languages:

```csharp
private {{type}} _{{name}};
public {{type}} {{Name}}
{
  get { return _{{name}}; }
  set
  {
    _{{name}} = value;
    NotifyPropertyChanged(nameof({{Name}}));
  }
}
```

**Comment by schani** [comment]
I think what we need for this to work and to be more generally applicable is the ability to add arbitrary data to nodes in the type graph.  This data can come from several sources:

1. The naming system, aided by the target language, adding in the names for types and properties in the code to be generated.

2. The target language, adding the stringified types to each IR type.  Figuring these out is often pretty complex, so it would be a burden to generate those via the templating system.

3. The user, who could specify their own attributes to be used in templates, but who could also override defaults, such as class names.  Those could be given either in a configuration file or, ideally, in a schema file.

This would open the door to a whole range of interesting applications, even allowing the template-based generation of whole data-displaying apps.

**Comment by schani** [comment]
We built [a prototype](https://github.com/quicktype/quicktype/blob/master/doc/Templates.md) for this a while ago.  It didn't go anywhere, and we have a way to extend quicktype through code now, so I'll close this.

**Comment by alexandreos** [comment]
Hi @schani, it would be awesome to have this [prototype](https://github.com/quicktype/quicktype/blob/master/doc/Templates.md) back. I'm interested in generating custom Swift models and having a template file would make it much easier to adopt in my current project.

Thank you
