### ISSUE TITLE
Adding a close button

### ISSUE THREAD

**Issue by abelardolg** [quicktype/quicktype#2235]
When I zoom in, this panel annoys
![image](https://user-images.githubusercontent.com/22522883/230338136-0e3a434e-a9c8-44f7-9e9c-8a2d9291eb9d.png)

Would you mind to put a close button, please? Thanks.

**Comment by catgirlinspace** [comment]
The options button in the top right closes it. 

Maybe to make this more clear a little arrow should be added pointing from the panel to the options button? Something like what GitHub shows when hovering.
<img width="114" alt="image" src="https://user-images.githubusercontent.com/13684891/230702850-9e506412-3928-4849-80b0-ff43813ec45b.png">
