### ISSUE TITLE
Option to output JSON attributes, but no convenience methods/classes

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype#227]
From klaus on Intercom:

I just don't need the convenience methods for what I am doing (rest API stuff), because RestSharp takes care of allt that stuff for me. And since I don't need them, I would much prefer not to have the convenience methods - as well as the classes not being partial.

**Comment by schani** [comment]
We currently have the `--just-types` option, which leaves out everything.  I see two main ways to introduce this:

1. Have two boolean options, one toggling `JsonAttribute`s, the other one toggling convenience methods.

2. A single enum option with three choices: 1. Everything, 2. Only `JsonAttributes`, 3. Pocos only.

I dislike the two boolean options, because it allows the choice of convenience methods without `JsonAttribute`s, which doesn't really make sense.  I shall therefore implement the enum option in the new TS C# renderer.

**Comment by sixfootfour** [comment]
Sounds like the right solution to me.

**Comment by schani** [comment]
There's one problem: When you have unions, you need the `Converter` class to serialize/deserialize them, so in that case I'll still generate that.

**Comment by sixfootfour** [comment]
I am not even sure what a union is in this context. Could you point me to a link?

**Comment by schani** [comment]
This is now implemented in the TypeScript renderer branch: #228

**Comment by schani** [comment]
A union is the type we produce when an array contains values of more than one type, for example in

    { "foo": [123, true, "bar"] }

For more details, see my [internals blog post](http://blog.quicktype.io/under-the-hood/).

**Comment by dvdsgl** [comment]
If you're already successfully using RestSharp with POCOs, you probably don't have unions in your model. quicktype emits union types when the sample JSON contains heterogeneous data.
