### ISSUE TITLE
Incorrect TypeScript interface when using const with boolean value

### ISSUE THREAD

**Issue by alan-agius4** [quicktype/quicktype#2325]
Using `const` with a non string value will produce incorrect TypeScript type definitions.

Schema
```json
{
    "id": "http://json-schema.org/geo",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type": "object",
    "properties": {
      "foo": {
        "oneOf": [
          {
            "type": "string",
          },
          {
            "const": false
            "type": “boolean”
           }
        ]
      }
    }
  }
```

Output
```ts
export interface Person {
    foo?: string;
    [property: string]: any;
}
```

Note: this used to work up until a recent release.

```
quicktype-core version: 23.0.54
```

**Comment by DanielBretzigheimer** [comment]
I can confirm your issue, it is caused by my change in #2314. But I think this didn't work correctly before.

The result before my change was:
```ts
export type Person = {
    foo?: boolean | string;
    [property: string]: any;
}
```

But the expected result for your example is:
```ts
export type Person = {
    foo?: false | string;
    [property: string]: any;
}
```

Do you think the same? I will start working on a bug fix, thanks for pointing this out.

**Comment by DanielBretzigheimer** [comment]
@alan-agius4 the PR was merged. Is the bug now fixed for you? If so, the ticket can be closed

**Comment by alan-agius4** [comment]
Thanks that fixes it.
