### ISSUE TITLE
Converter class conflicts when invoking quicktype multiple times independently for separate samples

### ISSUE THREAD

**Issue by neilw73** [quicktype/quicktype#276]
Hello,
Not entirely sure if this is a fault, but when you generate the code for a couple of separate classes it fails to compile because the Serialize class generated is static and so you end up with multiple static classes of the same name. Similarly the same happens for the Converter. Typically these will all be in the same namespace.

The Java version seems a bit neater (although uglier) because everything is within one class, Converter that can simply be renamed.

I'm also a bit stuck as to why ToJson is in it's own static class but FromJson is part of the data class. If it were in the data class then this wouldn't be an issue and the only thing remains to do is simply put Convert into it's own file.

**Comment by neilw73** [comment]
btw, I put ToJSon, FromJson and the class Converter all within the partial class and everything works fine. Is there a reason for not doing this?

public sealed partial class ClassDO
    {
        public static List<ClassDO> FromJson(string json)
        {
        }

        public static string ToJson(List<ClassDO> self)
        {
        }

        public class Converter
        {
            public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
            {
            };
        }

    }

**Comment by neilw73** [comment]
A bit inefficient, according to a post I put on stackoverflow:

public class StationDO {
    public string Active { get; set; }
}

public class AnotherDO {
    public string Name { get; set; }
}

// and more *DO classes

// class need to be "static" because contains "extension methods"
public static class MySerializationHelper {
    private static readonly JsonSerializerSettings serializationSettings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
        };

    // universal method for deserialization from json
    // the generic type "T" represents the result type of deserialization
    public static T FromJson<T>(string json) {
        return JsonConvert.DeserializeObject<T>(json, serializationSettings);
    }

    // universal method for serialization to json
    // this "this" keyword means, its "extension method"
    public static string ToJson<T>(this T self) {
        return JsonConvert.SerializeObject(self, Converter.Settings);
    }
}

**Comment by dvdsgl** [comment]
If you generate code for multiple samples according to our official guidance, you will avoid these issues: https://www.youtube.com/watch?v=K6bmaLpS0oo

**Comment by dvdsgl** [comment]
* It's a good idea to put ToJson in the partial class instead of in the static extension class.
* It's also reasonable to repeat the static `JsonSerializerSettings` in each top-level partial class, rather than a `Converter` class with a fixed name, although this is a bit more work.

**Comment by dvdsgl** [comment]
Ah, I think the reason that `ToJson` is not in the partial classes is that sometimes this must be an extension method when the top-level type is not a class.

**Comment by dvdsgl** [comment]
@neilw73 we don't have good docs for the feature in the YouTube video, but I'm working on a blog about it now. In case this helps, here's a diagram I'm also working on:

<img width="1025" alt="frame" src="https://user-images.githubusercontent.com/108197/32918058-1900b5e2-caef-11e7-96b8-87de05f80ac3.png">

**Comment by schani** [comment]
There are two ways now to avoid this problem:

1. Do everything in one invocation of quicktype, like @dvdsgl described.

2. Use a different namespaces for each invocation, with the `--namespace` option.

**Comment by dvdsgl** [comment]
I still plan to address this someday.
