### ISSUE TITLE
g++ exits code 4 on combinations.json

### ISSUE THREAD

**Issue by dagrooms52** [quicktype/quicktype#291]
## Bug Report
Tests fail in unedited Docker container from clean head of master branch.

## Commands

```shell
$ docker build -t quicktype .
$ docker run \
    -e "FIXTURE=cplusplus" \
    -t quicktype npm test -- test/inputs/json/priority/combinations.json 
```

## Output

```
...
* [131/160] golang {} test/runs/golang-2cc40e/reddit.json

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.

Command failed
{
  "command": "g++ -O0 -o quicktype -std=c++14 main.cpp",
  "code": 4,
  "cwd": "/app/test/runs/cplusplus-1e5d83"
}
Fixture threw an exception
{
  "error": {
    "command": "g++ -O0 -o quicktype -std=c++14 main.cpp",
    "code": 4,
    "cwd": "/app/test/runs/cplusplus-1e5d83"
  },
  "cwd": "/app/test/runs/cplusplus-1e5d83"
}
[object Object]
    at /app/test/test.ts:73:17
    at step (/app/test/test.ts:32:23)
    at Object.throw (/app/test/test.ts:13:53)
    at rejected (/app/test/test.ts:5:65)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
npm ERR! Test failed.  See above for more details.
```

--- 

I would suggest binding the specific software versions installed in the docker container to give consistent build and test results. [This SO answer](https://askubuntu.com/questions/428772/how-to-install-specific-version-of-some-package/428778) shows how to do so. I also noticed that the container is built from a base Ubuntu image; I'm sure there are many node.js or typescript base images that can be used as a cleaner base image instead. 

I'm happy to help resolve this issue if anyone can provide the software versions necessary to be installed in the docker container; I've spent a lot of time doing similar fixes on other projects, and I'm looking for a good place to start contributing to this project.

**Comment by dvdsgl** [comment]
The C++ compiler is exiting with code 4 on the `test/inputs/json/priority/combinations.json` sample:

```bash
docker run \
  -e "FIXTURE=cplusplus" \
  -t quicktype npm test \
  -- test/inputs/json/priority/combinations.json 
```

@dagrooms52 if you create a `python` test fixture, you can run it in the Docker container with:

```bash
$ docker run -e "FIXTURE=python" -t quicktype npm test
$ FIXTURE=python npm test # run without Docker
```

**Comment by dvdsgl** [comment]
Our container also pulls in dependencies for Java, Swift, .NET, Elm, Go, C++, etc., which is why we use a base Ubuntu image rather than a node image.

**Comment by schani** [comment]
@dagrooms52 Could it be that you're running out of memory?  The C++ compiler takes forever and consumes an ungodly amount of memory on the `combinations.json` sample.

**Comment by schani** [comment]
If this blocks you, you can also just disable that specific file for C++ by adding it to the `skipJSON` property in its test language definition [here](https://github.com/quicktype/quicktype/blob/master/test/languages.ts#L98).

**Comment by dagrooms52** [comment]
I doubt it's a memory issue, I have 16GB and this is the lowest memory reading I got out of `top` while running the tests:

`PhysMem: 11G used (2618M wired), 5390M unused.`

**Comment by schani** [comment]
You can see which compiler version we're using in the [build logs](https://travis-ci.org/quicktype/quicktype/jobs/307029468).  The relevant lines:

```
Get:92 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libstdc++-5-dev amd64 5.4.0-6ubuntu1~16.04.5 [1430 kB]
Get:93 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 g++-5 amd64 5.4.0-6ubuntu1~16.04.5 [8435 kB]
Get:94 http://archive.ubuntu.com/ubuntu xenial/main amd64 g++ amd64 4:5.3.1-1ubuntu1 [1504 B]
```

**Comment by schani** [comment]
I can definitely confirm it's a memory issue.  If I assign 16GB to Docker then it works, if I assign 2GB I get the exact error you get.  It's not about how much memory your machine has, but about how much you give to Docker.

**Comment by dagrooms52** [comment]
I didn't consider Docker memory, sorry about that but at least we got to the bottom of it! That compiler really does eat up a lot of memory.

**Comment by schani** [comment]
Yes, it's unfortunate.  If you're just interested in implementing Python support there's really no reason to run C++ tests, unless you have to change some infrastructure that's required for implementing Python.  And as I said, you can always just disable that particular one.

Please let us know if you need any help with Python.  You might want to [join us on Slack](http://slack.quicktype.io/) for more efficient discussion.
