### ISSUE TITLE
Translate irregular TypeScript property names to names that support dot access

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#296]
`interface Foo { "bar baz": number; }` is tedious to use because it requires you to write `foo["bar baz"]` rather than `foo.barBaz`.

**Comment by schani** [comment]
This would require rewriting the JSON object, right?  And we would also have to do the reverse transformation, for producing JSON.  We could do this in two ways:

* Leave the objects as plain objects, which means we'd still generate interfaces for them, and we could use the original JSON objects wherever changes are not necessary, i.e. we'd save on computation time and memory.

* Translate everything into proper TypeScript classes.  That might give us more flexibility for more advanced features later, at the cost of speed and memory at deserialization time.

**Comment by dvdsgl** [comment]
Yes, I'd like to output a map from JSON property names to TypeScript-safe property names, and rewrite the JSON objects. This should be pretty efficient since we can mutate the value returned by `JSON.parse`.

**Comment by schani** [comment]
We don't get the object's context in the tree from `JSON.parse`, though, do we?  How an object is supposed to be transformed will depend on what type it is.

**Comment by schani** [comment]
This is done, with `--nice-property-names`, off by default.
