### ISSUE TITLE
Language request: Rust

### ISSUE THREAD

**Issue by Phrohdoh** [quicktype/quicktype#300]
The documentation for [primitives](https://doc.rust-lang.org/std/#primitives) combined with [containers and collection](https://doc.rust-lang.org/std/#containers-and-collections) should provide all that is needed for a basic syntax output.

A few notes:

Nullable fields want to be `Option<T>` assuming the type is known (otherwise `Option<_Unknown>` may serve as a good indicator that the type of the contained data is unknown).

Rust has `struct`s not `class`es.

General syntax is:

```rust
struct Foo {
    bar: Bar,
    baz: Option<Baz>,
    quxs: Vec<Qux>,
    some_number: i32,
    url: String,
}
```

**Comment by dvdsgl** [comment]
And how is JSON parsed in Rust?

**Comment by Phrohdoh** [comment]
Ah yes that would have been smart of me to include.

The de-facto library for de/serialization is [serde](https://serde.rs/).

You can see a struct annotated with the proper attributes [here](https://serde.rs/#data-structures) (Serialize and Deserialize).

If a field needs to be renamed (for example `type` is a Rust keyword so a field cannot be named `type`) you can do this:

```rust
struct Foo {
    #[serde(rename = "type")] // The string here is the name in the JSON being parsed.
    kind: SomeTypeHere
}
```

**Comment by schani** [comment]
@Phrohdoh Please consider contributing Rust support.  I made a series of videos where I show how I implement the C++ target language: https://www.youtube.com/watch?v=bNJeMb6brQE&list=PL_xkZVfmktNxmTSDZUQA46gKSqG8nqIcM

**Comment by dvdsgl** [comment]
Our C# renderer is very similar to this, since it also uses annotations. Would you be willing to duplicate that renderer and modify it to output Rust?

**Comment by Phrohdoh** [comment]
You are welcome to assign this to me as I am interested in seeing this through but I am also very busy so cannot promise results anytime soon.

**Comment by Dr-Emann** [comment]
I think this is done as of #512

**Comment by dvdsgl** [comment]
Thanks @Dr-Emann !
