### ISSUE TITLE
Make a homebrew package

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype#330]

**Comment by dvdsgl** [comment]
Looks like this can still be based on `npm install`: https://github.com/IBM-Swift/homebrew-kitura/blob/master/kitura.rb

**Comment by schani** [comment]
I'm down with that.  People like `brew` because it's standardized, easy, and hides the details.  If it's NPM underneath, whatever.

**Comment by dvdsgl** [comment]
Yes, sounds right to me. It's nice to see that there's a standard way to distribute npm tools in homebrew that doesn't involve implicitly bundling a copy of node.

**Comment by dvdsgl** [comment]
Submitted: https://github.com/Homebrew/homebrew-core/pull/21613

**Comment by dvdsgl** [comment]
Merged
