### ISSUE TITLE
Compare features with JSONExport

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#350]
https://github.com/Ahmed-Ali/JSONExport

There may be some interesting ideas to borrow!

**Comment by schani** [comment]
It has many options for output, and potentially interesting ideas in templating, but it doesn't handle most non-trivial cases:

* Detect which properties are optional - it makes them all either required or all optional.

* Doesn't rename properties that clash with keywords, or at least not all.

* Removes spaces in property names where they're used to index the JSON objects.

* No unions, i.e. heterogenous arrays become arrays of `AnyObject`

* Doesn't handle the case where more than one property name map to the same Swift name.  i.e. it will only generate one `foo` property for an object containing `foo`, `Foo`, and `_foo`.
