### ISSUE TITLE
Expedite our tests

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#372]
Our suite takes over an hour again, so we end up doing almost 3 hours of testing to release a PR.

We get very little advantage from our test parallelism right now. I'd like to use Travis to launch our tests on high-core AWS instances with per-second pricing to get our runs under 15 minutes.

**Comment by dvdsgl** [comment]
I also would like to specialize PR tests to only test changed languages.

**Comment by schani** [comment]
For some target languages, like Java and C#, we spend a huge amount of time compiling and starting the runtime.  What if we emitted the code for all tests at once, using separate namespaces, and compiled them all in one go into a combined executable that can then read and process all inputs in one run?  We could save additional time by only generating the IR for each test once and using it to render code for all target languages.
