### ISSUE TITLE
String type equality is broken

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#380]
The Swift test suite started timing out on Travis. I narrowed it down to the test on `test/inputs/json/misc/ed095.json`, which contains a `[String: String]` that now is generated as a struct with 1.5k fields. This stalls the swift compiler indefinitely. Something about the nullability test in `shouldBeMap` is invalid now.

Run this stalled test with:

```bash
FIXTURE=swift npm test -- test/inputs/json/misc/ed095.json
```

**Comment by dvdsgl** [comment]
I created a branch with a failing test: https://github.com/quicktype/quicktype/pull/382

**Comment by dvdsgl** [comment]
https://github.com/quicktype/quicktype/blob/master/src/Language/Swift.ts#L415

Swift's `dense` mode groups contiguous fields of the same type, but `String` types are no longer considered equal. I guess this the same issue, and that the more specific bug is that `String` types are no longer considered equal, which is why `Map<String, T>` where `T != String` is still inferred.

**Comment by schani** [comment]
Correct.  I'll have it fixed soon.
