### ISSUE TITLE
quicktype doesn't work on this sample data

### ISSUE THREAD

**Issue by IanLeatherbury** [quicktype/quicktype#385]
[coins.json.zip](https://github.com/quicktype/quicktype/files/1594673/coins.json.zip)

`quicktype` does not return when invoked on this sample.

**Comment by schani** [comment]
It will return eventually, it's just really slow.  That's a result of the late enum inference changes.  I'll have a quick workaround soon, and a proper solution somewhat later.

**Comment by schani** [comment]
@IanLeatherbury  If you need it right now, you can use [release 7.0.0](https://github.com/quicktype/quicktype/releases).
