### ISSUE TITLE
String property with name "url" produces incorrect code

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype#409]
```
{
    "url": "abc"
}
```

The generated `struct` has an implicit initializer `init(url: String)`, but we generate an extension with an initializer `init?(url: String)`.

The easiest way to avoid this is to just disallow `url` for property names.  I'm baffled that not a single one of our test cases has such a property.

**Comment by schani** [comment]
Well, actually, the `recursive.json` test case has such a property, which is how I found it, except that it was disabled for Swift because it doesn't handle recursive types yet.

**Comment by dvdsgl** [comment]
Yowza.
