### ISSUE TITLE
Option for access control in Swift

### ISSUE THREAD

**Issue by dkcas11** [quicktype/quicktype#430]
It would be extremely helpful to choose whether to use access modifiers such as `public` and `internal` when using Quicktype in the browser, especially when dealing with large models.

Thanks anyway, works great.

**Comment by dvdsgl** [comment]
Can you please give more detail? Do these modifiers apply to the types? Properties? Samples would be really helpful! Thank you!

**Comment by dvdsgl** [comment]
Also, we're an open source project and you could straightforwardly add this feature and send us a PR if you're interested.

1. Add an option to `Swift.ts` (example: [feature option](https://github.com/quicktype/quicktype/blob/master/src/Language/Swift.ts#L59-L62))
1. [Pass the option](https://github.com/quicktype/quicktype/blob/master/src/Language/Swift.ts#L68-L73) to the [`SwiftRenderer`](https://github.com/quicktype/quicktype/blob/master/src/Language/Swift.ts#L223-L230).
1. Emit the access modifiers where you want them, probably in [`renderClassDefinition `](https://github.com/quicktype/quicktype/blob/master/src/Language/Swift.ts#L396).
