### ISSUE TITLE
Swift convenience initializers should not swallow exceptions from JSONDecoder.decode

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#462]
See discussion at #461 

cc @yoloabdo

**Comment by Yoloabdo** [comment]
Awesome, thank you!

**Comment by dvdsgl** [comment]
@Yoloabdo all fixed, let me know how it goes!

**Comment by Yoloabdo** [comment]
Looks good, but there's failable inits and it has throw too, it shouldn't have failable anymore I guess

**Comment by Yoloabdo** [comment]
for url init I'd suggest to stick with throw 
`        guard let data = json.data(using: encoding) else { throw URLError.badURL }`

**Comment by dvdsgl** [comment]
Would you like to try to implement it? 😄

**Comment by Yoloabdo** [comment]
Sure, let me give it a try 💃 😄
