### ISSUE TITLE
CLI very slow

### ISSUE THREAD

**Issue by SurushS** [quicktype/quicktype#480]
I'm just wondering whether it is normal behavior that a built quicktype takes around 15-20 seconds to actually generate a class from a json file. Is this normal behavior and if so, is it because of all the dependencies? I'm trying to generate C# classes with json schema's as input and its really slow.

**Comment by dvdsgl** [comment]
Could you share your schema with us? What is the file size at least? This is very slow for JSON schema input.

I don't think it's the dependencies—quicktype has relatively few.

**Comment by schani** [comment]
If you just invoke `quicktype` without any options, how long does that take?

**Comment by SurushS** [comment]
When invoking QuickType without parameters it takes ages. Doesn’t matter with or without so my guess was something in the initialization of QuickType

**Comment by schani** [comment]
How did you install quicktype? Via NPM?

**Comment by dvdsgl** [comment]
What version of node and what OS?

**Comment by SurushS** [comment]
i run it in my own container and basically followed the readme on github to install. node version v8.9.4 and its a container running ubuntu version 16.04 LTS

**Comment by SurushS** [comment]
also ran quicktype through NPM yes

**Comment by dvdsgl** [comment]
Can you please give us much more information? What is the host OS? Docker version? Host RAM? Docker RAM?

**Comment by SurushS** [comment]
Well actually I’m running it in AKS (Azure managed Kubernetes environment) with no restrictions set on resources on Docker level. The Nodes that it is running on are standard Dv3 vms on azure (standard on AKS).

**Comment by SurushS** [comment]
It’s running on a self hosted VSTS Agent which in turn uses Ubuntu as its base image. This it the [link](https://github.com/microsoft/vsts-agent-docker/blob/73feb90e95a85a8592776c9dfeffc0bfb5461e0c/ubuntu/16.04/docker/17.06.0-ce/standard/Dockerfile)

**Comment by SurushS** [comment]
The environment doesn’t affect it though. I have the same issue running the same container locally on my i7 32GB desktop with all the default preinstalled Docker settings

**Comment by dvdsgl** [comment]
`appcenter-cli` is a similar JavaScript CLI on `npm` — what do you get for `time appcenter help`?

**Comment by SurushS** [comment]
![qtype1](https://user-images.githubusercontent.com/35565295/35723762-c5e7da6c-07fb-11e8-9d13-eb8948c3115f.PNG)
![qtype2](https://user-images.githubusercontent.com/35565295/35723763-c5ff6f1a-07fb-11e8-9bbe-1058e5a1eac9.PNG)

**Comment by SurushS** [comment]
i have the same issue if i get your docker image from the hub and try it locally or on Azure. It takes between 12-15 seconds to show the help. Appcenter though, both on my own created image as well as your own docker image shows help instantly.

**Comment by dvdsgl** [comment]
I see the problem. This is not how you run quicktype. For some reason you are running our development script that reinstalls dependencies and compiles quicktype whenever you run it, as least in these screenshots.

Here is how to run quicktype:

```bash
$ npm install -g quicktype 
$ quicktype
```

Or to run from source, which you appear to be doing:

```bash
$ npm install # build quicktype 
$ node dist/cli.js
```

How did you come to use quicktype this way? What are you trying to do with quicktype? Perhaps I can suggest a better way to run it as a local npm dependency.

**Comment by SurushS** [comment]
I basically want to use it to generate C# poco classes based on Json or json schema input through cli on my vsts Agent. That’s the goal. What would be the best approach to do that? Simply download and install the npm package and run it on the Agent in your first example ?

**Comment by dvdsgl** [comment]
Yes, install it as a global dependency with `npm install -g` — I don't see any reason for you to build it from source.

Is it fast now? 😄

**Comment by SurushS** [comment]
yeah. it's fast now. from the source out, i was looking on the wrong place apparently. I overlooked the cli.js and went straight to the quicktype script. Thanks for the quick reply! 👍
