### ISSUE TITLE
Swift emits duplicate types for multiple top-levels

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#497]
Discovered in [typeguard/typed-spotify/swift4/spotify.swift](https://github.com/typeguard/typed-spotify/blob/master/swift4/spotify.swift#L65). This is the output of quicktype generating types for multiple top-levels.

The same duplication is not present in [typeguard/typed-spotify/types/spotify.txt](https://github.com/typeguard/typed-spotify/blob/master/types/spotify.txt).

**Comment by dvdsgl** [comment]
Also happens in the Objective-C output:

![image](https://user-images.githubusercontent.com/108197/35782674-62f7660a-09b0-11e8-837e-45db9c45cde5.png)

**Comment by dvdsgl** [comment]
It appears that `ConvenienceRenderer.forEachNamedType` will iterate over multiple instances of types that are unified between top-levels.

**Comment by dvdsgl** [comment]
The Spotify API requires OAuth, and that code is generated from JSON that is cached across `quicktype` invocations (`quicktype.sh` is an example script, and not actually used).

**Comment by dvdsgl** [comment]
I'll get ahold of the JSON and attach it here.

**Comment by schani** [comment]
Please add it to the repo.

**Comment by dvdsgl** [comment]
I don't think we can host that data.

**Comment by schani** [comment]
Oh right, damn.

**Comment by schani** [comment]
I think we should have a JSON anonymizer.  We talked about this in the context of allowing users to send us anonymized JSON, and it would come in handy here, too.

**Comment by dvdsgl** [comment]
In the case of these generated repos, I think we should infer the schema and store that eventually.. I think it would be uncontroversial to store the schema rather than the data...

**Comment by schani** [comment]
You did run quicktype with the JSON as input, not the Schema, right?

I can't reproduce the bug with a trivial test case, so there must be some special circumstance in the data.

**Comment by dvdsgl** [comment]
Here is the Spotify JSON: [spotify.zip](https://github.com/quicktype/quicktype/files/1694084/spotify.zip)

**Comment by schani** [comment]
I cannot reproduce this on master, neither with Swift, nor with Objective-C.  This is how I invoke quicktype:

```
./script/quickertype --lang objc ~/Downloads/spotify/*.json
```

**Comment by dvdsgl** [comment]
Unzip `spotify.zip` and do `./script/quickertype --lang objc ~/Downloads/spotify`.

**Comment by schani** [comment]
Oh yes, darn.  It only did a single top-level.  I can reproduce it now.
