### ISSUE TITLE
Rust improvements

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#516]
- [x] Fix invalid JSON in header comments
- [ ] Optionally emit top-level marshaling functions
- [x] Improve header comments
  - [x] Only show how to deserialize JSON (no need to show going back to string)
  - [x] Don't use extra empty lines between statements
  - [x] Use actual top-level type names in sample
- [x] Optionally omit redundant rename attributes when property name and JSON name match (dense mode)

cc @krk @Phrohdoh

**Comment by Phrohdoh** [comment]
The invalid JSON mentioned is [here](https://github.com/quicktype/quicktype/blob/67635a6feb8af2fc11369bdf1a2ff4e4cc003295/src/Language/Rust.ts#L310) and should be `let json = r#"{"answer": 42}"#;`.

**Comment by dvdsgl** [comment]
@Phrohdoh would you like to submit a PR to improve the header comments? There's a lot of easy wins there.

**Comment by Ryman** [comment]
To add: 
- The serialization code part isn't copy-pasteable currently as it imports `serde_json` but that part actually requires `serde_derive`. It would work if they copied *all* of the code though so maybe that's okay, but I imagine some people may not know that they need to import `serde_derive` in their library code. [Playpen example of it compiling with the change](http://play.integer32.com/?gist=0c2c1aa09c612ce25797972b6b05b07b&version=stable)
- It looks like the header comment improvements can be ticked off

I'd submit a patch for the first point myself but when I cloned the repo and tried running tests without modification they took *way* too long on my machine (with only the rust fixtures). Unsure if that's a problem with my configuration or not but thought it's worth mentioning.

**Comment by dvdsgl** [comment]
@Ryman `FIXTURE=rust npm test` will generate and test a couple hundred Rust programs. Do individual tests take longer than expected or the entire test suite or both?

**Comment by schani** [comment]
@dvdsgl Is it possible that we're downloading and re-compiling all Rust dependencies for each test case?

**Comment by Ryman** [comment]
> @Ryman FIXTURE=rust npm test will generate and test a couple hundred Rust programs. Do individual tests take longer than expected or the entire test suite or both?

It was the entire rust test suit afaik, the first 4 or so tests ran... relatively quick then 20 or so more would take many many minutes more, I don't have access to my laptop where I can run it right now to check though. It definitely felt like it was compiling more than necessary.

**Comment by dvdsgl** [comment]
@Ryman the test slowness is fixed now

**Comment by Ryman** [comment]
@dvdsgl Hey, sorry for the delay, I looked into the compile times a little and some of your generated types, when passed to serde are creating 40k+ lines of code (post macro expansion, try using `cargo-expand` if you want to see) with 30k of them being in a single method which rustc chokes badly on in `translation` (you can see this on a nightly compiler by setting `RUSTFLAGS=-Ztime-passes`. I had hoped to look into improving the codegen for serde and it seems to be a known problem on the issue tracker but I haven't been successful this week. 

I'd advise that you skip some of your tests such as [this one](https://github.com/quicktype/quicktype/blob/master/test/inputs/json/priority/blns-object.json) unless you enable some "extra-tests" feature or something which CI would enable, it should make local development nicer :) Or maybe it could just be an error to try to quicktype pathalogical inputs? What do you think?

**Comment by dvdsgl** [comment]
@Ryman yes, thank you for the analysis and we agree that we need to split up some of our test data that needlessly requires target languages to emit absurdly large types: #559

**Comment by schani** [comment]
Closing this.  But please keep submitting Rust PRs!
