### ISSUE TITLE
Allow manually setting top-levels for JSON Schema input

### ISSUE THREAD

**Issue by Marwes** [quicktype/quicktype#518]
From https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json .

This schema defines all its types inside `definitions` of the schema which quicktype does not appear to output anything for (perhaps because the types don't appear to be reachable)?

Is this something that can worked around or that can be improved in quicktype?

Smaller reproduction
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "VS Code Debug Protocol",
  "description": "A json schema for the VS Code Debug Protocol",
  "type": "object",
  "definitions": {
    "ProtocolMessage": {
      "type": "object",
      "description": "Base class of requests, responses, and events.",
      "properties": {
        "seq": {
          "type": "integer",
          "description": "Sequence number."
        },
        "type": {
          "type": "string",
          "description": "One of 'request', 'response', or 'event'.",
          "_enum": [
            "request",
            "response",
            "event"
          ]
        }
      },
      "required": [
        "seq",
        "type"
      ]
    }
  }
}
```

**Comment by schani** [comment]
Correct, this schema only defines a top-level map type.

There are two options, if you can't modify the schemas:

1. Make one schema for each type that uses `"$ref"` to refer to the definition in the master schema.  To do that we'd have to finally implement cross-file references ;-)

2. We could add an option to quicktype to let you specify which schema definitions you want as top-level types.

What are your thoughts?

**Comment by schani** [comment]
We could make the option allow a wildcard which would take in all types.

**Comment by schani** [comment]
@Marwes Do you happen to know why the enum is defined with `"_enum"` and not `"enum"` in the Schema?  quicktype only recognizes the latter.  I've never seen the former before.

**Comment by Marwes** [comment]
No idea, might just be a typo I guess.

**Comment by gintsmurans** [comment]
Tried it, but it doesn't seem to be working. I have git version installed.

![image](https://user-images.githubusercontent.com/56369/45211269-7dcb8e00-b29a-11e8-9784-7a50c7466890.png)

**Comment by schani** [comment]
@gintsmurans The way to do it now is to specify it as part of the input filename on the command line:

    quicktype --src-lang schema "/my/schema.json#/definitions/"

**Comment by dzuluaga** [comment]
Did this work for anyone? I got an empty Converter.java without any definitions specified inside using `15.0.223`. Here's my command:
`quicktype --lang java --src-lang schema ./sample-json-schema.json#definitions`

This is the output:
```
package io.quicktype;

import java.util.*;
import java.io.IOException;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.core.JsonProcessingException;

public class Converter {
    // Serialize/deserialize helpers

    public static Object fromJsonString(String json) throws IOException {
        return getObjectReader().readValue(json);
    }

    public static String toJsonString(Object obj) throws JsonProcessingException {
        return getObjectWriter().writeValueAsString(obj);
    }

    private static ObjectReader reader;
    private static ObjectWriter writer;

    private static void instantiateMapper() {
        ObjectMapper mapper = new ObjectMapper();
        reader = mapper.reader(Object.class);
        writer = mapper.writerFor(Object.class);
    }

    private static ObjectReader getObjectReader() {
        if (reader == null) instantiateMapper();
        return reader;
    }

    private static ObjectWriter getObjectWriter() {
        if (writer == null) instantiateMapper();
        return writer;
    }
}
```

The only way to make it work for me was to specify each JSON Schema file separately in the same command line:

`quicktype --lang java -s schema schema1.json schema2.json schema3.json`

The output includes entity classes along with a Converter class with getters and setters for each class. Still, this is not optimal, as you can't pass a single dereferenced JSON Schema with multiple definitions. Any other suggestion? Thanks!

**Comment by dzuluaga** [comment]
Nevermind. It works if you include the trailing slash. In my case:

`quicktype --lang java --src-lang schema ./sample-json-schema.json#definitions/`
