### ISSUE TITLE
Treat unsupported string formats as strings

### ISSUE THREAD

**Issue by waywardmonkeys** [quicktype/quicktype#525]
When using this with the Vega Lite schema, I get an error due to Vega Lite's usage of `"format": "uri"` for some strings.

The error comes from https://github.com/quicktype/quicktype/blob/d2ede2aa52ca2bbf9829094b3c852aa2b28f99b3/src/JSONSchemaInput.ts#L257-L270

What's the best way to address this?

**Comment by schani** [comment]
Hmm, I guess we should just treat unknown string formats as regular strings?

**Comment by waywardmonkeys** [comment]
@schani That seems reasonable, and I can submit a pull request ... but could still output a warning. But it seems like most things do a `panic` and no warnings?

**Comment by schani** [comment]
Yeah, we don't really have a warning facility right now, other than the annotations in the renderer.  We might want to add a facility to thread warnings through from the JSON Schema input to the renderer.  For now just put a `FIXME` comment there.

**Comment by schani** [comment]
@waywardmonkeys Are you going to submit a PR for this?

**Comment by waywardmonkeys** [comment]
I can in 10 hours or so. I am about to sleep for the night.

**Comment by waywardmonkeys** [comment]
But if you want to fix it first, go ahead. :)

**Comment by schani** [comment]
I'll be patient ;)

**Comment by waywardmonkeys** [comment]
Fixed in #546.
