### ISSUE TITLE
String format guid not supported?

### ISSUE THREAD

**Issue by WillSullivan** [quicktype/quicktype#543]
Love the tool, but I was trying to create classes from the schema (via the io app) and kept getting this error

> String format guid not supported

I'd love to know what that means so I can fix. I'm afraid that the error is being generated by the website itself because I can't find that text anywhere in the codebase here, but hoping someone can shed some light on this.  Thanks.

**Comment by dvdsgl** [comment]
Hi, @WillSullivan. We've documented this issue recently at #525.

We will release a fix in the next day or two for this that will treat unsupported string formats as strings.

**Comment by WillSullivan** [comment]
Gotcha. I'll strip out the guids and manually add them to the code. Thanks!
