### ISSUE TITLE
Further oddities with vega-lite's JSON schema

### ISSUE THREAD

**Issue by waywardmonkeys** [quicktype/quicktype#575]
The definition for `DateTime` from the JSON schema is getting translated oddly:

```
/// Object for defining datetime in Vega-Lite Filter.
/// If both month and quarter are provided, month has higher precedence.
/// `day` cannot be combined with other date.
/// We accept string for month and day names.
#[derive(Serialize, Deserialize)]
pub struct EqualClass {
    /// One of: (1) integer value representing the month from `1`-`12`. `1` represents January;  (2) case-insensitive month name (e.g., `"January"`);  (3) case-insensitive, 3-character short month name (e.g., `"Jan"`).
    month: Option<Day>,
    /// A boolean flag indicating if date time is in utc time. If false, the date time is in local time
    utc: Option<bool>,
    /// Integer value representing the quarter of the year (from 1-4).
    quarter: Option<f64>,
    /// Integer value representing the date from 1-31.
    date: Option<f64>,
    /// Integer value representing the hour of a day from 0-23.
    hours: Option<f64>,
    /// Integer value representing the millisecond segment of time.
    milliseconds: Option<f64>,
    /// Value representing the day of a week.  This can be one of: (1) integer value -- `1` represents Monday; (2) case-insensitive day name (e.g., `"Monday"`);  (3) case-insensitive, 3-character short day name (e.g., `"Mon"`).   <br/> **Warning:** A DateTime definition object with `day`** should not be combined with `year`, `quarter`, `month`, or `date`.
    day: Option<Day>,
    /// Integer value representing the year.
    year: Option<f64>,
    /// Integer value representing the minute segment of time from 0-59.
    minutes: Option<f64>,
    /// Integer value representing the second segment (0-59) of a time value
    seconds: Option<f64>,
}
```

One thing is that the name is `EqualClass`. Another is that the type of the value of `month` is `Option<Day>` ... but the JSON schema for that field is:

```
        "month": {
          "anyOf": [
            {
              "$ref": "#/definitions/Month"
            },
            {
              "type": "string"
            }
          ],
          "description": "One of: (1) integer value representing the month from `1`-`12`. `1` represents January;  (2) case-insensitive month name (e.g., `\"January\"`);  (3) case-insensitive, 3-character short month name (e.g., `\"Jan\"`). "
```

**Comment by waywardmonkeys** [comment]
(This is with master as of ed466bad4d8b06ac6e6e90e0de76ef5429ca0085.)

**Comment by schani** [comment]
The reason for the month type being `Day` are

* from the point of view of quicktype they're identical - they're both unions of string and number, since we don't recognize range constraints (yet?)

* Our naming algorithm picks one of the names of the type more or less at random.

I have no idea why `DateTime` got renamed to `EqualClass`.  I fiddled with type attributes, which store names, recently, which might have caused this.

Remedies:

* [ ] Figure out and fix the cause of the weird renaming.

* [ ] Always generate unique types if they're definitions.  At least for the ones that we currently treat as "named" types, i.e. classes, unions, and enums.  We already do this for classes.

**Comment by schani** [comment]
The naming issue is potentially related to #530

**Comment by waywardmonkeys** [comment]
I don't mind looking at this some ... if I had some pointers for where to look. :)

If you've started already, then nevermind and good luck!

**Comment by schani** [comment]
@waywardmonkeys As for the first point, train your debugger on `Namer.assignNames` in `Naming.ts`.  There are two loops there.  The first one assigns names from given and inferred names, the second one adds prefixes for whatever is left to name.

For the second point: We do actually generate unique, fixed classes in `JSONSchemaInput.ts`, so I'm a bit surprised that they get combined - "fixed" means they shouldn't be, see `findSimilarityCliques` in `CombineClasses.ts`.  So maybe what happens is that we lose the fixed flag at some graph rewrite.  I'm sorry, all of this assumes a lot of internals knowledge, and almost none of it is documented :-(

**Comment by schani** [comment]
@waywardmonkeys I fixed the naming issue.  As a side effect we also don't lose any of the descriptions anymore.  Could you please check and see if there's anything weird?  The unique types issue is still there, but I probably won't get to it for a while because there are more pressing issues at the moment.

**Comment by waywardmonkeys** [comment]
@schani Thanks! I've been distracted these last couple of days, but I will get to this over the weekend!

**Comment by waywardmonkeys** [comment]
@schani I've started digging through this ... I've submitted pull requests #663 and #664 for 2 things that I found. I've got a few more things to either file bugs about separately or submit a PR myself. I'm going to close this as the issues that were being addressed here are resolved and the new things are entirely different. Thanks for your help!

**Comment by schani** [comment]
Cheers!
