### ISSUE TITLE
Dart language support

### ISSUE THREAD

**Issue by aloisdeniel** [quicktype/quicktype#583]
It could be great to have [Dart](https://www.dartlang.org) support.

Generated code could take inspiration from [json_serializable](https://github.com/dart-lang/json_serializable/tree/master/example/lib) package.

**Comment by schani** [comment]
@aloisdeniel Please consider contributing!

**Comment by schani** [comment]
@aloisdeniel we would love to have someone contribute this. If you're still interested, the best way to make this happen is to promote quicktype in the Dart community and recruit someone willing and able to work on this. We will happily guide them.

**Comment by Phrohdoh** [comment]
@schani This will have greater visibility if this ticket is open. Is that something we can do?

**Comment by schani** [comment]
Here are programming languages [more popular](https://www.tiobe.com/tiobe-index/) than Dart that quicktype doesn't support yet:

* C
* Python
* Visual Basic
* PHP
* Object Pascal
* Ruby
* R
* Perl
* Matlab

We'd love to support them all, and we will go out of our way to help anybody who wants to contribute support for them to quicktype, but we won't keep issues open for them until somebody commits to them.

How about we open one issue "Support more programming languages" as a catch-all?

**Comment by amorenew** [comment]
@schani dart is now popular as a cross-platform framework 
it would be nice to support dart json annotation https://github.com/dart-lang/json_serializable/tree/master/json_annotation
