### ISSUE TITLE
c++: only a single namespace is allowed

### ISSUE THREAD

**Issue by kirbysayshi** [quicktype/quicktype#589]
I recently ran into wanting more than one namespace for C++ generated code. My use case is that I wanted to wrap the generated code into a "project" namespace followed by a "spec" or "gen" namespace to denote that the code is generated or somehow spec based. But the quicktype tool only supports a single namespace!

Possibilities:

`--namespace project::spec`
`--namespace project,spec`
`--namespace project --namespace spec`

Any thoughts as to supporting this?

**Comment by schani** [comment]
What would you expect the C++ code to look like?  (Sorry, I'm a modern-C++ noob).

**Comment by kirbysayshi** [comment]
I'm a c++ noob too!

```
namespace project {
namespace spec {

// ... the code

} // namespace spec
} // namespace project
```

**Comment by schani** [comment]
Please give #591 a try.  I haven't tested that nested namespaces work yet, only looked over the generated code.
