### ISSUE TITLE
C++ - Nested enums

### ISSUE THREAD

**Issue by nuno407** [quicktype/quicktype#608]
I have been trying to use quicktype in the past days with no major issue. Today I'm facing what i think is a issue.
Imagine the following JSON Schema:

{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "MeterValuesRequest",
    "type": "object",
    "properties": {
        "connectorId": {
            "description":"connectorId",
            "type": "integer"
        },
        "transactionId": {
            "description":"transactionId",
            "title":"transactionId",
            "type": "integer"
        },
        "meterValue": {
            "description":"meterValue",
            "title":"meterValue",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "timestamp": {
                        "description":"timestamp",
                        "type": "string",
                        "format": "date-time"
                    },
                    "sampledValue": {
                        "description":"sampledValue",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "value": {
                                    "description":"value",
                                    "type": "string"
                                },
                                "context": {
                                    "description":"context",
                                    "type": "string",
                                    "enum": [
                                        "Interruption.Begin",
                                        "Interruption.End",
                                        "Sample.Clock",
                                        "Sample.Periodic",
                                        "Transaction.Begin",
                                        "Transaction.End",
                                        "Trigger",
                                        "Other"
                                    ]
                                },
                                "format": {
                                    "description":"format",
                                    "type": "string",
                                    "enum": [
                                        "Raw",
                                        "SignedData"
                                    ]
                                },
                                "measurand": {
                                    "description":"measurand",
                                    "type": "string",
                                    "enum": [
                                        "Temperature",
                                        "SoC",
                                        "RPM"
                                    ]
                                },
                                "phase": {
                                    "description":"phase",
                                    "type": "string",
                                    "enum": [
                                        "L1",
                                        "L2"
                                    ]
                                },
                                "location": {
                                    "description":"location",
                                    "type": "string",
                                    "enum": [
                                        "Cable",
                                        "EV"
                                    ]
                                },
                                "unit": {
                                    "description":"unit",
                                    "type": "string",
                                    "enum": [
                                        "Wh",
                                        "kWh"
                                    ]
                                }
                            },
                            "required": [
                                "value"
                            ]
                        }
                    }
                },
                "required": [
                    "timestamp",
                    "sampledValue"
                ]        
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "connectorId",
        "meterValue"
    ]
}

which generates a a enum class for each enum of proprietie and where each of this enum are of type std::unique_ptr.

Now, In my C++ code i have something like:
....
meterValueSampledValue sample;  //which generates a struct of type meterValueSampledValue (one of the propreties)
sample.value = "5";
sample.context. = contextcontext::other // --> this gives error. contextcontext is the enum class generated

Is possible to use the enum class directly insted of std::unique_ptr<contextcontext>

Thank you for the help,
Nuno

**Comment by schani** [comment]
@nuno407 That wouldn't be correct, because the `context` property is optional.  You can make it required by adding it to the `required` array.

**Comment by nuno407** [comment]
@schani ok.
Another thing:
When I have proprety that is a map of another property how should I create the map? Because if I push_back I'm copying the object which is impossible due to the std::unique_ptr. 
Tell if it is not explicit

**Comment by schani** [comment]
@nuno407 Could you please give a concrete example with code?

**Comment by nuno407** [comment]
Imagine the following quicktype generated file:

    /**
     * context
     */
    enum class contextcontext { interruptionBegin, interruptionEnd, other, sampleClock, samplePeriodic, transactionBegin, transactionEnd, trigger };

    /**
     * format
     */
    enum class formatformat { raw, signedData };

    /**
     * location
     */
    enum class locationlocation { body, cable, ev, inlet, outlet };

    /**
     * measurand
     */
    enum class measurandmeasurand { currentExport, currentImport, currentOffered, energyActiveExportInterval, energyActiveExportRegister, energyActiveImportInterval, energyActiveImportRegister, energyReactiveExportInterval, energyReactiveExportRegister, energyReactiveImportInterval, energyReactiveImportRegister, frequency, powerActiveExport, powerActiveImport, powerFactor, powerOffered, powerReactiveExport, powerReactiveImport, rpm, soC, temperature, voltage };

    /**
     * phase
     */
    enum class phasephase { l1, l1L2, l1N, l2, l2L3, l2N, l3, l3L1, l3N, n };

    /**
     * unit
     */
    enum class unitunit { a, celcius, fahrenheit, k, kVA, kW, kWh, kvar, kvarh, percent, v, va, var, varh, w, wh };

    /**
     * sampledValue
     */
    struct meterValueSampledValue {
        /**
         * value
         */
        std::string value;
        /**
         * context
         */
        std::unique_ptr<contextcontext> context;
        /**
         * format
         */
        std::unique_ptr<formatformat> format;
        /**
         * measurand
         */
        std::unique_ptr<measurandmeasurand> measurand;
        /**
         * phase
         */
        std::unique_ptr<phasephase> phase;
        /**
         * location
         */
        std::unique_ptr<locationlocation> location;
        /**
         * unit
         */
        std::unique_ptr<unitunit> unit;
    };

    /**
     * meterValue
     */
    struct meterValue {
        /**
         * timestamp
         */
        std::string timestamp;
        /**
         * sampledValue
         */
        std::vector<struct meterValueSampledValue> sampledValue;
    };

    struct meterValues {
        /**
         * connectorId
         */
        int64_t connectorID;
        /**
         * transactionId
         */
        std::unique_ptr<int64_t> transactionID;
        /**
         * meterValue
         */
        std::vector<struct meterValue> meterValue;
    };

Now In code we have 
    meterValueSampledValue AAA;
    AAA.value = "300";
    AAA.context` = contextcontext::Trigger; // this gives error because is not a std::unique_ptr but is easily corrected
    MeterValue BBB
    std::vector<meterValueSampledValue> values;
    values.push_back(AAA); //this gives error because AAA has a strong::unique_ptr inside which is copied when passed to push_back. How to solve this? 

This example is ok?
Thank you for your help @schani

**Comment by schani** [comment]
I see your problem.  Unfortunately I'm not a C++ expert.  We might want to add support for `shared_ptr` for such a case.

**Comment by nuno407** [comment]
And @schani ,
How is the correct way to:

    AAA.context = contextcontext::Trigger;

Without have to explicitly create a new unique_ptr?

**Comment by schani** [comment]
I believe you can do

```c++
*AAA.context = contextcontext::Trigger;
```

**Comment by nuno407** [comment]
I have tried it and gives me core dump. I will test it more extensively!
Thank you!

**Comment by nuno407** [comment]
Hi @schani,
For reference, i have tested and should be done something like this:

     sample.context = std::make_unique<OCPPMessages::contextcontext>();
     *sample.context = OCPPMessages::contextcontext::other;

My fault is that the pointer is created but the value is not defined at creation.

Thank you for your help.
