### ISSUE TITLE
Support POSTing GraphQL introspection query

### ISSUE THREAD

**Issue by Mange** [quicktype/quicktype#619]
When running `quicktype --graphql-introspect` the introspection query is sent to the endpoint using the GET HTTP method, which fails on a lot of server implementations.

Is this an oversight, or is there some reason for not using the more conventional POST method that is used by GraphQL Playground, GraphiQL, http-prompt and friends? Perhaps this is a new convention I have not previously seen and I should raise this issue on the upstream servers instead? :smiley: 

I see that the code that performs the introspection links to source code from another repo, but the original code actually changes the HTTP method in addition to just sending the query.

**Comment by schani** [comment]
This is most likely completely our fault, though I do find it somewhat strange that POST would be used for a pure query.  Are there some docs on this?  Could you point us to a few servers that only accept POST so we can test?

**Comment by Mange** [comment]
It has more to do with the fact that you want to send JSON payload to the servers, and that's not something you should do with GET requests.[1]

To send the query you'd need to encode it in the query string, which is done using another encoder (urlencoding instead of JSON) and then that needs to be explicitly dealt with in the server. Some web frameworks might support this transparently while others don't.

Do you still want a server to test on? I could see if I could dig one up that is publicly available.

[1]: https://stackoverflow.com/questions/978061/http-get-with-request-body

**Comment by schani** [comment]
@Mange Yes, please.

**Comment by schani** [comment]
@Mange Ping

**Comment by Mange** [comment]
I found one example:

```
› cat query.json 
{
  "query": "{ __schema { queryType { name } } }",
  "variables": {}
}

› curl -X POST -H "Content-Type: application/json" -d @query.json https://api.hollowverse.com/graphql
{"data":{"__schema":{"queryType":{"name":"RootQuery"}}}}

› curl -X GET -H "Content-Type: application/json" -d @query.json https://api.hollowverse.com/graphql
GET query missing.
```

I'm sure there are more servers with that behavior here: https://github.com/APIs-guru/graphql-apis

Basically, it looks like the most common JS framework version also adds support for the non-standard GET, while most other languages seem to not have it.

**Comment by schani** [comment]
Thanks!

**Comment by Mange** [comment]
Thank you! :heart:
