### ISSUE TITLE
Add option to have value types be nullable in order to support conditional serialization

### ISSUE THREAD

**Issue by lferrao** [quicktype/quicktype#622]
It would be nice if there was an option to have value types such as long created as long? instead, in order to support conditional serialization based on whether a value is set, so as to not systematically serialize members even if they have never been set.

**Comment by dvdsgl** [comment]
Value types are nullable if they are ever null in your sample data, or if your schema specified that they are nullable. Or did I misunderstand?

**Comment by dvdsgl** [comment]
You can also make all properties optional via  --allPropertiesOptionaAl.

**Comment by lferrao** [comment]
I am assuming that this is not something that can be done using
app.quicktype.io?

**Comment by dvdsgl** [comment]
Do you see the switch that says `Make all properties optional`?

**Comment by lferrao** [comment]
Now I do, but only after refreshing, it must be a new feature because I
haven't refreshed for a while.

**Comment by lferrao** [comment]
It works, thanks!

**Comment by dvdsgl** [comment]
Cool! We release many times a day so I recommend refreshing when you come back!
