### ISSUE TITLE
Simple Types omits top-level maps and arrays

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#623]

**Comment by schani** [comment]
Do we really need Simple Types anymore?  I find that both TS as well as Swift with `just-types` produce very nice no-frills type definitions.

**Comment by dvdsgl** [comment]
I agree, let's get rid of it.

**Comment by schani** [comment]
We can still make an alias to TS with just-types. That's usually the one I look at, or Swift. But I think TS is nicer because of the unions. On the other hand, Swift has integers...  so maybe Swift.
