### ISSUE TITLE
Shift the `-` on `// MARK` comments from the end to the beginning of the comment

### ISSUE THREAD

**Issue by multinerd** [quicktype/quicktype#628]
For example, when using alamofire extensions, the source code generates the string 

> // MARK: Alamofire response handlers -

Placing the dash on the end of the line results in the new line below the comment [Like this](https://imgur.com/Y93czVJ)

i think `// MARK: - Alamofire response handlers`. with the `-` at the beginning would make more sense so when its viewed in xcode, it looks [like this](https://imgur.com/k6jSctz)

**Comment by dvdsgl** [comment]
Would you care to submit the PR for this? Just change this one line:

https://github.com/quicktype/quicktype/blob/master/src/Language/Swift.ts#L956

You can even send the PR right from the GitHub web UI :)

**Comment by multinerd** [comment]
Will do
