### ISSUE TITLE
Add option for public fields in Rust structs

### ISSUE THREAD

**Issue by jkcclemens** [quicktype/quicktype#655]
Currently, structs like the one below are generated.

```rust
#[derive(Serialize, Deserialize)]
pub struct Report {
    fights: Vec<ReportFight>,
    lang: String,
    friendlies: Vec<Friendly>,
    enemies: Vec<Enemy>,
    #[serde(rename = "friendlyPets")]
    friendly_pets: Vec<Enemy>,
    #[serde(rename = "enemyPets")]
    enemy_pets: Vec<serde_json::Value>,
    phases: Vec<serde_json::Value>,
    title: String,
    owner: String,
    start: i64,
    end: i64,
    zone: i64,
}
```

However, it is often desirable to have each field public, like so:

```rust
#[derive(Serialize, Deserialize)]
pub struct Report {
    pub fights: Vec<ReportFight>,
    pub lang: String,
    pub friendlies: Vec<Friendly>,
    pub enemies: Vec<Enemy>,
    #[serde(rename = "friendlyPets")]
    pub friendly_pets: Vec<Enemy>,
    #[serde(rename = "enemyPets")]
    pub enemy_pets: Vec<serde_json::Value>,
    pub phases: Vec<serde_json::Value>,
    pub title: String,
    pub owner: String,
    pub start: i64,
    pub end: i64,
    pub zone: i64,
}
```

An option to toggle making all fields public would be great.

**Comment by dvdsgl** [comment]
This would be a trivial option to add, and I estimate would take you less than 10 minutes to implement if you're interested.

1. [Here's the line to edit](https://github.com/quicktype/quicktype/blob/master/src/Language/Rust.ts#L278) in the Rust renderer.
2. Add an option just like the [density option](https://github.com/quicktype/quicktype/blob/master/src/Language/Rust.ts#L31).

**Comment by jkcclemens** [comment]
Ooh, great! I peeked in, but TypeScript is not something I know very well, so I got lost. I'll take a crack at it.

**Comment by dvdsgl** [comment]
Godspeed! If you can write Rust, you can definitely handle TypeScript 😆
