### ISSUE TITLE
Option to not generate partial classes (c#)

### ISSUE THREAD

**Issue by lferrao** [quicktype/quicktype#670]
Would it be possible to have an option to generate normal (non-partial) classes?

**Comment by schani** [comment]
@lferrao Why would you prefer that?

**Comment by lferrao** [comment]
When using QT for complex object trees a lot of small classes are generated, and the keyword "partial" everywhere can make these files unnecessarily pretty verbose.

**Comment by schani** [comment]
We don't think this is worth the cost.
