### ISSUE TITLE
Boolean options cannot be disabled on CLI

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#671]

**Comment by schani** [comment]
I don't think we should use `--flag=true` style CLI options.  Boolean options are either at their default value, in which case no CLI option is required, or they are toggled, in which case a `--flag` or `--no-flag` is enough.  I think that if the default is `false`, the option should be `--flag` to turn it on.  If the default is `true` then the option should be `--no-flag` to turn off.  I think that has precedent.

I think we can do that automatically for `BooleanOption` - if the default is `false`, just prepend `no`.

**Comment by dvdsgl** [comment]
That sounds good
