### ISSUE TITLE
Improving swift inits with protocols

### ISSUE THREAD

**Issue by Yoloabdo** [quicktype/quicktype#697]
Hello, 
I've a suggestion that we move all init in swift to a protocol that all objects applies to, way less lines, for example something I did recently: 

```swift
  /// a simple protocol to confirm all your models to.
   protocol CodableInit {
       init(data: Data) throws
   }

   extension CodableInit where Self: Codable {
    init(data: Data) throws {
        self = try JSONDecoder().decode(Self.self, from: data)
    }
```

We can write inits for enums, structs in extensions and modify it for classes as I noticed it's using different ones

**Comment by dvdsgl** [comment]
This sounds good, although wouldn't it extend all Codables, even those not defined by quicktype, with these methods?

**Comment by Yoloabdo** [comment]
of course not, just any class/enum/struct that would add the protocol

**Comment by dvdsgl** [comment]
Oh I see.

**Comment by Yoloabdo** [comment]
How can I help ?

**Comment by dvdsgl** [comment]
Send us a pull request!

**Comment by Yoloabdo** [comment]
I'm not that good with typescript, still my issue 🗡
