### ISSUE TITLE
Prefix for generated models

### ISSUE THREAD

**Issue by mackoj** [quicktype/quicktype#705]
Hi,

It's could be great if we could add a prefix to generated model.

Thanks for this great tool,

**Comment by schani** [comment]
Which target language are you talking about?  Why do you want a prefix?  I take it you want to prefix every type name?

**Comment by dvdsgl** [comment]
The [Objective-C renderer](https://github.com/quicktype/quicktype/blob/master/src/Language/Objective-C.ts#L52-L57) supports a custom class name prefix. It would be easy to add this to any language.

**Comment by schani** [comment]
I don't think it makes much sense for languages that have namespaces.  But maybe I'm missing something.

**Comment by mackoj** [comment]
For the Swift language

**Comment by mackoj** [comment]
Sometimes in Swift some generated model name collide with Standard library names or other library names.

**Comment by schani** [comment]
We try to exclude names that collide with common type names.  Which names in particular cause the collisions for you?

**Comment by mackoj** [comment]
Result which is a popular library on iOS.

**Comment by schani** [comment]
Depends on #707
