### ISSUE TITLE
`type String = [String]` emitted in Swift for Figma Schema

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#716]
For the [Figma schema](https://gist.github.com/dvdsgl/0d57f2c69306c864eb1c35bcfd47116c) some strange Swift is emitted:

https://github.com/quicktype/figma-types/blob/d51dbe8c5954dfb07d37e1a98d37f58df294167f/swift/Figma.swift#L39

**Comment by schani** [comment]
The output and the schema you link to don't match up.  I don't get a `String = [String]` for the given schema on `master`.

**Comment by schani** [comment]
This should have been solved in #725
