### ISSUE TITLE
Allow me to specify which types are top-level in TypeScript input

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#729]
I have a current workaround in quicktype/figma-types where I:

1. Generate Schema `schema.json` from `types/*.ts`.
2. Maintain a separate schema, `toplevels.json`, that references the top-level types I want from `schema.json`.
3. quicktype `toplevels.json`.

I would rather be able to do something like:

```typescript
/**
 * A person.
 *
 * @toplevel
 */
interface Person {
  pet: Pet;
}

interface Pet {
  name: string;
}
```

Which would make `Person` top-level, but not `Pet`.

It would also be reasonable to let me do:

`$ quicktype types/*.ts --top-level FileRepsonse,ProjectFilesResponse,CommentResponse -o Figma.swift`

The advantage of the former is that it's easier to add to the web app, but I only need this in the CLI for now.

**Comment by schani** [comment]
Fixed in #770
