### ISSUE TITLE
gatherNames either loops infinitely or is very slow

### ISSUE THREAD

**Issue by krk** [quicktype/quicktype#751]
I am getting an error on https://app.quicktype.io/ with large input: 

`Internal error: Trying to resolve an allocated type reference with an incompatible one`.

* Input: https://raw.githubusercontent.com/Microsoft/TypeScript/master/src/lib/dom.generated.d.ts
* Renderer: C# (does not seem to matter).

**Comment by schani** [comment]
That internal error is fixed in #719, but we have a speed problem in `gatherNames` again.
