### ISSUE TITLE
Use lodash.has properly

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype#771]
Most of the functions we use are completely redundant:

* `_.contains(x, y)` is `x.indexOf(y) >= 0`
* `_.isString(x)` is `typeof x === "string"`

At least one of the functions we use does not what we use it for:

* `_.has(x,y)` is not the same as `Object.prototype.hasOwnProperty.apply(x, y)`.  If `y` is `"a.b"`, for example, it checks whether `x` has a property `a` which is an object with property `b`.

Also, importing it as `_` lets us not use `_` for unused arguments anymore, which is very useful.

**Comment by dvdsgl** [comment]
I agree with some of this, but I prefer the readability and succinctness of functions like `contains` compared to the `indexOf` alternative.

**Comment by schani** [comment]
I don't want to add a dependency, pollute the namespace, and do an additional function call just so I can save one character on something that is a common JS pattern.

**Comment by dvdsgl** [comment]
I think my experience of writing and reading quicktype source is improved by these functions. We can 'unpollute' the namespace (I think you are exaggerating by using the word 'pollute'), and the dependency is very small.

Also, as one of top 5 most popular JavaScript libraries, there's a good chance that contributors will be familiar with lodash and want to use it.

**Comment by dvdsgl** [comment]
More specifically, lodash is the most popular JavaScript library according to npm.

**Comment by schani** [comment]
Alright.  I deeply despise much of what we use of lodash, but I'm not willing to die on this hill.

**Comment by schani** [comment]
We're using `Object.prototype.hasOwnProperty.apply` in a few places, because it seems to be the only proper way to check whether an object has a property (You can't do `x.y !== undefined` because it will tell you that a property that's present but `undefined` is not present, and you can't do `x.hasOwnProperty(y)` because `x.hasOwnProperty` might not be what you think it is).

We should have a function for that.  `hasOwnProperty(x, y)`?

**Comment by dvdsgl** [comment]
What about `"y" in x`?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in

**Comment by schani** [comment]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/61363/38459079-1fb08c2a-3a5a-11e8-9915-d8d219ec43a3.png">

**Comment by dvdsgl** [comment]
And what is the deficiency in `lodash.has`? Is that the spec you want?

**Comment by dvdsgl** [comment]
`hasOwnProperty` sounds like a good name to me.

**Comment by schani** [comment]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/61363/38459176-6159e9a4-3a5b-11e8-9372-ec5706d0326e.png">

So we could use `lodash.has(x, [y])`
