### ISSUE TITLE
Make TypeScript input work on declaration files, too

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype#780]
In `typescript-json-schema`:

```typescript
    public getMainFileSymbols(program: ts.Program): string[] {
        const files = program.getSourceFiles().filter(file => !file.isDeclarationFile);
```

This filters out declaration files, which seems to mean files that end in `.d.ts`.  I don't think we want that.

We can fix this by either fixing it in `typescript-json-schema` or by using our compiler host to "rename" the files.  I prefer the former.

**Comment by mortyccp** [comment]
Sorry, I think this problem still exists.
https://github.com/quicktype/quicktype/blob/f18425279b0aeaf841a758808054fe9c50bb5329/src/quicktype-typescript-input/index.ts#L116
The above line is not passing the last option `onlyIncludeFiles`, so the original logic to filter out declaration file in `getMainFileSymbols` still applied.
