### ISSUE TITLE
Synthetic Hashable conformance not always possible for objects with collection properties

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#794]
[Swift 4.1's `Hashable` synthesis](https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md) does not work for types like:

```swift
struct Foo: Hashable {
  let bars: [Bar] // this property is not considered `Hashable`
}

struct Bar: Hashable {}
```

**Comment by schani** [comment]
I just ran into this.  There are quite a few non-hashable things, and the code we generate will more likely than not be incorrect.  `enum`s and `class`es can't synthesize `Hashable`, which also means that anything referencing them won't.

I think for the time being we should just disable Swift 4.1 "support" and decide what we want to do.  It seems to me that if supporting `Hashable` is important to us we should be able to generate code that implements it for `class` and `enum`, and probably also for the array case above.  The other option is to figure out whether the types contain anything where `Hashable` isn't synthesizable, and only synthesize it when it works for all types, which is odd to explain to users.

**Comment by dvdsgl** [comment]
Sounds good to me, let's disable for now.

**Comment by agisboye** [comment]
Any chance this could be turned into a (off by default) setting so it's available for those who need it?

Just like synthesis of Hashable and Equatable are opt-in in Swift, the same could be done for Swift code generated by quicktype. Users who know that all of their types will support synthesis can request it by opting in.

**Comment by agisboye** [comment]
Alternatively to a global setting, individual types could be opted in using an annotation. At least this should be possible when converting from TypeScript. I haven't tried other source/target pairs yet.

**Comment by dvdsgl** [comment]
@agisboye yes, we would accept a PR to add that. It should be easy.
