### ISSUE TITLE
Alamofire Extensions not working

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [quicktype/quicktype#795]
Alamofire Extensions not working for Swift Language

**Comment by schani** [comment]
@vaibhav-varshaaweblabs Could you please be more explicit?  What exactly is not working?  Could you provide us with the input data you're giving to quicktype?  Which Swift version are you using?

**Comment by thilakks** [comment]
return responseDecodable(queue: queue, completionHandler: completionHandler)
it is giving Use of unresolved identifier 'responseDecodable'

**Comment by thilakks** [comment]
iam facing that issue here how to solve that one extension DataRequest {
    // ...
    
    @discardableResult
    func responsePerson(
        queue: DispatchQueue? = nil,
        completionHandler: @escaping (DataResponse<Welcome>) -> Void)
        -> Self {
            return responseDecodable(queue: queue, completionHandler: completionHandler)
    }
}

**Comment by schani** [comment]
@dvdsgl ?

**Comment by dvdsgl** [comment]
@thilakks can you please use the Share Link feature to share your input and configuration?

**Comment by schani** [comment]
Closing this due to no response.
