### ISSUE TITLE
DateTimeOffset is written fully qualified

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#801]
We write `System.DateTimeOffset` rather than `DateTimeOffset`. Perhaps there's a good reason to do this, but `System.` is often left implicit.

**Comment by schani** [comment]
The more names we use unqualified, the more names we have to forbid.

**Comment by dvdsgl** [comment]
In this case, there would probably be other issues if we defined a type named DateTimeOffset (users would have to write QuickType.DateTimeOffset everywhere).

**Comment by schani** [comment]
I don't care either way.  Feel free to change it.
