### ISSUE TITLE
Be able to consume SOAP And/Or WSDL to generate XML Mappings

### ISSUE THREAD

**Issue by 9ParsonsB** [quicktype/quicktype#841]
I find it a huge pain having to write serialization mappings for XML / SOAP services.

QuickType has saved me a huge amount of time with mappings for JSON and so I would like to propose that QuickType be extended to also support [XML / SOAP](https://www.w3schools.com/xml/xml_soap.asp) and potentially [WSDL](https://www.w3schools.com/xml/xml_wsdl.asp)

### SOAP:
```XML
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <SomeRequest>
         <SomeProperty>1</SomeProperty>
         <OtherProperty>Hello</OtherProperty>
      </SomeRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

OR

### WSDL:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions http:force="" name="ServiceOrEndpointName" targetNamespace="NameSpace" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="NameSpace" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:documentation>
        Documentation about the service
    </wsdl:documentation>
    <wsdl:types>
        <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="SomeRequest" type="SomeRequestType">
                <xs:annotation>
                    <xs:documentation>Some Documentation for this request</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:complexType name="SomeRequestType">
                <xs:annotation>
                    <xs:documentation>Documentation about this type</xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element form="unqualified" name="SomeProperty" type="xs:int"/>
                    <xs:element form="unqualified" name="OtherProperty" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
</wsdl:definitions>
```
### C#:

```C#
namespace QuickType
{
    [SoapType("SomeRequestType")]
    public class SomeRequest
    {
        [SoapElement("SomeProperty")]
        public int SomeProperty { get; set; }

        [SoapElement("OtherProperty")]
        public string OtherProperty { get; set; }
    }

    public static class Converter
    {
        public static string SerializeObject<T>(T serialize)
        {
            var stringWriter = new StringWriter();
            new XmlSerializer(typeof(T)).Serialize(stringWriter,serialize);
            return stringWriter.ToString();
        }

        public static object DeserializeObject<T>(string serialized) => new XmlSerializer(typeof(T)).Deserialize(new StringReader(serialized));
        
    }
}
```

**Comment by dvdsgl** [comment]
Can you please include some sample inputs and outputs?

**Comment by 9ParsonsB** [comment]
@dvdsgl Updated.

Code is not tested but definatly compiles. Will update if any issues.

**Comment by 9ParsonsB** [comment]
``

**Comment by schani** [comment]
@9ParsonsB Are all properties strings in SOAP/WSDL?  What's the relationship between the two?  Can one be mapped to the other?  Is there an equivalent to classes in them?

**Comment by 9ParsonsB** [comment]
So there are quite a few parts to this issue:

1. Create `XmlTypeBuilder` to consume XSD (XML Schema) and convert to QuickType IR
2. Extend `CSharpRenderer`  to `XmlCSharpRenderer` and potentially `SoapCSharpRenderer` to create XML mapping as apose to JSON
3. Extend \#1 to take WSDL
4. Consume XML and convert to XSD (which can then feed into \#1)
5. Extend \#4 to consume SOAP

**Comment by schani** [comment]
You probably want to start with 2.  It's the easiest of them all, and it will enable you to already get XML code by using an XML->JSON converter for input.

**Comment by schani** [comment]
@9ParsonsB What's the status on this?  Do you need any help?

**Comment by 9ParsonsB** [comment]
@schani  `XmlCSharpRenderer` is still in progress. Not had much time to work on this lately. Will drop into slack when I get back into it.

**Comment by schani** [comment]
I'll close this.  If you do end up finishing it, please submit a PR.

**Comment by IeuanWalker** [comment]
@9ParsonsB @schani 
Could possibly use this library - https://github.com/abdolence/x2js or https://github.com/alabianca/xml-to-json

**Comment by ethindp** [comment]
Any update on this? I've been working with different XML data binding tools and the majority of them are (sadly) proprietary which is annoying. It would be great to have another tool that's free to try. My target language is, unfortunately, C++, but expat or Poco::XML (which is just a wrapper around expat) are good parsers for XML.
