### ISSUE TITLE
Remove dependencies in quicktype-core

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype#853]
These are the dependencies that are left in my restructured quicktype-core:

```
  package                   size       minified   gzipped
  chance@1.0.16             392.36 KB  214.3 KB   69.04 KB
  lodash@4.17.10            529.99 KB  69.01 KB   23.96 KB
  stream-json@0.6.1         220.95 KB  74.96 KB   20.88 KB
  handlebars@4.0.11         597.67 KB  72.14 KB   20.77 KB
  string-to-stream@1.1.1    184.75 KB  59.02 KB   16.79 KB
  immutable@3.8.2           139.68 KB  55.27 KB   15.15 KB
  pako@1.0.6                226.71 KB  44.21 KB   13.71 KB
  urijs@1.19.1              101 KB     41.31 KB   12.8 KB
  js-base64@2.4.3           65.52 KB   25.02 KB   7.59 KB
  unicode-properties@1.1.0  21.42 KB   7.75 KB    3.08 KB
  pluralize@7.0.0           12.42 KB   5.34 KB    2.11 KB
```

* `chance`: We only use this to get city and animal names for random variable names.  We can roll this ourselves, or just take the lists from `chance`.

* `lodash`: We don't need `lodash`.

* `stream-json`: This is the JSON parser we use, so until we have our own we're stuck with this.

* `handlebars`: This is for the templating prototype that didn't go far.  It requires basically no maintenance, so I'd like to keep it, but it would be nice if we could move that into CLI.

* `string-to-stream`: It's weird that this is so large.  We use it to streamify input strings, to make them palatable to our JSON parser.  It seems like it's contained in `string-to-stream`, though, so we wouldn't save anything by getting rid of it:

```
  stream-json@0.6.1,string-to-stream@1.1.1  226.96 KB  75.29 KB  20.94 KB
```

**Comment by schani** [comment]
I got rid of `chance`, `lodash`, and `handlebars` (I take it back - I don't want to keep it for the time being).

Unfortunately, we still have `graphql` in there, which I assumed I didn't need at all anymore, but our GraphQL input still depends on it, and it clocks in at 35kg gzipped.  I'd have to abstract input handling some more to be able to break it out into its own package, but I'm satisfied with where we're at right now.

**Comment by schani** [comment]
I abstracted the input handling, and GraphQL input is now its own package, so we got rid of `graphql` in `quicktype-core`.

**Comment by schani** [comment]
Merged in #868

**Comment by joelgallant** [comment]
@schani FYI, https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/Dart.ts relies on `lodash` in the most recent version of quicktype-core. It's not in dependencies at the moment.

**Comment by schani** [comment]
Thank you!
