### ISSUE TITLE
"Error: Maximum call stack size exceeded." on large JSON

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [quicktype/quicktype#855]
Source JSON: https://twitchemotes.com/api_cache/v3/images.json (~50MB, rate-limited, one hit per 30min)

Commandline: `quicktype images.json -l schema -o images.schema.json`

Ensure node is being run with high memory (`--max-old-space-size=8192` for example) as this takes ~6GB of memory.

Output:
```
quicktype images.json -l schema -o images.schema.json
Error: Maximum call stack size exceeded.
```

Error occurs after around 4 minutes of run-time. No other output.

Running node v10.1.0 on Windows 10 x64.

**Comment by schani** [comment]
It works if you use the `--no-enums` option.  I'll figure out why it crashes otherwise.  Thank you!
