### ISSUE TITLE
Support to include to_json and from_json methods within structures (C++)

### ISSUE THREAD

**Issue by daichij** [quicktype/quicktype#870]
Hi! Is it possible within quicktype C++ generation to move the from_json and to_json methods from being after all of the defined structures to being contained within each respective structure? The output format I'm looking for is something along the sorts of:
```c++
struct Example
{
    std::string key;

    std::string toJSON()
    {
        nhlohmann::json _j;
        _j["key"] = key;
       return _j.dump(); 
    }

    void fromJSON(const std::string& json)
    {
        nhlohmann::json _j = nhlohman::json::parse(json);
        key = _j["key"].get<std::string>();
    }
}
```
Essentially, the generalized format I'm aiming for is:

```c++
struct NamedType1
{
    <named type properties>
   std::string toJSON() {}
   void fromJSON(const std::string& json) {}
}

struct NamedType2
{
    <named type properties>
   std::string toJSON() {}
   void fromJSON(const std::string& json) {}
}
...
```

Is this possible? Thanks!

**Comment by schani** [comment]
If the main reason is to just have those member functions for convenience, then it should be very easy to keep the current `from_json` and `to_json` functions and implement the member functions by calling those.

I don't think that replacing the global functions is possible in non-trivial cases, because they need to be able to call each other to serialize and deserialize their members, and doing that operates on `json` objects, not on strings.

Also, are you sure you want a member function `from_json` that overwrites an existing instance with new data?

**Comment by daichij** [comment]
Having the member function overwrite the existing instance is part of the spec I've been provided, so that's what I have to do. I have managed to implement the member functions by using the from_json and to_json generator function.

How are the global functions called to serialize and deserialize the members? Does the nlohmann JSON get<>() method require the from_json and to_json methods in the nlohmann namespace to return custom-defined structures?

**Comment by schani** [comment]
It's been a while since I implemented the C++ target language, but yes, I'm pretty sure that the `get` requires `from_json` and `to_json`.

The easiest thing you can do to get the member functions that you wrote manually to be generated automatically is to modify the `emitClass` method and just add them there:

```
    private emitClass = (c: ClassType, className: Name): void => {
        this.emitDescription(this.descriptionForType(c));
        this.emitBlock(["struct ", className], true, () => {
            this.forEachClassProperty(c, "none", (name, jsonName, property) => {
                this.emitDescription(this.descriptionForClassProperty(c, jsonName));
                this.emitLine(
                    this.cppType(
                        property.type,
                        { needsForwardIndirection: true, needsOptionalIndirection: true, inJsonNamespace: false },
                        true
                    ),
                    " ",
                    name,
                    ";"
                );
            });
        });
    };
```

**Comment by daichij** [comment]
Yep! It's pretty much just adding the member function additions as the last lines in the emitBlock() that generates the struct, right?

**Comment by schani** [comment]
To do things "properly" we'd have to make the C++ target language and renderer classes more friendly for subclassing so that they can be extended like the [C# example](https://github.com/quicktype/quicktype-custom-csharp-example/blob/master/app.ts#L151).

**Comment by schani** [comment]
@daichij Correct, it seems that's all you'd have to do.

**Comment by daichij** [comment]
Awesome! Thanks for the help!

What sort of changes would you make the the C++ target language and renderer classes to make them more friendly for subclassing?

**Comment by schani** [comment]
Many of the methods in there that are `private` should be made `protected` for a start.  Then at least a subclass of `CPlusPlusRenderer` could override `emitClass`.  To make your particular case easier (and others like it) I would move the part inside the `emitBlock` into its own method `emitClassMembers`.  Your subclass would then only override `emitClassMembers`, first calling `super`, and then emitting the two new member functions.  We'd be happy to accept that as a PR if you're interested.

**Comment by daichij** [comment]
What all would you look for in that PR? Just the body of that `emitBlock` to be moved into a protected method, emitClasMembers, and have it replaced by the method call?

**Comment by schani** [comment]
That would be one thing.  I think all currently `private` methods should also be made `protected`.

**Comment by daichij** [comment]
Sounds good, I've submitted a PR for that. Let me know what I need to modify!
