### ISSUE TITLE
Qt C++ Support

### ISSUE THREAD

**Issue by Think7** [quicktype/quicktype#881]
Hello,

Just discovered this lovely tool, Great work!

Would you consider adding support for the Qt C++ framework?

I can provide templates, examples, use cases, or anything else need to handle implementation. It should be very similar to the existing C++ code generation, just using Qt's data types instead.

**Comment by dvdsgl** [comment]
Please provide the sample code you'd like quicktype to generate and let's see!

**Comment by dvdsgl** [comment]
By the way, this is the file you would edit if you're interested in contributing. It should be straightforward: 

https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/CPlusPlus.ts

**Comment by KitsuneDev** [comment]
Sorry to comment on such an old issue, but was this ever completed?
If not, would contributions to implement it be welcomed?

**Comment by dvdsgl** [comment]
Yes, we welcome contributions but we're very busy and don't have time to help you too much with them, but it should be pretty straightforward to add this.
