### ISSUE TITLE
Cant load 25mb json

### ISSUE THREAD

**Issue by Symbai** [quicktype/quicktype#882]
Would be nice to have a json file upload rather because large json content (25mb on disk) cannot be loaded / pasted.

**Comment by schani** [comment]
Everything runs on the client, so technically it wouldn't be an upload, but you're right that we should make a no-editor option for large files.

You can still use [the CLI](https://www.npmjs.com/package/quicktype), which works much better with large files.

**Comment by dvdsgl** [comment]
@Symbai did you try dragging-and-dropping your file into app.quicktype.io? What happens? I've used files close to this size before.

**Comment by Symbai** [comment]
@dvdsgl Didn't know it supports drag drop, tried with copying the content to clipboard and paste it into the json field. Drag drop works perfectly fine I can confirm.

Maybe add a small button to upload a file or a field saying "drop json file here" to make it a little bit more clear?

**Comment by dvdsgl** [comment]
Good suggestions, we will try to add a tip. This should also display when you first use quicktype:

![drag-and-drop-quicktype](https://user-images.githubusercontent.com/108197/40891610-87243f04-673d-11e8-8342-6e2f580252a9.gif)
