### ISSUE TITLE
React prop-types Support

### ISSUE THREAD

**Issue by Martin-Pitt** [quicktype/quicktype#903]
Any way to generate [React `prop-types`](https://github.com/facebook/prop-types) settings?
E.g. [http://rmosolgo.github.io/prop-types/#…](http://rmosolgo.github.io/prop-types/#%7B%22json%22%3A%22%7B%5Cn%20%20%5C%22name%5C%22%3A%20%5C%22Bluth%20Family%5C%22%2C%5Cn%20%20%5C%22parents%5C%22%3A%20%5B%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22George%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22age%5C%22%3A%2072%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Lucille%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22age%5C%22%3A%2068%5Cn%20%20%20%20%7D%5Cn%20%20%5D%2C%5Cn%20%20%5C%22children%5C%22%3A%20%5B%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Michael%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22age%5C%22%3A%2045%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22GOB%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22age%5C%22%3A%2041%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Lindsay%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22age%5C%22%3A%2037%5Cn%20%20%20%20%7D%5Cn%20%20%5D%5Cn%7D%22%2C%22function_wrapper%22%3Afalse%2C%22destructure%22%3Afalse%2C%22semicolons%22%3Afalse%2C%22alphabetize%22%3Atrue%2C%22dangle_commas%22%3Afalse%2C%22required%22%3Atrue%7D)

I was about to refer someone to this app, but I realised that it does not actually support prop-types, which surprised me.

**Comment by schani** [comment]
Please consider contributing.
