### ISSUE TITLE
error "Clipboard does not contain valid JSON" for any JSON

### ISSUE THREAD

**Issue by chopeen** [quicktype/quicktype#904]
I am getting the same error for any JSON content I try, even the Pokémon JSON from the [Marketplace](https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype).

The Output pane does not show any additional details.

---

Extension version: 10.24
VS Code version: 1.24.1

**Comment by schani** [comment]
Moved to https://github.com/quicktype/quicktype-vscode/issues/8
