### ISSUE TITLE
Support for Guids/Uuids

### ISSUE THREAD

**Issue by redwyre** [quicktype/quicktype#917]
It would be useful for quicktype to recognise Guids, in my case for use with C#.

The formats that I would personally like to see being recognised are:
"D" format: 00000000-0000-0000-0000-000000000000
"N" format:  {00000000-0000-0000-0000-000000000000}

**Comment by schani** [comment]
@redwyre If you're serious about contributing code for this, I can make the code I wrote recently to support stringified integers more generic so it's easier to add more custom string types.  Let me know.

**Comment by redwyre** [comment]
Sure, I'll give it a crack

**Comment by schani** [comment]
Ok, give me a few days.

**Comment by schani** [comment]
@redwyre I made it pretty easy to implement new transformed string types now: https://github.com/quicktype/quicktype/blob/master/doc/Transformers.md

The short version is: Search for `date-time` in `*.ts` and implement the equivalent for UUID.  If you run into any issues it's best to talk to us on [Slack](https://slack.quicktype.io).

**Comment by schani** [comment]
@redwyre What's the status on this?

**Comment by redwyre** [comment]
Sorry, I did a bunch of stuff then got stuck trying to test it on windows. I'll compare what you've done to my local changes and give it a go when I can :)

**Comment by schani** [comment]
@redwyre Sorry, it's already done - see commit 75229d5.  Please put it through its paces and report any issues.
