### ISSUE TITLE
references in a multi-file json schema don't resolve correctly 

### ISSUE THREAD

**Issue by ataibarkai** [quicktype/quicktype#921]
given a json schema encoded in the filesystem as such:
```
schemas/
   validate.json
   events/
      administration.json
      ads.json
      ...
   products/
      administration.json
      ads.json
      ...
```

references between files don't resolve correctly.

e.g. in `schemas/products/administration.json`, there is a reference to `../events/administration.json`.

quicktype seems to incorrectly infer `schemas/products/events/administration.json` rather than `schemas/events/administration.json` as the file path:

`quicktype -s schema schemas/validate.json -o models.swift`
-->
`Error: Could not fetch schema schemas/products/events/administration.json, referred to from schemas/products/administration.json#/allOf/0: Error: Input file schemas/products/events/administration.json does not exist.`

example:
[schemas.zip](https://github.com/quicktype/quicktype/files/2134909/schemas.zip)

**Comment by schani** [comment]
Thank you for reporting the issue!

I believe you're using `$id` incorrectly.  If you have a schema in `/schemas/products/administration.json` which has an `$id` field of `products/administration.json`, then a `$ref` within that schema is resolved relative to `/schemas/products/products/administration.json`.  I'm not an expert on this, so if you are, please correct me.  Otherwise please close the issue.

**Comment by ataibarkai** [comment]
Did you mean to write `/schemas/products/administration.json` rather than`/schemas/products/products/administration.json`?

At any rate, I believe it should resolve relative to `/schemas/products/`, not relative to  `/schemas/products/administration.json` (i.e. relative to the folder containing the file).
I am not an expert either, but a colleague with more experience with json schema seems to think so as well.
btw this scheme works fine for us when implementing schema validation on our ruby stack.

Btw, it looks like there is another related bug, when I specified a `./events/administration.json`, it got resolved to `schemas/products/products/events/administration.json` rather than to `schemas/products/events/administration.json`

**Comment by ataibarkai** [comment]
Ok, might really be a problem on our end then. I'll look into this.
Thanks for the info

**Comment by schani** [comment]
If you learn that quicktype does actually behave incorrectly, please report back.  I'll close the issue for now.

**Comment by schani** [comment]
quicktype actually does handle this incorrectly.

A `$id` in the root should not be resolved relatively.  That should at least fix your issues if you add a `.json` to the `$id`s.

Ideally, quicktype should also allow adding schemas from arbitrary files and use their root `$id`s to refer to them.

**Comment by schani** [comment]
@ataibarkai Could you please check out #962 ?  It fixes this issue.  Let me know if it works for you, please.  If you find any other problems with it, please submit issues with reasonably minimal test cases.

**Comment by nitzantomer** [comment]
I have a similar issue, and this branch seems to fix it , any idea when it will be merged and deployed to npm? Thanks.

**Comment by schani** [comment]
Done.  Should be on NPM in half an hour or so.

**Comment by cnaaq** [comment]
@nitzantomer 
I am facing the same problem as your last comment. did you manage to resolve it?

**Comment by cnaaq** [comment]
@nitzantomer 
use ``-S`` to append the other ``.json`` file so that the ref is fetched!
