### ISSUE TITLE
Make map inference less aggressive

### ISSUE THREAD

**Issue by raphaklaus** [quicktype/quicktype#924]
Steps to reproduce:

1) Open: https://app.quicktype.io/

2) Paste this JSON:

```
{
  "email": "",
  "qsc": "aqodfiqwid"
}
```

The interface is not created.

3) Now paste that:
```
{
  "email": "",
  "date": "aqodfiqwid"
}
```

The interface is created perfectly.

Language: TypeScript

**Comment by schani** [comment]
That's a weird case of our [map inference](https://blog.quicktype.io/markov/) going a bit gung-ho.  Thanks for reporting!

**Comment by schani** [comment]
Btw, you can always turn it off:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/61363/41951908-25710dee-7982-11e8-9d77-d0a215e2883f.png">

**Comment by raphaklaus** [comment]
Good to know. Unfortunately, this option is set on by default in the VSCode Extension. Is there a way to disable that one using some extension setting?

**Comment by schani** [comment]
No, the extension is very basic and doesn't have settings.  Would you consider contributing?  Adding settings would probably be pretty easy.

**Comment by raphaklaus** [comment]
Yeah, I think so. Just give the repo url and I'll fork it.

**Comment by dvdsgl** [comment]
https://github.com/quicktype/quicktype-vscode

**Comment by schani** [comment]
To tell quicktype what to do you have to surface the setting [here where `quicktype` is called](https://github.com/quicktype/quicktype-vscode/blob/master/src/extension.ts#L144).  The type that it takes is [defined here](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/Run.ts#L39).  Let us know if you have any questions, and/or come [join us Slack](https://slack.quicktype.io/)
