### ISSUE TITLE
Quicktype hangs after upgrading version

### ISSUE THREAD

**Issue by SurushS** [quicktype/quicktype#940]
We use quicktype in docker containers and it seems that since we updated to a newer version, the quicktype cli just hangs. It seems the issue started on **quicktype@15.0.30** because **quicktype@15.0.29** works fine. 

It's very simple to reproduce, so i'm wondering if i'm missing dependencies outside of what npm resolves by itself.

you can basically run these set of commands to get a docker up and running and installing npm on it and afterwards trying to run it. it hangs.
```sh
# run docker image of ubuntu
docker run -it ubuntu:latest bash

# install everything you need

apt-get update
apt-get install npm
apt-get install git

# you can select latest or anything between latest and 15.0.30
npm install -g  quicktype@latest

quicktype --version

```

Am i missing something? are there additional dependencies needed after version 15.0.29?

**Comment by schani** [comment]
I'm on it.

**Comment by schani** [comment]
The responsible commit seems to be 88e5f58ff5415e321a6d9d851df5a4e549637b8d.  I don't know yet why it would cause that hang.
