### ISSUE TITLE
Support for "oneOf", and "additionalProperties"

### ISSUE THREAD

**Issue by ndbroadbent** [quicktype/quicktype#953]
Thanks a lot for building quicktype, this is really awesome! I'm working on a [PDF generation service](https://formapi.io/) that generates JSON schemas for PDF templates, so I'm very excited to start generating some example code for these schemas.

I have a [demo template](https://formapi.io/templates/tpl_DEMO42TmQjTgsQ7q/edit) that I'd love to get working. [Here's the JSON schema](https://formapi.io/api/v1/templates/tpl_DEMO42TmQjTgsQ7q/schema).

The problem appears to be that I'm using `oneOf` for things like images:

```json
    "image": {
      "type": "object",
      "properties": {
        "oneOf": [
          {
            "base64": {
              "type": "string",
              "media": {
                "binaryEncoding": "base64"
              },
              "title": "Base64 Encoded Image"
            }
          },
          {
            "url": {
              "type": "string",
              "format": "url",
              "title": "Image URL",
              "description": "URL where the image can be downloaded."
            }
          }
        ]
      },
      "title": "Image"
    },
```

It also breaks if I include a value for `additionalProperties` in the root object (might be best to just ignore that if it's not used.)

But once I fix all those issues, it works beautifully! e.g. https://app.quicktype.io?share=GLf91me8dAQMBCLO7C1t
I can't wait to integrate this with my service.

**Comment by ndbroadbent** [comment]
But I'm actually going to generate a custom JSON schema for quicktype so that I can start using it now. But I'd be interested to see how this case could be supported

**Comment by ndbroadbent** [comment]
I think there's one more bug: It's setting the top-level title to "Coordinate". I can also see that when I choose the output language of "JSON Schema".

**Comment by schani** [comment]
@ndbroadbent That's not how `properties`/`oneOf` is used.  What your schema says is that the `Image` type has a property called `oneOf`, and its type schema is an array, which is invalid in JSON Schema.  What you actually want (I think) is something like

```
{
    "oneOf": [
        {
            "type": "object",
            "properties": {
                "base64": {
                    "type": "string",
                    "media": {
                        "binaryEncoding": "base64"
                    },
                    "title": "Base64 Encoded Image"
                }
            }
        },
        {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "format": "url",
                    "title": "Image URL",
                    "description": "URL where the image can be downloaded."
                }
            }
        }
    ]
}
```

**Comment by schani** [comment]
The top-level name is `Coordinate` because that's what it's set to in the UI:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/61363/42674302-6e2fe380-866f-11e8-8579-6f5e0931822b.png">

That name will override what's in the JSON Schema.

**Comment by schani** [comment]
Could you please file a new issue for the `additionalProperties` thing you mentioned, with a reproducible example?  Thanks!

**Comment by ndbroadbent** [comment]
Oh whoops, you’re right! Yeah I was putting oneOf inside the properties object, so that was an error on my part. I will open a new issue for the “additionalProperties” key. Thanks!
