### ISSUE TITLE
Infer property type based on patternProperties if pattern is .*

### ISSUE THREAD

**Issue by wader** [quicktype/quicktype#976]
Would it be useful to have special case for patternProperties `.*`? in that case `additionalProperties` should be ignored so i think it should be safe to assume all properties will have same type.

**Comment by wader** [comment]
Hi, don't know if common unfortunately. I'm using https://github.com/alecthomas/jsonschema which seem to output this. I could try to patch jsonschema instead if this seems wrong. Any idea what would be a proper way of expressing this?
```json
"a": {
  "patternProperties": {
    ".*": {
      "type": "string"
    }
  },
  "type": "object",
  "additionalProperties": {"type": "string"}
}
```
or maybe:
```json
"a": {
  "type": "object",
  "additionalProperties": {"type": "string"}
}
```
?

**Comment by schani** [comment]
If I understand the spec correctly, what `"patternProperties": { ".*": X }` means is that ALL properties have to conform to `X`.  That's in contrast to `additionalProperties` which only applies to properties not mentioned in `properties`.  If no `properties` are specified, the semantics should be the same.

Under which circumstances does `jsonschema` produce this?  Only for maps?

**Comment by wader** [comment]
Yes only maps i think. Sorry i should have been more clear i was thinking about no properties specified case and also mention my specific use case.

jsonschema produces this for maps https://github.com/alecthomas/jsonschema/blob/master/reflect.go#L194 and I noticed that the generated TypeScript code for `map[string]string` ended up as `{ [key: string]: any }`. Not sure if it's a good idea to make quicktype smarter or change what jsonschema produces.
