### ISSUE TITLE
numerical value of an enum?

### ISSUE THREAD

**Issue by harsszegi** [quicktype/quicktype#979]
Hello, how can I specify in the JSON Schema the numerical value for an enum?
E.g. I want to achive something like that:

enum Foo { Value1=1, Value2=2,....}

Thanks,

**Comment by schani** [comment]
We don't have that feature yet.  What's your use case?

**Comment by harsszegi** [comment]
We have a protocol description and the protocol is bad (in terms of Json Schema). Instead of 
real Json enums it uses integers for WeekDays and we wanted to convert those integers to enums
(e.g. Monday=1, Tuesday=2, etc.). Yes I know the protocol itself should have been fixed, but it is 
out of scope currently.

**Comment by schani** [comment]
One thing is that not we don't even represent enums numerically in some of our target languages, such as JavaScript.  But that's a minor issue.

Which particular target languages do you need this for?  For most this should be fairly straightforward to [implement via type attributes](https://blog.quicktype.io/customizing-quicktype/).  Would you consider contributing?

**Comment by harsszegi** [comment]
It is C++. I’ll check the link you have sent and will come back with regards to the contribution [I have anyhow changed the C++ renderer heavily for our use; transformed structs to classes, added getters/setters, etc.]

**Comment by schani** [comment]
It would be great if could contribute your modifications that would be useful to other users, too :-)

**Comment by schani** [comment]
Here is how we specify alternate names for enum members:

```
    "enum": {
      "type": "string",
      "enum": ["red", "green", "blue"],
      "qt-accessors": {
        "red": "fire",
        "green": "grass"
      }
    },
```

Numerical values should do something similar, such as

```
"qt-enum-values": { "red": 1, "green": 2, "blue": 4 }
```

**Comment by harsszegi** [comment]
Yups, this is exactly what I started to check, a bit buffled by the accessorNamesAttributeProducer, can't yet figure out the meaning of the "union" / "cases" usage in the implementation (e.g. whether it's relevant for me or not), will keep you posted how I progress.

**Comment by schani** [comment]
No, it shouldn't be. `forType` is what you need.

**Comment by harsszegi** [comment]
Great, it works, can you help me out with regards to one thing?
What do I have to use instead of the "???" below?
I want to access name's "string" representation, e.g. really the enum name, and not
 the SimpleName object itself...
Thanks,
        this.forEachEnumCase(e, "none", name => {
            if (caseNames.length > 0)
                caseNames.push(", ");
            caseNames.push(name);
            if (enumValues !== undefined) {
                const enumvalue = EnumValues_1.getEnumValue(enumValues, name.???????);
                if (enumvalue !== undefined) {
                    caseNames.push(enumvalue);
                    this.emitLine("xxxx ", enumvalue);  
                }
            }
        });

**Comment by harsszegi** [comment]
Awesome it works perfectly.

    enum DrawDayNo { FRIDAY = 5, MONDAY = 1, SATURDAY = 6, SUNDAY = 7, THURSDAY = 4, TUESDAY = 2, WEDNESDAY = 3 };

**Comment by schani** [comment]
That's wonderful! Could you submit a PR? I'll likely have some coding convention issues with it, but I'm happy to fix them if you can't be bothered. Please include a test case, too. There's currently no way to test that those enum values are actually produced, but we compare the output of every PR to the last master, so if it changed we'd at least notice.  Please also make sure that the whole test suite runs with your changes.

```
FIXTURE=cplusplus,schema-cplusplus npm test
```

**Comment by harsszegi** [comment]
aok, will give it a go keep you posted

**Comment by harsszegi** [comment]
Ok, solution merged
