### ISSUE TITLE
C# schema issue on Required

### ISSUE THREAD

**Issue by chrizy** [quicktype/quicktype#991]
Hi, I’m having the following problem trying to generate C# classes for the schema below

```
{
	"$schema": "http://json-schema.org/draft-03/schema#",
	"description": "Rightmove Realtime Datafeed Json Schema for send property request",
	"type": "object",
	"properties": {
		"network": {
			"type": "object",
			"id": "network",
			"required": true,
			"description": "Information about the network calling the API",
			"properties": {
				"network_id": {
					"type": "integer",
					"id": "network_id",
					"required": true,
					"description": "Unique Rightmove reference for this network"
				}
			},
			"additionalProperties": false
		},
		"branch": {
			"type": "object",
			"id": "branch",
			"required": true,
```
full schema: https://www.icloud.com/iclouddrive/0EpyBLiL-EQxFtiTHQJz_kKJw#SendPropertyDetailsRequestSchema.json

`quicktype -s schema SendPropertyDetailsRequestSchema.json -o test.cs`
returns
Error: `required` must be string or array of strings, but is true at SendPropertyDetailsRequestSchema.json#/properties/branch.

The schema has come from a third party and I’m not sure if the code generator or schema has an issue.
Any help appreciated, thanks

**Comment by schani** [comment]
In JSON Schema Draft 3 `required` had a different meaning.  It shouldn't be too hard to handle this, too.

**Comment by chrizy** [comment]
Yes that's fine. its public already. Thanks
